### ISSUE TITLE
[2.1] StringScanner named captures

### ISSUE THREAD

**Issue by headius** [jruby/jruby#1067]
https://bugs.ruby-lang.org/issues/8343

Also perhaps https://bugs.ruby-lang.org/issues/836

**Comment by olleolleolle** [comment]
_Background_: [Joni, the Java-based Oniguruma port](https://github.com/jruby/joni#using-named-captures) supports named captures. This issue is about using them in the StringScanner's `#scan` method ([source](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/ext/strscan/RubyStringScanner.java#L240)).

**Comment by jstemen** [comment]
It looks like this feature has already been implemented.  I wrote a couple simple tests to show that it works: https://github.com/jruby/jruby/pull/3761

**Comment by enebo** [comment]
This appears to have been fixed some time ago on 9k.  Resolving.
