### ISSUE TITLE
Java 1.8.0-ea-b113 [linux-arm] libjffi-1.2.so warning

### ISSUE THREAD

**Issue by brutuscat** [jruby/jruby#1215]
Coming from #899 (CC @headius )

It happened while trying to setting up jruby in my raspberrypi:

```
pi@rasputin ~ $ ruby -ve 'puts "it works"'
jruby 1.7.6 (1.9.3p392) 2013-10-22 6004147 on Java HotSpot(TM) Client VM 1.8.0-ea-b113 +indy [linux-arm]
it works

pi@rasputin ~ $ which gem
/home/pi/.rbenv/shims/gem

pi@rasputin ~ $ gem install bundler
Java HotSpot(TM) Client VM warning: You have loaded library /home/pi/.rbenv/versions/jruby-1.7.6/lib/jni/x86_64-Linux/libjffi-1.2.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

I moved the offending folder to a new directory and the warning disappeared.

**Comment by kares** [comment]
wonder if this is (still) relevant on JRuby 9.x as well ... anyone to confirm on ARM?

**Comment by justinsoong** [comment]
@kares yes still happening

**Comment by headius** [comment]
I'll try it on my ARM VM.

**Comment by headius** [comment]
Ok, so I tested on my aarch64 VM and I do not get this error; it seems to load correctly.

So, one of the following is likely true:

* This issue is fixed. @justinsoong claims it's still happening, so we need more information on that.
* This issue only affects 32-bit ARM. I will have to retry on one of the 32-bit ARM machines I have (none set up for dev right now).

Given that the original warning was because it tried to load the x86 library on ARM, I'm leaning toward this actually being ok in recent JRuby releases. If it were mistakenly loading x86 instead of ARM, I would expect it to try to load x86_64 instead of AARCH64, but it does not.

@justinsoong Can you show us what version of JRuby and how you trigger the warning?

**Comment by headius** [comment]
Let's call this fixed as of my comment above, and say it's good in the next major release after that (9.2.0.0).
