### ISSUE TITLE
Cannot make two symbols with same bytes and different encodings

### ISSUE THREAD

**Issue by DavidEGrayson** [jruby/jruby#1348]
I noticed that the symbol table in JRuby cannot seem to store two different symbols if the symbols happen to have the same bytes, even if the encodings are different.

Here is a script demonstrating the problem:

``` ruby
sym1 = "ab".force_encoding("UTF-16").to_sym
sym2 = "ab".to_sym
puts sym2.encoding

sym3 = "cd".to_sym
sym4 = "cd".force_encoding("UTF-16").to_sym
puts sym4.encoding
```

Here is the output from my shell demonstrating how MRI gets the encodings for sym2 and sym4 right and JRuby gets them wrong because of the pre-existing symbol in the symbol table:

```
$ ruby -v && ruby test_symbol_table.rb
ruby 2.0.0p0 (2013-02-24) [x64-mingw32]
US-ASCII
UTF-16
$ source use_jruby_179.sh
$ jruby -v && jruby test_symbol_table.rb
jruby 1.7.9 (1.9.3p392) 2013-12-06 87b108a on Java HotSpot(TM) 64-Bit Server VM
1.7.0_45-b18 [Windows 8-amd64]
UTF-16
US-ASCII
```

I think I will work on making a pull request to fix this; advice and objections are welcome.

I have made some progress on issue #1329 (properly setting the encoding of unmarshaled symbols), but before I can truly succeed in fixing that, I think I need to fix this and maybe a few other fundamental things about symbols.

**Comment by DavidEGrayson** [comment]
MRI fixed [that bug](https://bugs.ruby-lang.org/issues/10598), by the way.  I tested this issue again today with MRI 2.2.0-p0 (on Linux) and JRuby 9.0.0.0-pre1 (on Windows).  Here are the results I get when I run the original script from my first post:

```
$ ruby -v && ruby enc.rb 
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]
US-ASCII
UTF-16
```

```
$ jruby -v && jruby enc.rb
jruby 9.0.0.0.pre1 (2.2.0p0) 2015-01-20 d537cab Java HotSpot(TM) 64-Bit Server VM 24.45-b08 on 1.7.0
_45-b18 +jit [Windows 8-amd64]
UTF-16
Windows-1252
```

So the only thing that has changed since I reported this in December 2013 is that the encoding of sym4 changed from US-ASCII to Windows-1252, but it still seems that there is an underlying bug in the JRuby symbol table that makes it possible for symbols to have the wrong encoding.

**Comment by DavidEGrayson** [comment]
This issue still affects JRuby 9.0.0.0.  Here is the output I would get:

~~~~
$ jruby -v symtab.rb
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) Client VM 25.31-b07 on 1.8.0_31-b13 +jit [Windows 8-x86]
io/console not supported; tty will not be manipulated
UTF-16
UTF-8
~~~~

I'm just running the script posted at the very beginning of this thread.  MRI 2.2.0p0 (in Linux) outputs `US-ASCII` first and `UTF-16` second, as expected.

**Since this is a long thread, here is a quick recap:** The JRuby symbol table is designed to consider any two symbols to be the same if and only if they have the same bytes, but symbols also hold encoding information inside them.  This results in unpredictable behavior when evaluating a simple expression like `"ab".to_sym.encoding` because the answer you get depends on the current state of the symbol table, which depends on all previous Ruby code that has executed and all Ruby files that have been parsed.  MRI's symbol table takes into account the encoding of the symbols and does not suffer from this problem.  Another issue is that the encoding of a symbol in MRI is considered to be US-ASCII (instead of UTF-8) if it only consists of ASCII characters; JRuby doesn't implement that rule.

**Comment by enebo** [comment]
Current work does not integrate encoding into the symbol table so this will not be fixed with that work.  As it turns out our largest problem with fixing this is that all native extensions would need to assume an individual encoding or we would need to change their API.  I think this can be fixed in the future but it should lock-step with a more major way we refer to methods for things like callMethod().

**Comment by headius** [comment]
Ok so the work I did was not able to fix this because I had to back off the portion of that work that would hash symbols based on both bytes and encoding. That is the critical missing piece for this bug.

However I get a very different failure now from 9.1 forward:

```
[] ~/projects/jruby $ jruby ../jnr-posix/blah.rb 
EncodingError: invalid symbol in encoding UTF-16 :"\x61\x62"
  to_sym at org/jruby/RubyString.java:5892
  <main> at ../jnr-posix/blah.rb:1

[] ~/projects/jruby $ rvm jruby-9.2.1.0 do ruby ../jnr-posix/blah.rb 
EncodingError: invalid symbol in encoding UTF-16 :"\x61\x62"
  to_sym at org/jruby/RubyString.java:5888
  <main> at ../jnr-posix/blah.rb:1

[] ~/projects/jruby $ rvm jruby-9.2.0.0 do ruby ../jnr-posix/blah.rb 
EncodingError: invalid symbol in encoding UTF-16 :"\x61\x62"
  to_sym at org/jruby/RubyString.java:5868
  <main> at ../jnr-posix/blah.rb:1

[] ~/projects/jruby $ rvm jruby-9.1.17.0 do ruby ../jnr-posix/blah.rb 
EncodingError: invalid symbol in encoding UTF-16 :"\x61\x62"
  to_sym at org/jruby/RubyString.java:5254
  <main> at ../jnr-posix/blah.rb:1
```

The top version is current master with my recent symbol/marshal fixes.

@enebo Maybe you have some ideas here? Seems like UTF-16 symbols are getting messed up pretty badly.

**Comment by enebo** [comment]
yeah lack of encoding both bytes+encoding is a pretty big problem.  Adding encoding to hashing calc fixes it and this issue but then all String parameter-based (I call these id methods) APIs will not be able to find anything since it does not know encoding.  

The only possible solution is to assume that any String parameter method is not just iso8859_1 but is US-ASCII.  This would work for almost all current things until someone decides to callMethod on something with multiple byte characters.  UTF-8 would be a poor solution as symbols which are clean 7-bit are always converted to encoding USASCII but it would solve in case of mbc.  A hybrid of these two is:

  1. is clean 7 bit string say USASCII
  1. if it appears to not be 7bit then use UTF-8

Possibility?  Not totally sure.  This means byte-walking all strings to see if it is clean or not.  I don't like the idea of string scanning on strings but then the corollary of this would be to make a convenient calling API which takes ByteList and implore native extension authors to use that.  The the cost of string scanning would be upon older extensions and people unwilling to change to the newer API.

**Comment by headius** [comment]
We are close to having this fixed, due to work over the past couple years to propagate ByteList through the parser and into various ID tables. However there's still one missing piece.

MRI (at least as of the 2.5 branch) uses the following function to calculate the hash for the symbol's string (same logic as for string itself):

```c
st_index_t
rb_str_hash(VALUE str)
{   
    int e = ENCODING_GET(str);
    if (e && rb_enc_str_coderange(str) == ENC_CODERANGE_7BIT) {
        e = 0;
    }
    return rb_memhash((const void *)RSTRING_PTR(str), RSTRING_LEN(str)) ^ e;
}
```

We do have similar logic in our RubyString#hash logic, but this logic is not used by the symbol table since it stores only ByteList. Note that this meets our expectations above that the string's encoding should be considered as part of the hash.

The remaining fix would be to propagate this encoding inclusion – with the explicit exclusion 7-bit strings – into the logic for symbol's bytelist hashing.

**Comment by headius** [comment]
Oh also I noticed that CRuby's `String#intern` no longer scans for coderange here, and because we do the given script errors out.

```
$ jruby -Xbacktrace.style=full blah.rb
EncodingError: invalid symbol in encoding UTF-16 :"\x61\x62"
        getStackTrace at java/lang/Thread.java:1559
     getBacktraceData at org/jruby/runtime/backtrace/TraceType.java:242
         getBacktrace at org/jruby/runtime/backtrace/TraceType.java:53
     captureBacktrace at org/jruby/RubyException.java:371
             preRaise at org/jruby/exceptions/RaiseException.java:115
               <init> at org/jruby/exceptions/RaiseException.java:65
               <init> at org/jruby/exceptions/Exception.java:38
               <init> at org/jruby/exceptions/StandardError.java:38
               <init> at org/jruby/exceptions/EncodingError.java:38
   constructThrowable at org/jruby/RubyEncodingError.java:51
          toThrowable at org/jruby/RubyException.java:349
                 from at org/jruby/exceptions/RaiseException.java:81
    newRaiseException at org/jruby/Ruby.java:4125
     newEncodingError at org/jruby/Ruby.java:4096
               intern at org/jruby/RubyString.java:6052
```

Here's a patch to remove it, but it should be reviewed and compared to CRuby logic:

```diff
@@ -6048,10 +6063,6 @@ public class RubyString extends RubyObject implements CharSequence, EncodingCapa
     public RubySymbol intern() {
         final Ruby runtime = getRuntime();
 
-        if (scanForCodeRange() == CR_BROKEN) {
-            throw runtime.newEncodingError("invalid symbol in encoding " + getEncoding() + " :" + inspect());
-        }
-
         RubySymbol symbol = runtime.getSymbolTable().getSymbol(value);
         if (symbol.getBytes() == value) shareLevel = SHARE_LEVEL_BYTELIST;
         return symbol;
```

**Comment by headius** [comment]
This will be fixed by #6341, assuming there's no reason not to merge that.

**Comment by headius** [comment]
Unfortunately, even the work in #6341 can't get around a simple fact: by representing most identifiers in JRuby using a Java String, we can't avoid some ambiguous collisions of symbol encodings.

I've summarized the overall problem here: https://github.com/jruby/jruby/pull/6341#issuecomment-664588352

The bottom line is that without major surgery – surgery we are unwilling to perform due to impact and uncertainty of success – there will always be some limitations on how we represent 7-bit symbols and identifiers internally. My final recommendation there is that we simply ensure all paths to Symbol normalize ASCII-compatible 7-bit strings to US-ASCII, which integrates well with all ASCII-compatible encodings and which will guarantee such identifiers round-trip perfectly. This will mean broken examples like shown here, with invalid 7-bit bytes forced into a UTF-16 string, will not work as expected, and the resulting symbol will return those bytes to US-ASCII. I believe this is an acceptable limitation.

Marking this bug as "won't fix" but we have some additional work to formalize the US-ASCII identifier normalization (parser does it already, but clearly String#intern does not.)

**Comment by DavidEGrayson** [comment]
While my example might seem contrived, isn't it possible that there are valid UTF-16 strings where all the individual bytes happen to be 7-bit because of what code points are used?  For example, the UTF encoding of "hi" would be 4 bytes: "h\x00i\x00".  There are probably many more interesting examples out there.  You make it sound like UTF-16 symbols will work differently depending on what codepoints happen to be in them even if they are made from valid UTF-16 strings.

**Comment by headius** [comment]
@DavidEGrayson Your example of properly-encoded "hi" in UTF-16 would actually live as a UTF-16 symbol without issues, since ASCII-compatible string encodings will generally not include null bytes (the use of 7-bit here is slightly wrong; the real marker is "ASCII-compatible", which excludes UTF-16). The only case that would conflict is if some other encoding also represented "hi" as "h\x00i\x00".

The reason for this is that CRuby will generally discourage null bytes in strings because it uses C-level string operations to work with them under many circumstances. That UTF-16 works at all in Ruby is something of a minor miracle, and generally you'll see similar problems interacting with ASCII-compatible identifiers and system calls even in CRuby. Try running CRuby with the default internal encoding set to UTF-16 and you'll start to see large problems.

The more likely collision would be a UTF-8 string colliding with one of the CJK encodings that just happens to use the UTF-8 marker bytes in a different way, but I do not know of any simple examples. Most such encodings in general use today are aware of both ASCII and UTF-8 and take measures to avoid having byte-level collisions.

**Comment by headius** [comment]
As a simple explanation: the conflict only occurs if the **bytes** would be identical from encoding to encoding. Clearly that's not the case for UTF-16 and pretty much any other encoding, and it's likely not the case even for ASCII-compatible encodings with marker bytes since they're already designed **not** to conflict.

**Comment by DavidEGrayson** [comment]
OK.  One more suggestion would be to just add some metadata at the end of your JRuby string objects that are being used to represent symbols.  The metadata would say what encoding was used.  Then most of the code can keep treating those as strings without knowing about their structure, but code that prints them or sends them to an external system might have to chop off the metadata.

**Comment by headius** [comment]
@DavidEGrayson We have considered that possibility, but it has several problems:

* If we encode it as part of the string using proper-ranged characters, we end up with a bunch of strings floating around the system that otherwise look normal but have this "special" formatting we have to understand. Given the pervasiveness of Strings in JRuby and Java, it would be very difficult to guarantee that "normal" and "special" strings don't get mixed up.
* If we encode it as part of the string using invalid or control-ranged characters, we would be unable to debug those strings or use them to interact with the rest of the JVM. They would no longer be "valid" as far as Java's UTF-16 encoded characters go, and we would still have to "know" that one string is "special" and another is "normal".

Ultimately, any sort of clever embedding into the String itself leads to more difficult and insidious bugs than we have today, and ultimately would be more work than just making a new Identifier class, all to support a very small range of use cases that just aren't out there.

If you are able to find specific cases where we fall down under the current model, with the requirement that the strings involved be **properly-encoded characters**, we can certainly look at those cases (new issues please) and reevaluate what I've written here. As it stands today, the only known bugs introduced by this will involve **improperly-encoded characters** or exotic encodings, neither of which are well supported by the rest of Ruby anyway.
