### ISSUE TITLE
REXML failures when parsing SAML

### ISSUE THREAD

**Issue by ylansegal** [jruby/jruby#1469]
I am attempting to use the ruby-saml library with jruby. In my fork, I have made the appropriate changes to the gem to ensure that all tests are passing in MRI, but the XML parsing in jruby fails. Please take a look at the results in:

https://travis-ci.org/ylansegal/ruby-saml
https://travis-ci.org/ylansegal/ruby-saml/builds/18020223

All the failures seem to stem from REXML, but as far as I know that is part of the stdlib. 

Can someone point me in the direction of the discrepancy? 

Thanks,

**Comment by thujone** [comment]
If it interests anyone, the problem was that the version of Nokogiri used by ruby-saml did not support some of the jruby security methods properly. However, since then, Nokogiri has added support. We were able to overcome the issues we were having by simply upgrading to Nokogiri 2.6. For more info, see the jruby changelogs for Nokogiri.

**Comment by rtyler** [comment]
Looks like this issue has been resolved outside of the project, so I"m going to go ahead and close it
