### ISSUE TITLE
Problems calling getValue on Action object

### ISSUE THREAD

**Issue by rhinton** [jruby/jruby#1654]
I can't figure out what I'm doing wrong here.  The Java code works.  All the Ruby permutations fail.  How can I get the values I want?

EDIT: Conversation on [jruby-user] on 8 Apr 2014 confirms this is a JRuby bug.

deleteme.java:
```java
import java.io.*;
import javax.swing.*;

class Deleteme {
    public static void main(String args[]) throws IOException {
        String str;
        str = (String)TransferHandler.getCutAction().getValue(Action.NAME);
        System.out.println("Cut action name is: " + str);
        str = (String)TransferHandler.getCopyAction().getValue(Action.NAME);
        System.out.println("Copy action name is: " + str);
        str = (String)TransferHandler.getPasteAction().getValue(Action.NAME);
        System.out.println("Paste action name is: " + str);
    }
}
```

Results from running deleteme.java:
```
$ javac deleteme.java
$ java Deleteme
Cut action name is: cut
Copy action name is: copy
Paste action name is: paste
```

Now the ruby code in deleteme.rb:
```ruby
require 'java'

# Easier way to do this at file scope?  Normally I would just include_package
# 'javax.swing' in my class.
java_import javax.swing.TransferHandler
java_import javax.swing.Action


name = TransferHandler.getCutAction.getValue(Action.NAME)
puts "Cut action name is: #{name}"
name = TransferHandler.getCopyAction.getValue(Action.NAME)
puts "Copy action name is: #{name}"
name = TransferHandler.getPasteAction.getValue(Action.NAME)
puts "Paste action name is: #{name}"

# try really hard
action = TransferHandler.getCutAction
name = action.java_send(:getValue, [java.lang.String], Action.NAME)
puts "Cut action #{action.inspect} name is: #{name}"

# try another way; doesn't work because getValue takes an argument
#name = TransferHandler.getCutAction.value(Action.NAME)
#puts "Cut action name is: #{name}"

# try another way
meth = action.java_method(:getValue, [java.lang.String])
puts "Cut action name is: #{meth.call(Action.NAME)}"
puts "Cut action name is: #{meth.call(Action.NAME.to_java)}"
```

Results of running deleteme.rb:
```
$ jruby deleteme.rb
Cut action name is: 
Copy action name is: 
Paste action name is: 
Cut action #<Java::JavaxSwing::TransferAction:0x7548c02f> name is: 
Cut action name is: 
Cut action name is: 
$ jruby --version
jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on OpenJDK 64-Bit Server VM 1.6.0_22-b22 [linux-amd64]

C:\...> jruby deleteme.rb
[all names still missing]
C:\...> jruby --version
jruby 1.7.10 (1.9.3p392) 2014-01-09 c4ecd6b on Java HotSpot(TM) Client VM 1.6.0_37-b06 [Windows 7-x86]
```

**Comment by rtyler** [comment]
I've been tinkering with this a bit on JRuby 9k and I can't for the life of me figure out why the `getValue()` method won't be called correctly. But I did discover that you can access the name field on the `Action` object:

```
[16] pry(main)> TransferHandler.copy_action.name
=> "copy"
[17] pry(main)> TransferHandler.cut_action.name
=> "cut"
[18] pry(main)> TransferHandler.paste_action.name
=> "paste"
[19] pry(main)> 
```

**Comment by enebo** [comment]
I think this is a problem with how JI works and how the underlying Swing code is written.  I find this to be a primal limitation of our automatic coercion so it is not something we can actually fix.  I will mark as WONTFIX, but I will show you how to work around this and why it is happening.

Look at http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/6-b14/sun/swing/UIAction.java#72

We can see that this code is weird.  Namely: 'key == NAME'.  In JRuby, we convert between Java <-> Ruby string types.  When we get the value of NAME we convert to a Ruby String and then when we call getValue we convert it back to a Java String.  Since it is a new Java String then Java object identity fails and it returns null.  The good news is when people use Java Object identity with Strings they also tend to intern() the string value.  So you can make all this work by intern'ing your string:

```ruby
name = TransferHandler.getCutAction.getValue(Action::NAME.intern)
```
Things will work.   I wonder why they did not use .equals() in this code since this could not possibly be a hot path in Swing?

**Comment by rtyler** [comment]
@enebo this wasn't my ticket but I definitely appreciate you dropping some knowledge on us :)

**Comment by enebo** [comment]
@rtyler your excellent triaging and pondering what was wrong had me dig in.  So thanks for updating the issue.  This one was quite old :)

**Comment by rhinton** [comment]
Thanks all for the answers and information!
