### ISSUE TITLE
Ruby.getErrorStream() encoding bug

### ISSUE THREAD

**Issue by guai** [jruby/jruby#1879]
In Ruby.getErrorStream() PrintStream getting constructed from $stderr IO.
And it does not use its encoding settings.
I got char conversion errors in some cases where $stderr's encoding is utf-8.

jruby 1.7.13 release.

**Comment by MSNexploder** [comment]
While it is true that IOOuputStream pretty much ignores the actual RubyIO encoding and uses ASCII as hardcoded default I have a hard time creating a proper repro.

**Comment by kares** [comment]
@MSNexploder thanks ... and sice it was 1.7 while 9K did a rewrite on IO let's assume its fixed :dancing_men:

**Comment by headius** [comment]
This is the same issue as #8682 and #6588 and remains to this day. Since this bug was filed we added a way to specify a single encoding that IOOutputStream should use for all writes. However a further bug in #8686 breaks if the target IO has an external encoding and the same encoding is used for IOOutputStream (in order to no-op the encodes).
