### ISSUE TITLE
Method keyword arguments are destructive

### ISSUE THREAD

**Issue by indrekj** [jruby/jruby#2015]
ruby -v: jruby 9000.dev-SNAPSHOT (2.1.2p142) 2014-10-01 d3df63c Java HotSpot(TM) 64-Bit Server VM 24.65-b04 on 1.7.0_67-b01 [darwin-x86_64]

example:
```ruby
def foo(bar: 'baz'); end
opts = {bar: 'something'}
foo(opts)
opts #=> {}
```

In MRI 2.1.3 the same code:
```ruby
def foo(bar: 'baz'); end
opts = {bar: 'something'}
foo(opts)
opts #=> {:bar=>"something"}
```

**Comment by enebo** [comment]
Reported by someone else and I remembered this issue.  So some notes:

1. Caused by not dup'ing the kwargs list and our resolution algo removes elts to make sure all reqd elements are present (including duplicated values)
2. in IR each kwarg is received via instruction and we call this fairly expense extractKwargsHash each time

Simplest way to fix in the short-term would be to not remove elements from the kwargs list but #2 is pretty sucky so I don't think doing that is the long term fix.  We ultimately do not want to remove elts (+ dup) and we don't want to keep refiguring out the kwargs hash once per kwarg parameter.
