### ISSUE TITLE
"java -jar jruby-complete.jar -S gem install yard" creates uri:classloader: directory when GEM_HOME is not set

### ISSUE THREAD

**Issue by mkristian** [jruby/jruby#2488]
```
java -jar maven/jruby-complete/target/jruby-complete-9.0.0.0.pre1.jar -S gem install yard
Fetching: yard-0.8.7.6.gem (100%)
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared directory.
```
but also
```
$ ls -1
uri:classloader:
```

**Comment by mkristian** [comment]
this is already fixed

**Comment by sluu99** [comment]
Hi! I'm still seeing this issue in the 9000 release:

```

C:\Users\abc\Desktop\jrubydemo>java -jar .\jruby-complete-9.0.0.0.jar --version
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) 64-Bit Server VM 25.51-b03 on 1.8.0_51-b16 +jit [Windows 8.1-amd64]

C:\Users\abc\Desktop\jrubydemo>java -jar .\jruby-complete-9.0.0.0.jar -S gem install bundler
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared directory.

C:\Users\abc\Desktop\jrubydemo>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```

**Comment by mkristian** [comment]
well, not sure it says there is no write permissions into the classloader. the problem is that default GEM_HOME is inside the jruby-complete.jar so bundler can NOT install gems there.

if the whole thing does create some strange file like "uri:classloader:/" in your current directory then this bug is not fixed.

but to use bundler or even the gem command with jruby-complete.jar you need to set GEM_HOME to install gems.

**Comment by ndimitry** [comment]
I cannot install gems on Linux with the same error message. I've set all of  "GEM_HOME", "GEM_PATH", "gem_home" with no luck.
Calling `echo $GEM_HOME` results in value set by me `/home/myUser/.gem/jruby_jar
Still when calling `java -jar jruby-complete-9.2.14.0.jar -S gem env` the installation directory turns out to be:
`INSTALLATION DIRECTORY: uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared`
And the GEM PATHS being output is at first  `uri:classloader:/META-INF/jruby.home/lib/ruby/gems/shared` and only then `/home/ms/dnazaruk/.gem/jruby/2.5.0`

So seems that the issue still exists
