### ISSUE TITLE
undefined method `invoke_with_build_args' for nil:NilClass on Windows 7

### ISSUE THREAD

**Issue by michaelbuckner** [jruby/jruby#2525]
I saw a few other issues regarding this but could not find a definitive answer. Fresh jruby9K install with JRE.

Gem install gives the following:

ERROR:  Loading command: install (LoadError)
        load error: jopenssl/load -- java.lang.NullPointerException: null
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

I tried modifying the registry.rb per issue #2500 but it did not work.

Thanks

**Comment by enebo** [comment]
@michaelbuckner To clarify you used our installer which ship with its own JRE?  Other questions is 32vs64 bit win7?  Did you run time CMD?  I test with win7 64bit ultimate but I usually test without jre because I have multiple jvm's installed on my windows machine.

**Comment by michaelbuckner** [comment]
I tried both. 

Initially I had JRE 1.8. I removed that + jruby and did the 64bit installer with bundled JRE.

Time/timezone on my machine are correct.

**Comment by headius** [comment]
Ok, I need a backtrace from this and an example session with commands you ran, as you ran them.

To get a backtrace, I think the gem command has a --trace or --verbose or something. Also get a trace passing -Xbacktrace.style=raw to JRuby, to get the full Java trace in case it is being Rubyfied.

Really can't do much until we get the full backtrace, since it works ok for me here.

**Comment by mkristian** [comment]
there is very similar looking issue here: https://github.com/torquebox/jruby-maven-plugins/issues/65
both using jdk1.8 but can not reproduce it either

**Comment by headius** [comment]
I just confirmed gem install is working on Windows after making a few updated fixes. Please confirm with pre2.
