### ISSUE TITLE
Enumerator containing range does not pass a block variable

### ISSUE THREAD

**Issue by hiukkanen** [jruby/jruby#2632]
(1..1).each &method(:puts)
    
    # cruby => 1
    # jruby =>

**Comment by headius** [comment]
Looks like it's not turning it into a proc that receives one argument, and it's just putsing the newline.

**Comment by headius** [comment]
A test with an intermediate method shows it's passing nil out for some reason. Going to debug.

**Comment by headius** [comment]
So the problem was an optimization we made to Range#each many years ago, where it checks if the target block actually wants arguments before it creates and passes them. However the logic for turning a method into a proc was always setting up that proc to report that it takes no block arguments.

Fix coming for 1.7 and 9k.
