### ISSUE TITLE
support method access for nested Java classes

### ISSUE THREAD

**Issue by kares** [jruby/jruby#2639]
assuming Java integration already works in a Java-like manner : 
`java.lang.management.MemoryType.value_of('HEAP')`

shall support Java-like `java.awt.Desktop.Action.valueOf('OPEN')`
instead of "only" Ruby-like `java.awt.Desktop::Action.valueOf('OPEN')`

**Comment by headius** [comment]
So you're basically saying to allow nested classes to be accessible with "." as well as "::", yes?

**Comment by kares** [comment]
yy, since JRuby allows `java.awt.Desktop` where by Ruby semantics it "should" be `java.awt::Desktop`
... and we also handle nested upper-case package names right `basePackage.UglyPackageName.Klass`

I'm just not sure if there aren't any draw-backs for introducing fully Java *"like"* nested class access ?

**Comment by rohitdumbre86** [comment]
Hello Guys!! I want to work on this particular issue. Any pointers as in can I maven build the jruby java code?

**Comment by kares** [comment]
@rohitdumbre86 hey! believe some of those can be figured out - it's quite a std `mvn` build.
... check *.travis-ci.yml* or there's also https://github.com/jruby/jruby/blob/master/BUILDING.md

if you need to better understand JRuby's Java Integration - look for commits tagged with **[ji]** prefix

**Comment by MariuszCwikla** [comment]
I prepared solution, although I am not 100% it's the best one.
I'm handling inner class case from within `method_missing`. Please review.

**Comment by edipofederle** [comment]
@headius / @kares I think this one could be closed as well. Could you please check it? thx

**Comment by headius** [comment]
@edipofederle It seems like we eventually decided that using `method_missing` to solve this was too heavy-handed, at least based on #5924, so this behavior has never been added. I am still of the opinion that inner classes are best accessed using `Foo::Bar` syntax, but it should be possible to make `Foo.Bar` work without `method_missing` (the list of inner classes is static and known at load time).

So... we can close this if @kares no longer wants to support `Foo.Bar`, but should leave it open otherwise.
