### ISSUE TITLE
Compiling app with embedded JRuby has RELEASE_6 warning

### ISSUE THREAD

**Issue by bensummers** [jruby/jruby#2733]
If you compile an application which embeds JRuby 1.7.19, you get this warning:

    Supported source version 'RELEASE_6' from annotation processor 'org.eclipse.sisu.space.SisuIndexAPT6' less than -source '1.8'

It's probably just a cosmetic issue.

**Comment by headius** [comment]
It looks like something in your build is trying to load or run our AnnotationBinder, which had @SupportedSourceVersion(RELEASE_6). Because you are running on a Java 8 JVM, you were warned because that annotation is used to indicate the *latest* version our annotation processor supports.

I'm modifying AnnotationBinder to just override getSupportedSourceVersion and always return the latest version that JVM supports, since it's a pretty simple processor and should support future source versions without modification (and if it doesn't, we'll find out pretty fast).

**Comment by headius** [comment]
This is fixed in 870f979. I'd like to know more about your build, though, so I can understand why our annotation processor was getting loaded. You must be using the Sisu container for your app, yes? It seems like whatever annotation processing Sisu does is overreaching and touching annotations from the libraries contained within.

I will file a separate bug to remove the build-time annotation processor, since I don't think it's useful to anyone but us.

**Comment by bensummers** [comment]
We don't use Sisu.

Here's the application: https://github.com/oneis/haplo

It uses its own application server because it is, roughly speaking, an application framework and container for JavaScript plugins which work within a built-in database-like application. It runs as a Java app which embeds JRuby which is scripted by JavaScript.

Internally we built it with ant, and the open source version uses Maven.

However, I can't seem get Maven to output the warning, which is either because Maven is a different complication environment which isn't affected, or I don't know Maven well enough.

If you're particularly interested in this issue, I can send you the ant version of the build script.

Incidentally, I've been meaning to work out why this complete bodge was needed for the latest 1.7.x releases: https://github.com/oneis/haplo/blob/master/framework/boot.rb#L50 -- need to find the time to write a nice test case.
