### ISSUE TITLE
[Truffle] Error adding Complex to Fixnum

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#2805]
Adding Fixnum to Complex works but the reverse doesn't.
```
$ ~/Documents/jruby/bin/jruby -X+T -e 'puts 1 + Complex(1, 2)'
-e:1:in `+': Truffle doesn't have a case for the org.jruby.truffle.nodes.core.FixnumNodesFactory$AddNodeFactory$AddUninitializedNode node with values of type  java.lang.Integer=1 Complex(org.jruby.truffle.runtime.core.RubyBasicObject) (TypeError)
	from -e:1:in `<main>'

$  ~/Documents/jruby/bin/jruby -X+T -e 'puts Complex(1, 2) + 1'
2+2i
```
Do we need to add a RubyComplex class to add a specialization for this? Or how would you resolve this?

This is used in matrix stdlib.

**Comment by chrisseaton** [comment]
This is more complicated that with other types as `Complex` doesn't exist as far as the Java code knows. We solved this with `Rational` by implementing `Fixnum + Rational` as `Rational + Fixnum` - which I think for some reason is in fact the correct thing to do.

https://github.com/jruby/jruby/blob/49dc6b43fec628c7560edb116f79938108ec9cd4/truffle/src/main/java/org/jruby/truffle/nodes/core/FixnumNodes.java#L129-L137

Where that isn't possible, like divide, we do `convertToRational(Fixnum) + Rational`.

https://github.com/jruby/jruby/blob/49dc6b43fec628c7560edb116f79938108ec9cd4/truffle/src/main/java/org/jruby/truffle/nodes/core/FixnumNodes.java#L552-L563

**Comment by bjfish** [comment]
@chrisseaton  I can try to implement this if you haven't done so already

**Comment by chrisseaton** [comment]
Yes please

**Comment by chrisseaton** [comment]
It's probably much much easier now we have `ruby()` actually.

**Comment by bjfish** [comment]
@chrisseaton Can you recommend how to add a Specialization like this for a non-core class? e.g. Matrix

How would the guard look? Would the specialization go in FIxnumNodes even though this is non-core?

I need a Fixnum#/ and I think this can be implemented in terms of Fixnum#* `fixnum * matrix.inverse`

**Comment by chrisseaton** [comment]
I don't see why `Fixnum#/` should have to know about a non-core class? In MRI the C code doesn't know about `Matrix` (I don't think it does), so why should our implementation?

I think you might find that through coercion, `Fixnum / Matrix` actually becomes `Matrix / Matrix` (or maybe something called `Scala / Matrix`, and it's not due to special casing of `Matrix` in `Fixnum#/` - take a look in the Rubinius kernel at `Numeric#redo_coerced` and `#math_coerce`, and then `Matrix#coerce`.

We could do with a solid understanding of this - resist the temptation to special case for `Matrix` - I think there is a general solution in here somewhere.

**Comment by bjfish** [comment]
@chrisseaton  The spec that is failing is call the coerce_spec (library/matrix) so I think you are on the right track but I don't know where the coercion happens.
```ruby
1 / Matrix[[0,1],[-1,0]]
```

**Comment by chrisseaton** [comment]
Rubinius does

```ruby
  def divide(o)
    Rubinius.primitive :fixnum_div
    redo_coerced :/, o
  end
  alias_method :/, :divide
```

Maybe look at adding a specialisation to `Fixnum#/` that does `redo_coerced :/, o`.

**Comment by eregon** [comment]
Yes, this is just the `coerce` mechanism, actually even Rational and Complex do not need a special case, just Float and Integer (Fixnum and Bignum) since they don't coerce well between each other.
So there is `Matrix#coerce`, which returns a Scalar (a class defined by Matrix) and then Fixnum should just do the `redo_coerced` on it.

**Comment by eregon** [comment]
I think it's even preferable to not have Rational/Complex specializations unless we need it, since the class check is imprecise and there is a better mechanism already defined by the normal semantics.

**Comment by bjfish** [comment]
@chrisseaton Added `redo_coerced` to `/` here: dce0852ff7e7399ed66da694eea6d6229de61dda . Let me know if Rational/Complex should be removed.

**Comment by chrisseaton** [comment]
Can you try removing them and see what happens? You need to try running any of the benchmarks as well (do `bench debug` to get the command, add `--loop` to the end and let it run for a while) as the Rubinius implementation of `Time.now.to_f` uses `Rational` and that gets pulled into what gets compiled for the benchmarks. If that seems ok and the specs pass it's fine to remove.

**Comment by eregon** [comment]
We don't use Time anymore I think, but the monotonic time. Also, if Process::CLOCK_MONOTONIC fails, `Time#-(Time)` is used which should have the proper optimization to not go by rational (converting time to float could additionally lose precision).
