### ISSUE TITLE
Cannot kill thread with Readline

### ISSUE THREAD

**Issue by e2** [jruby/jruby#2841]
The following never finishes on JRuby (never gets to the final line):

```ruby
require 'readline'

th = Thread.new { Readline.readline }
th.join(0.5)

Thread.new do
  sleep 2
  th.kill
end

STDERR.puts "continuing in foreground"
th.join # hangs here

STDERR.puts "Never gets here... ;("
```

Here are 2 relevant threads from a dump: https://gist.github.com/e2/d58ec0374ce58e7c7495

I don't know if this behavior is intended or not (I just want to quit Readline from a different thread).

**Comment by headius** [comment]
This is a known issue, and in fact there's another bug about it (at least one): jruby/jruby#2383

There's currently no way to do readline non-blocking – a requirement for interrupting it – because we use the jline library. It builds off standard JDK stdio objects, which are not interruptible.

See linked issue for more details.

**Comment by e2** [comment]
Thanks! I was searching for "blocking" and "io" in the issues and couldn't find it. Didn't expect Readline to be in the title.
