### ISSUE TITLE
Rakefile/rakelib depends on Ant, will not boot if not present

### ISSUE THREAD

**Issue by headius** [jruby/jruby#2965]
I guess I never noticed before that we can't even boot our rakefile without ant being available, since it is used for several of our test tasks. We should try to eliminate or ease this requirement:
- We could fetch ant during bootstrap, like we do with other test requirements.
- We could rewrite the parts of our rake build to not use ant targets.

**Comment by chrisarcand** [comment]
I recently experienced this while setting up JRuby and trying to [run the tests for activerecord-jdbc-adapter](https://github.com/jruby/activerecord-jdbc-adapter/blob/9b5bf8b9440dc58715fe3122a555931f82bf2927/rakelib/compile.rake#L3)); doing any rake command results in `Errno::ENOENT: No such file or directory - ant`.

It's pretty confusing for someone new to JRuby as searching around there's no gem that packages it (that is plainly obvious, anyway) and it's easy to expect it to just be packaged with JRuby since JRuby is what contains the ant integration.

As @headius mentioned on IRC, perhaps the best course of action is just to have a gem that pulls ant from maven (and maybe move the ant integration in core to there, too)

**Comment by kares** [comment]
@chrisarcand guess, for AR-JDBC that is simply a lot of heritage (technical debt) along the years...
master does not use ant anymore (does javac directly) but the rails-5 branch didn't start off master :)
... so it is what it is - still would say its not that crucial in this case - only a few would compile AR-JDBC

**Comment by headius** [comment]
@kares I don't think anything would be too severely affected if we moved the ant support to a gem. It could even be one we install by default. The main issue is really that we have this ant support but don't ship ant, so it depends on it being available on the system. With ant use fading away, that's less and less likely.

**Comment by headius** [comment]
So after chatting with @mkristian we realized a nasty wrinkle: the Ant integration depends on the `ant` executable being present, so it can retrieve an appropriate environment for ant, its plugins, etc. So it's not simply a matter of including the jar; we would need to also include the plugins and plumbing that are part of a full Ant dist.

Given that, it seems like it might be a better choice to just present a better error indicating that Ant should be installed on the local system. The user can generally figure out how to do that, and we get the full dist to use.

I considered the possibility of just creating an Ant gem that actually includes the full layout and bin dir, but installing that gem when JRuby is in PATH would take over the `ant` command from the system.

It might be possible to include a full Ant dist vendored in the rake-ant gem, but I didn't explore that possibility.

**Comment by headius** [comment]
I think this can be resolved once @enebo has a chance to review the PR and gem.

**Comment by headius** [comment]
The rake/ant integration has been moved to the rake-ant gem and included as a default gem. The error message has been fixed to request that the user install ant.
