### ISSUE TITLE
Process.spawn with redirect causes ConcurrencyError

### ISSUE THREAD

**Issue by djberg96** [jruby/jruby#3038]
jruby 9.0.0.0.rc1 (2.2.2) 2015-06-10 a0bf3b3 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]
Yosemite
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

It seems JRuby does not like redirecting output on Process.spawn:

    # Where test.rb is a very simple puts "hello" kind of script
    Process.spawn("test.rb", :out => ['test.log', 'a'])

    # Result
    ConcurrencyError: Detected invalid array contents due to unsynchronized modifications with concurrent users
      spawn at org/jruby/RubyProcess.java:1295

**Comment by bbrowning** [comment]
The :out key's array can have 1, 2, or 3 values in it. This ConcurrencyError is actually thrown because of an ArrayIndexOutOfBoundsException thrown at https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyArray.java#L4398. That gets called via https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/util/io/PopenExecutor.java#L1537. It looks like the code here and on line 1528 of PopenExecutor assumes that requesting an array index past the end of the array will return nil. But, what's happening instead is this ConcurrencyError gets thrown.

The code needs to either check array length before accessing elements or use another method besides `eltOk` that returns nil instead of throwing.

**Comment by headius** [comment]
@bbrowning Ahh nice investigation. Simple enough to fix; I'm sure this was a flaw in my port, where I used a different method from MRI (i.e. one that errors rather than returning nil).

**Comment by headius** [comment]
I added a spec for this behavior, but it appears JRuby is having trouble running these redirecting specs within RubySpec. We'll have to address that separately, but the reported spawn form should be working properly now.

**Comment by djberg96** [comment]
Excellent, thank you!
