### ISSUE TITLE
Requiring a bare file from current directory works unexpectedly

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#3049]
`test.rb`:
```ruby
puts "BUG"
```

```bash
$ bin/jruby -e 'require "test"'
```

This should not find the file (well, unless "." is in `$:` but it is not) and raise a LoadError.

The last update to RubySpec revealed the bug.
9da2c2c7b48259c3e90044aeb33d606d8944d163 should be revert once it is fixed.

**Comment by headius** [comment]
This is a side effect of our desire to present both Ruby and Java command-line semantics. When running the "java" command at the command line, the current directory is added to the classpath. We do the same in our launcher. This causes Ruby files to be accessible because they can be found via classloader searching.

I'm not opposed to removing this classpath entry, but it would be a change from how the "jruby" command has run for many years.

**Comment by mkristian** [comment]
I did removed this java "feature" on my https://github.com/jruby/jruby/tree/test-dir-globs-on-uri-classloader branch where I want to move the last bit of the old "LoadService" into the new one.

I always thought this is the desired feature since we have already such a test which does not fail for other reasons (ruby PWD != java PWD)

but whatever is decided here I would incorporate it in the above branch.

**Comment by mkristian** [comment]
fixed with #3073 which also added a test for this
