### ISSUE TITLE
[Truffle] Threads might not exit sleep state when interrupted

### ISSUE THREAD

**Issue by nirvdrum** [jruby/jruby#3131]
It's currently possible for a Ruby thread to ignore being awoken.  It looks like a race condition of sorts, so you might need to run the following example a few times to see the issue:

```
THREAD_COUNT = 10

@pool = THREAD_COUNT.times.map { Thread.new { sleep } }

@pool.each { |t| t.run }

@pool.each(&:join)
```

Some debugging notes:

When a Ruby thread goes to sleep (`Kernel#sleep`), its sleep status is set to `Status.SLEEP` [1].  When `Thread.run` is called, the status is changed to `Status.RUN` and the Java thread backing the Ruby thread is interrupted [2].  The exception handler checks the status and sets a flag to determine whether to break out of the sleep [3].

Based on some logging I added, the exception handler is seeing the thread's status as `Staus.SLEEP`, not `Status.RUN` and as such, it's not setting the `shouldWakeUp` flag.  When the exception is propagated, it's handled in `ThreadManager` and stops propagating up [4].  At this point, `result` is `null` and the action corresponding to the thread sleep is executed again [5].  This is the normal flow of events (i.e., the block is supposed to be executed again), but since the `shouldWakeUp` flag wasn't properly set, the thread goes to sleep again and interrupt is now lost.

[1] -- https://github.com/jruby/jruby/blob/b91c9ed69b55319f7bc4dc7af60c480003753354/truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ThreadManager.java#L122
[2] -- https://github.com/jruby/jruby/blob/5c8c448200acd951b6346912384d5ce55aa1c8a6/truffle/src/main/java/org/jruby/truffle/runtime/core/RubyThread.java#L173-L176
[3] -- https://github.com/jruby/jruby/blob/b91c9ed69b55319f7bc4dc7af60c480003753354/truffle/src/main/java/org/jruby/truffle/nodes/core/KernelNodes.java#L1829-L1831
[4] -- https://github.com/jruby/jruby/blob/master/truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ThreadManager.java#L134
[5] -- https://github.com/jruby/jruby/blob/master/truffle/src/main/java/org/jruby/truffle/runtime/subsystems/ThreadManager.java#L103-L105

**Comment by pitr-ch** [comment]
I think `t.run` can be executed before the thread goes to `sleep`, so the thread is never woken up.

**Comment by nirvdrum** [comment]
@pitr-ch But I'm quite clearly seeing it being woken up.  The `status` value is just wrong by then.  I suppose what could happen is it's woken before it goes to sleep, which sets the status to `Status.RUN`, the code that sets the status to `Status.SLEEP` is then run, the Java thread goes to sleep and sees the interrupted status flag is set, triggering the exception handler.

**Comment by eregon** [comment]
There is a tension between the script shown and this spec:
https://github.com/jruby/jruby/blob/master/spec/ruby/core/thread/shared/wakeup.rb#L26
Essentially, the spec expects the Thread#run to be lost if invoked before the thread is sleeping (so the thread stays on sleep until line 27 is executed) while the code above does not.

To show the problem in the snippet, you could call
`Thread.current.run` before sleep and then they would not wake unless some other thread calls `run` while they are sleeping`

The reason the code above does not deadlock on MRI is just luck because the threads in the pool get in sleep before the main thread continues. A fix to make sure they are sleeping would be:
`@pool.each { |t| Thread.pass until t.status == "sleep" }`.

I am not sure what is better.

**Comment by eregon** [comment]
I implemented the MRI semantics, so Thread#wakeup/run only wakes up the thread if it is actually sleeping.
We now have a separate flag for wakeUp (and not reusing status) for clarity.
If we change our mind it's easy enough to move to "no wakeup lost" semantics and tag the spec.
