### ISSUE TITLE
Update Java integration specs for RSpec 3+

### ISSUE THREAD

**Issue by headius** [jruby/jruby#3159]
Our Java integration specs (spec/java_integration) are currently not RSpec 3+ compatible. At a minimum, they used methods deprecated in late 2.x, and they also use syntax that's deprecated with noisy warnings in 3+. They should be updated to RSpec 3.x syntax and our build updated to pull in RSpec 3.x when bootstrapping local dev environment.

This change should be made on both jruby-1_7 and master branches.

**Comment by headius** [comment]
Run the specs with `rake spec:ji`.

These specs can be run directly, but there's some classpath stuff that will fail.

**Comment by PragTob** [comment]
(interested in trying to tackle this)

should/might be doable with transpec and I've done this sort of thing before. No idea how big the spec files are but seems like a fun little project, I got vacation the week before JRubyConf.EU so this time I might REALLY get to my first JRuby commit.

**Comment by headius** [comment]
Go for it! Right now the specs don't run *at all* with RSpec 3+, so it's pretty annoying when I have that instlaled.

**Comment by myronmarston** [comment]
@PragTob sounds like you're already aware of this (given you mentioned transpec) but in case you're not: [our upgrade guide](http://rspec.info/upgrading-from-rspec-2/).  Please reach out if you run into any difficulties.

**Comment by PragTob** [comment]
@myronmarston did not know the upgrade guide - thanks :) More or less what I'd have done - transpec and co worked beautifully for us over at [shoes4[(https://github.com/shoes/shoes4) :)

**Comment by kares** [comment]
been avoiding [some](https://github.com/jruby/jruby/commit/27dc38359f97ff556f8f57b124e67092ef564ea6) of the [noizy](https://github.com/jruby/jruby/commit/db7c1113f320a6a0598ea150f3caeb330886946a) [warnings](https://github.com/jruby/jruby/commit/84a20516d305c3fc35b52c4875513595877beb90) on jruby-1_7 branch ... was also hoping to review the JI pends

@PragTob in case you're doing it do jruby-1_7 branch instead of master - for less potential conflicts :)

**Comment by PragTob** [comment]
@kares shouldn't it end up on both branches? I don't know how you actually work with that? I thought of starting at one branch and then cherry picking the commit? Sorry never maintained a project with 2 major branches :)

**Comment by kares** [comment]
@PragTob **jruby-1_7** is merged periodically to master so it will end up there as well (just a hint - if its easier for you to roll of master we can cherry-pick them from there ... although it might be a bit more work)

**Comment by envygeeks** [comment]
You would have to travel into the master branch anyways because there are added spec files so it doesn't matter if you cherry pick those changes, I would simply just merge and let it fail, edit the failed files (it looks to me like < 10 would fail -- probably not that much work) and then edit the added files and change them.  All in all this project could probably be completed in a few days.

**Comment by kares** [comment]
done at https://github.com/jruby/jruby/pull/3265
