### ISSUE TITLE
jruby.org/tryjruby/ - Page Not Found

### ISSUE THREAD

**Issue by dummey** [jruby/jruby#3168]
Looks like the tryjruby page down. 

http://jruby.org/tryjruby/

**Comment by headius** [comment]
I started to fix it but we need to do a few extra things to make it work:

* Both the jnlp and the applet require a signed jruby-complete.jar.
* The complete jar does not currently contain either JRubyApplet or IRBConsole in usable forms, since they are both part of the jruby-readline library now. That needs to be fixed.

At least the page is there and formatting right, though :-)

**Comment by headius** [comment]
@mkristian I know how to sign a jar, but I'm not sure the best way to get a usable complete jar with JRubyApplet and IRBConsole available at top-level. Thoughts?

**Comment by headius** [comment]
Closing in favor of jruby/jruby.github.io#3.
