### ISSUE TITLE
jruby 9000: java.lang.InternalError when using `gem` command

### ISSUE THREAD

**Issue by aharpervc** [jruby/jruby#3179]
Not sure what other details would be useful...

```
c:\Users\Public>jruby -v
jruby 9.0.0.0 (2.2.2) 2015-07-21 e10ec96 Java HotSpot(TM) Client VM 24.51-b03 on 1.7.0_51-b13 +jit [Windows 8-x86]
```

```
c:\Users\Public>gem
null:-2:in `GetFinalPathNameByHandle': java.lang.InternalError: Should not get here
        from null:-1:in `getFinalPath'
        from null:-1:in `getRealPath'
        from null:-1:in `toRealPath'
        from null:-1:in `toRealPath'
        from null:-1:in `run'
        from null:-1:in `run'
        from null:-2:in `doPrivileged'
        from null:-1:in `<clinit>'
        from null:-1:in `getTimeZone'
        from null:-1:in `getTimeZone'
        from null:-1:in `setDefaultZone'
        from null:-1:in `getDefaultRef'
        from null:-1:in `getDefault'
        from null:-1:in `initializeCalendar'
        from null:-1:in `<init>'
        from null:-1:in `<init>'
        from BeanManagerImpl.java:25:in `<clinit>'
        from null:-2:in `forName0'
        from null:-1:in `forName'
        from BeanManagerFactory.java:15:in `<clinit>'
        from Ruby.java:248:in `<init>'
        from Ruby.java:330:in `newInstance'
        from Main.java:266:in `internalRun'
        from Main.java:225:in `run'
        from Main.java:197:in `main'
```

**Comment by enebo** [comment]
This is super weird and seemingly dying down in the JVM itself.  Here is a different but similar bug report for this on JVM:

https://bugs.openjdk.java.net/browse/JDK-8046686

This one seems to involve creating a softlink but I am wondering if this is something the JVM expects you will have some permission to access and ???? .

Since this is dying before JRuby has even finished booting you can see how much further it goes by adding:

```text
JRuby -Xmanagement.enabled=false -S gem list
```
This will not enable our MBean admin support which most likely you are never using...I sort of expect something further down the line in bootstrapping to fail with a different stack though.

This is happening so early when bootstrapping JRuby itself I am suspecting something about win8 env which is not playing nicely with Java OR maybe more than one Java installed and some envs are crossed OR less common situation we have never seen (e.g. installed on some UNC with unexpected permissions).  Just brainstorming, but this appears on the surface to involve the JVM not being happy deep down.

**Comment by enebo** [comment]
No info in a couple of years.  Please re-open if you can provide some more info.
