### ISSUE TITLE
Initial $LOAD_PATH depends on JRUBY_HOME in jruby-complete-9.0.0.0

### ISSUE THREAD

**Issue by CeesZ** [jruby/jruby#3257]
The default $LOAD_PATH for jruby-complete-9.0.0.0 depends on the environment variable JRUBY_HOME
In my opinion that is not desirable if you are running an application in a JAR, when you
need the initial $LOAD_PATH for access to the standard libraries and do not want
(accidental) interference with the libraries from outside the JAR. 
If an application wants to take note of JRUBY_HOME it should do so by inspecting the
environment variable itself. 
jruby-complete-1.7.19 did NOT depend on JRUBY_HOME, see following example: 

C:\Projects\XLibriz\lib\java>CD C:\Projects\XLibriz\lib\java

>SET JRUBY_HOME=C:\jruby-1.7.19

>java -jar jruby-complete-1.7.19.jar -e "puts $LOAD_PATH.join(\"\n\");"
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9

>java -jar jruby-complete-9.0.0.0.jar -e "puts $LOAD_PATH.join(\"\n\");"
Warning: JRuby home "C:/jruby-1.7.19" does not exist, using C:\Users\user\AppData\Local\Temp\
C:/Users/user/AppData/Local/Temp/lib/ruby/2.2/site_ruby
C:/Users/user/AppData/Local/Temp/lib/ruby/stdlib

>SET JRUBY_HOME=C:\Data (existing directory, no Ruby files)

>java -jar jruby-complete-1.7.19.jar -e "puts $LOAD_PATH.join(\"\n\");"
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9

>java -jar jruby-complete-9.0.0.0.jar -e "puts $LOAD_PATH.join(\"\n\");"
C:/Data/lib/ruby/2.2/site_ruby
C:/Data/lib/ruby/stdlib

>SET JRUBY_HOME=

>java -jar jruby-complete-1.7.19.jar -e "puts $LOAD_PATH.join(\"\n\");"
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9/site_ruby
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/shared
file:/C:/Projects/jruby-complete-1.7.19.jar!/META-INF/jruby.home/lib/ruby/1.9

>java -jar jruby-complete-9.0.0.0.jar -e "puts $LOAD_PATH.join(\"\n\");"
uri:classloader:/META-INF/jruby.home/lib/ruby/2.2/site_ruby
uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib

**Comment by headius** [comment]
So are you proposing that the jruby-complete.jar should ignore JRUBY_HOME? And it sounds like that was the case in 1.7.19 and earlier?

**Comment by mkristian** [comment]
I have to add that jruby whether it runs from filesystem install or from
jruby-complete.jar or from modular maven artifacts, it depends on the
GEM_HOME, GEM_PATH, JARS_HOME, BUNDLER_GEMFILE, etc. there is no real
isolation from the environment, unless you take care of those -
IsolatedScriptingContainer does eliminate a few of those. for example if
people use RVM then java -jar jruby-complete.jar will see the gems for
current ruby from RVM and this is even true when this is MRI ruby.

it is not so to determine the fact that you are running from
jruby-complete.jar or any other classpath with jruby-core.jar +
jruby-stdlib.jar from filesystem installation which is basically
jruby-core.jar + JRUBY_HOME set to some filesystem location.

**Comment by CeesZ** [comment]
Yes, exactly.

I use JRUBY-COMPLETE as the base for a standalone application jar, which should run on any computer with the right operating system.

Users should not have to worry about the environment it runs in. In a sense the ‘complete’ part of the name says it all. In cases where JRUBY_HOME is needed, it is probably better to use JRUBY.

But maybe others have different use cases in favor of the use of JRUBY_HOME  in JRUBY-COMPLETE

**Comment by headius** [comment]
I have one idea how to do this...if we set a different main for the complete jar versus the jruby.jar we put into a distribution, we'd know how it was launched. They'd essentially do the same thing, but when running from jar main it wouldn't look at environment variables...only properties.

The other option would be to never look at environment vars in the Java code, and rely on the launchers to do it. Most people who use the env vars use our bin/jruby.bash or the native equivalent, which could just take those environment variables and put them in the right properties.

**Comment by mkristian** [comment]
let's say when there is a jruby-home on the classpath, i.e. there is
META-INF/jruby.home then we ignore JRUBY_HOME and use the one from the
classpath. that brings us back to jruby-1.7.x behaviour - I guess.
but we still obey jruby.home system property !

if this is way to go, I can spent implementing it.

there are other places where we try to detect whether we are running from
"jar" to make respawning of ruby possible for ruby libraries like rake.

the problem is not only jruby-complete but also jruby-jars.gem which has
two jars and one of it the jar from the distro. i.e. it should setup the
classpath with two jars: jruby-core-complete and jruby-stdlib

and if I just collect all my jars from org.jruby:jruby artifact than it
should behave the same as jruby-complete as these are exactly the same
classes. same the jars from jruby-jars.gem. all three should behave exactly
the same IMO.

**Comment by CeesZ** [comment]
I do not really understand the issue with jruby-jars.gem (probably because I never used it), but I would favor a solution where the *default* for jruby-complete is to ignore JRUBY_HOME. The solution as proposed by headius - to set a different main for the complete jar - seems a good way to achieve this.
Apropos of other actions depending on whether running from the "filesystem" or running from a "jar", it would be nice to have a more elegant way to determine this than by inspecting if `__FILE__` starts with `uri:classloader` or contains `.jar!` as I do at the moment. Maybe it exists and I missed it.
==Cees

**Comment by mkristian** [comment]
I am on it now. but the different main is tricky since the we have several distributions:
* tar.gz or zip binary distribution
* modular maven artifact
* complete/shaded maven artifact for easy command line execution and it is also an OSGi bundle
* jruby-jars gem which is kind of a mix for all the above three

the last three use the same jars from a java point of view. they are only differently packed. one jar or two jars or many jars.

and there is already a way to determine whether we run from classpath which contains ```META-INF/jruby.home``` or so that spawing a new jruby process works. here switching the main method would need to follow as well.

so what I am about to do is give preference to ```META-INF/jruby.home``` instead of using the environment JRUBY_HOME.

the other issue is not clear to me: the best would be to look at ```JRuby.runtime.instance_config.jruby_home```
to see if the stdlib is on classpath or from filesystem.

or if you code runs from within a jar you can look at ```Dir.pwd``` and check if this startsWith uri:classloader: which can be useful for example setting up a log file somewhere outside the application "directory"

probably a check on a given file would help as well. let's see.

**Comment by mkristian** [comment]
@headius that the ScriptingContainer behaves differently, i.e. gives first preference to JRUBY_HOME is something which we do in jruby-1.7.x but I would go for a more uniform solution and remove those code lines:  https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/embed/ScriptingContainer.java#L268
