### ISSUE TITLE
File.stat("someunavailable").mtime returns odd result

### ISSUE THREAD

**Issue by slackfan** [jruby/jruby#3448]
Hi, 

```
path = 'bananarama'
mtime = path && File.stat(path).mtime rescue nil
puts mtime
puts mtime.class
```
In JRuby-9.0.1.0 the result is what I would expect
```

NilClass
```

In JRuby-9.0.3.0 the result is a "random (?)" date in the future
```
2016-02-11 18:23:35 +0100
Time
```

This breaks e.g. Rubygems because the check for a newer gem on the gem server fails because an unavailable gem is recognized as newer than the gem on the gem server. (RemoteFetcher.cache_update_path)

**Comment by enebo** [comment]
I am going to assume you are on Windows right?  I can see this on Windows but not MacOS and I did in fact completely replace our old stat impl on Windows to use native Windows APIs instead of posix compat stat impl (this was to support long paths and UNC paths).  This should not be too hard to figure out and you saved me having to put out a 9.0.5 quickly after 4 :)

**Comment by slackfan** [comment]
Yes, this happens on Windows (7, 2008r2 server, 2012 server). Forgot to mention that :)

**Comment by enebo** [comment]
@slackfan Fixed locally so this will be in 9.0.4.

**Comment by slackfan** [comment]
Thank you!

**Comment by enebo** [comment]
This has been fixed a few days.  Not sure which commit but it is done.  Closing.
