### ISSUE TITLE
jruby-jars jruby-core should not include java/util/concurrent/ConcurrentHashMap.class

### ISSUE THREAD

**Issue by donv** [jruby/jruby#3555]
Starting with the inclusion of High Scale in JRuby 1.7.23, the jruby-jars gem includes java/util/concurrent/ConcurrentHashMap.class in the jruby-core jar.

This causes a security exception when an application tries to load the class outside the bootloader.

jruby-jars should not contain any packages in the `java` packages.

**Comment by mkristian** [comment]
the problem here is that it is not clear whether High Scale needs a patched ConcurrentHashMap.class to for its library - which I would assume or guessing from fact that they do pack into their jar. so first we need to find out whether this class is there on purpose or not. and maybe find out whether JRuby uses this feature which uses this ConcurrentHashMap

but in the long run I agree that jruby should not pack such classes, other places then ruboto will run into the problem sooner or later.

**Comment by kares** [comment]
wow - quite an intrusive surprise. for the record the high scale library was introduced only to use a concurrent `IntHashMap` alternative: [`NonBlockingHashMapLog`](https://github.com/boundary/high-scale-lib/blob/master/src/main/java/org/cliffc/high_scale_lib/NonBlockingHashMapLong.java) ... which does not depend on `ConcurrentHashMap` directly.

from the README it seems the patched classes are optional (and thus not really needed to be packaged by JRuby): https://github.com/boundary/high-scale-lib#original-readme
p.s. they also have a patched `java.util.Hashtable` class

**Comment by kares** [comment]
this is now also resolved with https://github.com/jruby/jruby/pull/3560 (will be merged over to master)

**Comment by donv** [comment]
Thanks!
