### ISSUE TITLE
jruby+truffle setup creates gems in 'ruby' directory but jruby looks in 'jruby' directory

### ISSUE THREAD

**Issue by tinco** [jruby/jruby#3569]
When running a truffle project I get the following exception:

```
  cannot load such file -- rack (LoadError)
```

Steps to reproduce:

  1. Add a Gemfile to project, enter 'rack' gem
  2. Run jruby+truffle setup, it should create a .jruby+truffle_bundle/ruby directory
  3. Add a ruby file that does `require 'rack'`
  4. Have a wrapper around jruby nightly like so: `echo 'exec /jruby-master/bin/jruby -X+T -r "./.jruby+truffle_bundle/bundler/setup.rb" "$@"' > /jruby-master/bin/ruby && chmod +x /jruby-master/bin/ruby`
  5. Use it to run the ruby file, see the error
  6. Rename the gem directory to `jruby`, error should disappear

I wrote these steps from heart, it might be that I missed something crucial. There's a docker environment that had the problem here: https://github.com/phusion/truffle-test/commit/6395e74de56a85d3164ac7a3d1ecd3d3a5a7dbe5

**Comment by chrisseaton** [comment]
I believe this happens because the tool is being run by a system Ruby rather than JRuby - but the tool shouldn't let that happen.

As @tinco says the workaround is to rename `.jruby+truffle_bundle/ruby` to `.jruby+truffle_bundle/jruby`, but there may be other symptoms of the system Ruby being used to run the tool, such as the wrong version of gems being installed.

Ping @pitr-ch

**Comment by pitr-ch** [comment]
Hello @tinco, 
let my try to help, couple of questions first:

(2.) how do you run `jruby+truffle setup` ? I couldn't find it in the Dockerfile.
(4.) why wrapper is used instead of `jruby+truffle run a_file.rb` ?

I've tried to reproduce your steps (without docker) but the wrapper worked for me in setup environment.

**Comment by pitr-ch** [comment]
Ah, @nirvdrum helped me to figure out why do you see ruby instead of jruby, fix is coming. For now switching your env. to jruby-master before running `jruby+truffle setup` should help.

**Comment by pitr-ch** [comment]
`jruby+truffle setup` is fixed to use correct bundler.

**Comment by tinco** [comment]
Good work and thanks :+1:

**Comment by chrisseaton** [comment]
Can this be closed?
