### ISSUE TITLE
JRuby doesn't support DATA and __END__

### ISSUE THREAD

**Issue by chrisseaton** [jruby/jruby#3579]
Looks like it was removed during development for 9.

**Comment by headius** [comment]
Oops. I guess test coverage is a little weak here.

**Comment by chrisseaton** [comment]
No you've just got the tests tagged!

**Comment by headius** [comment]
Looks like @enebo removed it in fbaf0389687e543bcbdd2d416d3f3e67a3a2b5b5 and never got back to reimplementing it.

**Comment by chrisseaton** [comment]
I added some stuff to your lexer to get it working in Truffle in 46bdc3cbcd10d031197c5f5dd39d879d29464908 so that may be useful for you.

**Comment by headius** [comment]
@chrisseaton Thanks, that probably works for most uses of DATA. It doesn't work for stdin though.

```
[] ~/projects/jruby $ cat blah.rb
puts DATA.read
__END__
hello

[] ~/projects/jruby $ ruby23 < blah.rb
hello

[] ~/projects/jruby $ jruby -X+T < blah.rb
WARNING: JRuby+Truffle is designed to be run with a JVM that has the Graal compiler. The compilation is disabled Without the Graal compiler and it runs much slower. See https://github.com/jruby/jruby/wiki/Truffle-FAQ#how-do-i-get-jrubytruffle
Truffle internal error: internal implementation error - RuntimeException java.io.IOException: Can't read file /Users/headius/projects/jruby/- org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:602)
internal implementation error - RuntimeException java.io.IOException: Can't read file /Users/headius/projects/jruby/- org.jruby.truffle.runtime.RubyContext.execute(RubyContext.java:602)
	at org.jruby.truffle.nodes.methods.ExceptionTranslatingNode.execute(ExceptionTranslatingNode.java:78)
	at org.jruby.truffle.nodes.instrument.RubyWrapperNode.execute(RubyWrapperNode.java:61)
	at org.jruby.truffle.nodes.RubyRootNode.execute(RubyRootNode.java:58)
```

**Comment by chrisseaton** [comment]
Gah didn't think of that.

**Comment by headius** [comment]
I should have a fix shortly that will enable both runtimes to do it *mostly* right.

**Comment by headius** [comment]
@chrisseaton @enebo I pushed my fix, which mostly involved getting access to the real FileChannel for the read file, putting it in a RubyFile, and grabbing that on the other side for DATA. This is now fully compatible with MRI's DATA since it's a real File with the actual descriptor/channel used to parse. Not that anyone is ever going to care.

@enebo The previous commit removes buffering from RubyInstanceConfig.getScriptSource. I could not think of a path in our code where the resulting stream wouldn't be buffered already or get buffered by RubyIO anyway.

@chrisseaton I also added `LexerSource.getChannel` for you to use in creating an appropriate DATA for Truffle.

**Comment by enebo** [comment]
@headius yeah script source is fine the others I might worry about

**Comment by headius** [comment]
The other source forms for require etc won't ever need DATA so it isn't as
big a deal. If they're double-buffering, though, that's overhead we don't
need.

**Comment by enebo** [comment]
@headius last time I checked they were not but that was also because all buffering had been removed so I added buffering back into the mix :)

**Comment by eregon** [comment]
We need a spec for this STDIN case :smile:
