### ISSUE TITLE
 Warning "io/console not supported; tty will not be manipulated" occurs again on 9.0.5.0 (2.2.3)

### ISSUE THREAD

**Issue by tukanos** [jruby/jruby#3704]
I'm trying to work with readline and I get this working 

```Ruby
jruby -v -rreadline -e "p Readline.readline"
```
output:
```
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) Client VM 25.66-b17 on 1.8.0_66-b17 +jit [Windows 7-x86]
io/console not supported; tty will not be manipulated
```

### Environment
The versions installed:
```
--> jruby -v
jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) Client VM 25.66-b17 on 1.8.0_66-b17 +jit [Windows 7-x86]
````
```
--> java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) Client VM (build 25.66-b17, mixed mode, sharing)
```
```
--> wmic OS get Caption,CSDVersion,OSArchitecture,Version
Caption                         CSDVersion      OSArchitecture  Version
Microsoft Windows 7 Enterprise  Service Pack 1  64-bit          6.1.7601
```

### Expected Behavior
To move the cursor right/left to edit output with keys right and left (gives OK output) only and not to show warning message.
```io/console not supported; tty will not be manipulated```

### Actual Behavior
Showing the message and unable to move the caret around.

**Comment by enebo** [comment]
io/console has never worked on windows although we should bite the bullet and port the necessary code to implement it.

@tukanos If you omit -v do you still see this warning printing out?  -v will enable $VERBOSE which is the guard which displays this warning or not (from Ruby command-line documentation):

```text
-v Displays version and enables verbose mode
```
In this case,  I think the behavior is correct in that you enabled verbose mode so we tell you that io/console is not getting loaded properly on windows (because we do not have an implementation of it -- we stub out some stuff).

I opened #3705 for adding the new feature.  If this warning is occurring without -v then please reopen this issue.  It is possible somehow readline library is enabling $VERBOSE errantly.

**Comment by tukanos** [comment]
Hello @enebo,

without the -v it does not display the warning, but also it does not work properly as you mentioned (with the code missing).  I had it there to see why it is not working as it should, there I saw it.

Thank you for opening a feature ticket.  It is rather useful if you want to have a simple program with only a few user answers, you can do it simple with io/console.
