### ISSUE TITLE
[Truffle] Intermittent Array error when running activemodel tests

### ISSUE THREAD

**Issue by bjfish** [jruby/jruby#3822]
### Expected Behavior
The tests complete.

### Actual Behavior
From the activemodel directory run:
` jruby+truffle run --require-pattern 'test/**/**/railtie_test.rb' -r exclude_tests -- -I test -e 'nil'`
Results in the following error occasionally:
```
Run options: --seed 22666

# Running:

ES

Finished in 2.837000s, 0.7050 runs/s, 0.0000 assertions/s.

  1) Error:
RailtieTest#test_secure_password_min_cost_is_true_in_the_test_environment:
RubyTruffleError: internal implementation error - ArrayIndexOutOfBoundsException 103 org.jruby.truffle.core.array.ObjectArrayMirror.get(ObjectArrayMirror.java:27)
    /Users/brandonfish/Documents/rails/railties/lib/rails/application.rb:321:in `include?'
    /Users/brandonfish/Documents/rails/railties/lib/rails/application.rb:321:in `add_lib_to_load_path!'
    /Users/brandonfish/Documents/rails/railties/lib/rails/application.rb:92:in `inherited'
    /Users/brandonfish/Documents/rails/activemodel/test/cases/railtie_test.rb:13:in `initialize'
    /Users/brandonfish/Documents/rails/activemodel/test/cases/railtie_test.rb:13:in `new'
    /Users/brandonfish/Documents/rails/activemodel/test/cases/railtie_test.rb:13:in `setup'
    /Users/brandonfish/Documents/rails/activemodel/.jruby+truffle_bundle/mocks/shims.rb:17:in `block (3 levels) in run'

2 runs, 0 assertions, 0 failures, 1 errors, 1 skips
```

**Comment by eregon** [comment]
Thanks for the report!
Running this with assertions enabled triggers an `assert` in Hash storage verification, investigating.

**Comment by eregon** [comment]
It looks like this uses minitest/parallel, which ends up spawning 2 threads by default.
This in turns seems to corrupt some Hash and likely some Array too.
I am not sure whether these races are supposed to happen or if there is some bug in our autoload or in the code assuming Array and Hash to be thread-safe.

**Comment by eregon** [comment]
Assigning to @pitr-ch since we will run threads in single-thread mode for now to make them more deterministic. I think we can close this issue once that is done, as the error should not appear anymore.

**Comment by thedarkone** [comment]
Just a quick note, Rails expects its boot process to be run single-threadedly, don't know what is happening here...

`$LOAD_PATH` obj must be made thread safe.

**Comment by pitr-ch** [comment]
fixed in 49e97eb24727727cafa948842f13f90b85d6dab5

@thedarkone yeah but this is not a rails boot process but lazy loading parts of a ActiveModel treating it 
as a library by parallel minitest. We are disabling this for now, because we are not thread-safe enough at the moment, which is know issue we work on.

Yes, it does. `$LOADED_FEATURES` as well.

**Comment by thedarkone** [comment]
> this is not a rails boot process but lazy loading parts of a ActiveModel treating it
as a library by parallel minitest. We are disabling this for now, because we are not thread-safe enough at the moment, which is know issue we work on.

Making sure we're on the same page: even with all the outstanding jruby-truffle thread-safety issues fixed, you still wouldn't be allowed to parallel load any part of Rails (including `ActiveModel`).

**Comment by pitr-ch** [comment]
After autoload is fixed then it should be ok, assuming that other ruby code is not also touching `$LOADED_FEATURES` and `$LOAD_PATH` (which is probably happening in the tests), since those are for now protected only from the internal side. Other things may broke though since Ruby code tends to rely on MRI's GIL.
