### ISSUE TITLE
Bad SSL certificate for jRuby for http://rails-assets.org

### ISSUE THREAD

**Issue by lephyrius** [jruby/jruby#3847]
### Environment

jruby 9.1.0.0 (2.3.0) 2016-05-02 a633c63 Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [darwin-x86_64]
Installed jRuby with RBenv and ruby-build using homebrew.
Bundler installed.
### Expected Behavior

Gemfile

```
source 'http://rails-assets.org' do
  gem 'rails-assets-select2'
end
```

Run bundle
Installs the rails assets ruby gem.
### Actual Behavior

This error message doesn't apply to jRuby:

```
Fetching source index from http://rails-assets.org/
Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for http://rails-assets.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

So this might only be a documentation issue? Or is it a issue with rails assets?

**Comment by mkristian** [comment]
see https://github.com/jruby/jruby/issues/3764

not sure where the problem is with you, but for me it looks again like the jdk version

**Comment by lephyrius** [comment]
@mkristian So the solution is to downgrade to JDK 7?

**Comment by kares** [comment]
there has been previous issues with CA certificates + rails-assets.org ... maybe you should look around

**Comment by mkristian** [comment]
@lephyrius recently I had a case where someone installed a openjdk8 debian package but the installation came with very old certificates and could not reach https://repo2.apache.org. in your case jdk7 could help, or latest jdk8, etc

**Comment by snowdall** [comment]
I'm seeing the exact same issue.  I've also tried a number of different things myself, but to no avail.  Has anyone come up with a solution on this one?

**Comment by papricek** [comment]
See https://github.com/tenex/rails-assets/issues/325

**Comment by preetpalS** [comment]
@papricek The workaround that they give for using `http://insecure.rails-assets.org` isn't that great since you are getting your assets over HTTP instead of HTTPS.

@snowdall I had a similar problem with Ruby on Windows (MRI). Try downloading the `cacert.pem` file from [here](https://curl.haxx.se/docs/caextract.html), putting that file's path in an environment variable named `SSL_CERT_FILE` (on windows command prompt: `SET SSL_CERT_FILE=C:\Rubies\cacert.pem`; Linux (bash): `SSL_CERT_FILE=/home/user/cacert.pem`), and then running bundler (with that `SSL_CERT_FILE` environment variable available (you should see the path if you run `echo %SSL_CERT_FILE%` on Windows or if you run `echo $SSL_CERT_FILE` in Linux)).

**Comment by preetpalS** [comment]
I believe that this issue is mainly caused by out of date CA certificates. This problem isn't exclusive to JRuby (see this [StackOverFlow issue](http://stackoverflow.com/questions/10246023/bundle-install-fails-with-ssl-certificate-verification-error)).

Anyone having this issue might also take a look at this workaround from [rvm.io](http://rvm.io/support/fixing-broken-ssl-certificates).

**Comment by headius** [comment]
The JVM tends to use its own certs for verification. There's various ways to update them...not knowing your platform, I'll let you search it up.

If it turns out we're still not working right, we can reopen this issue.
