### ISSUE TITLE
NameError: uninitialized constant Delegator

### ISSUE THREAD

**Issue by tobymurray-nanometrics** [jruby/jruby#4018]
Ran into this with Fuubar [here](https://github.com/thekompanee/fuubar/issues/92)

### Environment
jruby 9.1.2.0 (2.3.0) 2016-05-26 7357c8f Java HotSpot(TM) 64-Bit Server VM 25.92-b14 on 1.8.0_92-b14 +jit [mswin32-x86_64]

MSYS_NT-10.0 TobyM-PC1 2.5.0(0.295/5/3) 2016-03-31 18:47 x86_64 Msys

### Expected Behavior

```
λ C:\tools\ruby\23-x64\bin\irb.cmd
irb(main):001:0> ::Delegator
=> Delegator
```

### Actual Behavior

```
λ irb
irb(main):001:0> ::Delegator
NameError: uninitialized constant Delegator
        from org/jruby/RubyModule.java:3309:in `const_missing'
        from (irb):1:in `<eval>'
        from org/jruby/RubyKernel.java:983:in `eval'
        from org/jruby/RubyKernel.java:1290:in `loop'
        from org/jruby/RubyKernel.java:1103:in `catch'
        from org/jruby/RubyKernel.java:1103:in `catch'
        from C:/tools/jruby/9.1.2.0/bin/jirb:13:in `<top>'
```

**Comment by enebo** [comment]
@tobymurray-nanometrics I gave an explanation on the issue you linked but this is not a bug because delegator is part of stdlib delegate and you need to require it to use it.  Rubygems happens to use it on most platforms but apparently not all versions do (I could not see Delegator on windows MRI 2.2 for example).

**Comment by tobymurray-nanometrics** [comment]
Awesome, thanks so much for the quick response @enebo. Not-bugs are the best kind of bugs.
