### ISSUE TITLE
IO.select problems with SSL sockets on JRuby 1.7 on CentOS

### ISSUE THREAD

**Issue by ferrous26** [jruby/jruby#414]
Calling `IO.select` on `SSLSocket`'s is not behaving correctly. In some cases `IO.select` will never return (even though a timeout has been given) and in other cases it will erroneously report that the socket is ready for reading when it is not actually ready for reading.

I am experiencing this issue using OpenJDK 1.7 on CentOS. The example code below works fine on OS X 10.8.2. In both cases I am using JRuby 1.7.1 (master).

```ruby
require 'openssl'
require 'socket'

server_ctx             = OpenSSL::SSL::SSLContext.new
server_ctx.verify_mode = OpenSSL::SSL::VERIFY_NONE
server_ctx.cert        = OpenSSL::X509::Certificate.new File.read "config/ssl/cert_test.pem"
server_ctx.key         = OpenSSL::PKey::RSA.new File.read "config/ssl/keys_test.pem"

server        = TCPServer.new 0
ssl_server    = OpenSSL::SSL::SSLServer.new server, server_ctx
client        = TCPSocket.new 'localhost', server.addr[1]
ssl_client    = OpenSSL::SSL::SSLSocket.new client, OpenSSL::SSL::SSLContext.new

Thread.new do ssl_client.connect end
server_socket = ssl_server.accept

result = IO.select [ssl_client], nil, nil, 1
if result
  puts ssl_client.read_nonblock 10
else
  p 'OK'
end
```

Sorry the the example code can't be smaller, but setting up the SSL connection is a bit of a PITA.

**Comment by headius** [comment]
IO.select(ssl_socket) is not reliable on any implementation, due to the buffering that occurs internally for most SSL socket wrappers. Basically, IO.select does not know about those buffers. This is a known issue and we and ruby-core have not found a satisfactory solution.

See https://bugs.ruby-lang.org/issues/8875.

Now that may or may not explain this issue, but it would be very easy to get stuck in a loop if select kept claiming data was available (because the socket has data) but the SSLSocket does not consume it properly (because it's missing some handshake or other sequence).

I'm going to close this, since it's both very old and relates to a known issue with IO.select(ssl_socket) that neither we nor MRI plan to fix.

**Comment by ostinelli** [comment]
> I'm going to close this, since it's both very old and relates to a known issue with IO.select(ssl_socket) that neither we nor MRI plan to fix.

Indeed, however SSLSocket in the MRI has the method `pending` implemented, which can then allow to solve this issue by first reading the contents of the SSL buffer before `IO.select`.

However in JRuby this method is still [not implemented](https://github.com/jruby/jruby-openssl/blob/ed95b2c7bf85c3b4d3ff430cf7656cc4ac92535d/src/main/java/org/jruby/ext/openssl/SSLSocket.java#L1009). Because of this, I cannot add JRuby support for a library that uses SSL Sockets. Are there any plans to implement `pending`?

BTW thank you @headius for the great work :)

**Comment by headius** [comment]
@ostinelli I had no idea the `pending` method existed! Could you file a jruby-openssl issue about it, ideally including information from MRI (feature request, commit number, etc)? We can get it added in the next round!

**Comment by headius** [comment]
@kares @mkristian It should be reasonably easy to implement `pending` for SSLSocket, eh?

**Comment by kares** [comment]
@headius not sure about the SSL engine behaviour - if [`wrap`](http://docs.oracle.com/javase/7/docs/api/javax/net/ssl/SSLEngine.html#wrap%28java.nio.ByteBuffer[],%20java.nio.ByteBuffer%29) always returns all data than the non-empties buffer might be holding the pending bytes...
