### ISSUE TITLE
Method#owner returns wrong implementation module

### ISSUE THREAD

**Issue by etehtsea** [jruby/jruby#4262]
`Kernel#method` used in examples but it seems that both methods are relying on [implementationModule variable](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/RubyMethod.java#L259).

JRuby master (actually proper implementation called in `RubyIO`):

```
>> s0.method(:inspect)
=> #<Method: UNIXSocket(Kernel)#inspect>
```

MRI:
```
[17] pry(main)> s0.method(:inspect)
=> #<Method: UNIXSocket(IO)#inspect>
```

**Comment by headius** [comment]
You sure you're on master HEAD? I'm pretty sure I just fixed this for freerange/mocha#274 in #4250.

**Comment by etehtsea** [comment]
@headius seems to be another issue. I've got the same result on `9.1.5.0` and b0abc53c7045e934e799b8870befe58246fdf940.

**Comment by headius** [comment]
I don't think this is related to `Method#owner`. I think this is due to `IO` not defining its own `inspect` method. Instead, it just overrides the Java impl. As a result, the only `inspect` in any method table is the one from `Kernel`.

```
$ jruby -rsocket -e 'p UNIXSocket.instance_method(:inspect).owner'
Kernel
```


If I modify RubyIO to actually define `inspect` as a Ruby method, then it matches your result:

```
$ jruby -rsocket -e 'p UNIXSocket.instance_method(:inspect).owner'
IO
```

I'll go ahead with that fix.

**Comment by etehtsea** [comment]
@headius you are right,  I missed that. Thank you!
