### ISSUE TITLE
JRuby can not interpret keyword argument when placed after positional argument in block

### ISSUE THREAD

**Issue by axfcampos** [jruby/jruby#4319]
Hey there 👋 

### Environment

Running `jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.74-b02 on 1.8.0_74-b02 [darwin-x86_64]` on `Darwin axfcampos.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64`

### Expected Behavior

Example code:
```ruby
def hello
  yield(1, b: 2)
end

hello do |a, b:|
  puts a, b
end
```

Output in MRI 2.3.1:
```
1
2
```

### Actual Behavior

Output in JRuby:
```
ArgumentError: missing keyword: b
```

**Comment by flash-gordon** [comment]
I came across the same issue, though I can't reproduce it with your example. For me it fails with 
```sh
ruby -e "proc { |_, a:| }.call(1, a: 1)"
```
Because of it I got a couple of pending examples in [one of my gems](https://github.com/dry-rb/dry-monads).

**Comment by enebo** [comment]
I spent some time on this and will try and get something on this shortly but this is not broken once the code is JITed.  Both interp and full interp fail but that makes sense since they both use the same code.  I am confused though.  I was fairly certain the JIT called through the same method as well.  So something in JIT changes this behavior...

**Comment by flash-gordon** [comment]
@enebo I checked my case on JRuby's master and it works fine, thanks!
