### ISSUE TITLE
Yard does not work in JRuby =>9.1.3.0

### ISSUE THREAD

**Issue by petr666** [jruby/jruby#4363]
Since JRuby 9.1.3.0 yard stopped working. More precisely it is probably not able to align comments with actual elements. Same project, same version of yard, "documented" dropped from 100% to 28.57%. Also it started to print warning "Unknown tag @host", however there is no such tag in comments and this warning is generated based on commented instance variable within method implementation (therefore I guess there is some problem with comment alignment).
Everything is working as expected in JRuby 9.1.2.0 and older (including 1.7.x)

**Comment by headius** [comment]
Can you show us an example of the problem? I'm not a yard user.

**Comment by olleolleolle** [comment]
`bundle exec rspec spec/templates/helpers/text_helper_spec.rb`

<details>

**Comment by enebo** [comment]
Woo even after narrowing this down with a bisect it took a while to get it:

```ruby
nodes = [1]
nodes.each.with_index do |node, index|
  puts node
  nodes.insert index + 1, *[2, 3, 4] if node == 1
end
```

The if is just so this does not run forever.  JRuby will only print 1 and MRI will print 1,2,3,4.

**Comment by headius** [comment]
Closing the loop...

The problem was that the newish packed arrays had a couple block-receiving methods that did not handle modification during iteration. So if it was a one or two element array and you did `ary = [1]; ary.each {|x| ary << 1}` it would only run the block once, rather than as many times as there were elements inserted.

NOTE: Matz himself has said that modification during iteration is an undefined behavior, so technically we were not doing anything wrong here. However, the fix was simple so we went ahead with it. I do not recommend relying on this behavior.

**Comment by olleolleolle** [comment]
@petr666 This change is a fix for the test that I noted, but it will not make _all_ of YARD's behavior work in JRuby. 

I have set up a Travis build with YARD's test suite [on my own Github fork](https://github.com/olleolleolle/yard/blob/master/.travis.yml). It shows lots of test failures on `jruby-head`. https://travis-ci.org/olleolleolle/yard/jobs/182802272

I recommend running `yard` using MRI until it can run its own test suite with JRuby.
