### ISSUE TITLE
9k regression on indirect java_class.annotation(java_class) method

### ISSUE THREAD

**Issue by byteit101** [jruby/jruby#4432]
### Environment
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.8.0_111-b14 +jit [linux-amd64]
and
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [linux-x86_64]

```java
import java.lang.annotation.*;
@Target({ ElementType.FIELD, ElementType.METHOD, ElementType.TYPE })
@Retention(RetentionPolicy.RUNTIME)
public @interface MyAnnotation {
    String value() default "";
}
```

```java
import java.util.*;
@MyAnnotation
class MyClass {
	public static Class[] getAll(){
	   return new Class[] { MyClass.class };
    }
}
```

### Expected Behavior
```rb
jruby-1.7.19 :002 > java_import 'MyClass'
 => [Java::Default::MyClass] 
jruby-1.7.19 :003 > java_import 'MyAnnotation'
 => [Java::Default::MyAnnotation] 
jruby-1.7.19 :004 > MyClass.all[0].annotation(MyAnnotation.java_class)
 => #<Java::Default::$Proxy24:0x212bf671> 
jruby-1.7.19 :005 > MyClass.all[0].annotation(MyAnnotation.java_class).value
 => "" 
```

### Actual Behavior
```rb
jruby-9.1.6.0 :003 > java_import 'MyClass'
 => [Java::Default::MyClass] 
jruby-9.1.6.0 :004 > java_import 'MyAnnotation'
 => [Java::Default::MyAnnotation]
jruby-9.1.6.0 :005 > MyClass.all[0].annotation(MyAnnotation.java_class)
ArgumentError: wrong number of arguments (1 for 0)
	from (irb):9:in `<eval>'
	from org/jruby/RubyKernel.java:998:in `eval'
	from org/jruby/RubyKernel.java:1299:in `loop'
	from org/jruby/RubyKernel.java:1118:in `catch'
	from org/jruby/RubyKernel.java:1118:in `catch'

jruby-9.1.6.0 :008 > MyClass.all[0].annotation
 => false 
```

All 1.7 that i've used (since 1.7.3) works as the first, while all the 9.x series that I've tried do the latter. This looks like some funky proxy screw up, as directly referencing MyClass works on 1.7 and 9k:

```rb
jruby-9.1.6.0 :005 > MyClass.java_class.annotation(MyAnnotation.java_class)
 => #<Java::Default::$Proxy25:0x6a03bcb1> 
jruby-9.1.6.0 :006 > MyClass.all[0]
 => class MyClass 
jruby-9.1.6.0 :007 > MyClass.java_class
 => class MyClass 
jruby-9.1.6.0 :008 > MyClass.all[0].annotation(MyAnnotation.java_class)
ArgumentError: wrong number of arguments (1 for 0)

```

**Comment by kares** [comment]
believe this is a collision on setting up ruby aliases for Java methods.

the first case works since it returns a `Java::JavaClass` wrapper, 
the seconds returns a 'true' `java.lang.Class` proxy - has `getAnnotation(arg)` which gets alias-ed as `annotation` but there's also `isAnnotation` alias-ed as `annotation?` and `annotation` (if not yet defined). 
we have a deterministic Java method order-ing in 9K while in 1.7 its whatever java.lang.Class#getMethods returns.

**Comment by kares** [comment]
this lead me to realize there's still non-determinism with get/is aliases although this does not clasify for that.

the previous 1.7 behaviour was unfortunate since it would lead to confusing cases such as #3262 
that is why in 9K things got changed and only 'real' get-ers have aliases without the get/is prefix, in this particular case:
* getAnnotation(param) is not considered a getter since it receives a parameter
* isAnnotation() is considered a getter and since there's no getAnnotation() `annotation` alias is set-up

this might sound weird but its better than 1.7 (believe alias-ing might just stay order dependent there).

you should refactor your code to use `get_annotation(param)`

interestingly the order of methods locally seems pretty deterministic (hard to get a failing test) but on travis-ci I was able to reproduce the issue with getFoo/isFoo Ruby aliasing (shall put that in another report).
