### ISSUE TITLE
Documentation out of date?

### ISSUE THREAD

**Issue by allquixotic** [jruby/jruby#4493]
The Wiki page at https://github.com/jruby/jruby/wiki/JRubyAndJavaCodeExamples seems to be out of date.

Using latest stable JRuby (9.1.7.0) these examples contain *many* compile-time errors, and nearly every single method call into the org.jruby APIs is deprecated.

I tried correcting this myself, but my attempts were frustrated by the fact that the documentation does not seem to be written for JRuby 9k at *all* (it mentions 1.7), and by the fact that most methods are not documented at all.

It is best practice in the software industry that if you're going to deprecate something, you should say what to use instead. And it's not always clear what to use instead when methods are deprecated in org.jruby.Ruby or org.jruby.javasupport.Java, because these classes contain an ungodly number of methods with very similar names, most of which are undocumented.

**Comment by headius** [comment]
These examples do indeed appear to be out of date. I'm not sure I've ever looked at this page myself.

It appears this page was imported from our old wiki on kenai.com and it has had only minor updates since.

We probably should just remove the Java examples here and point at the more up-to-date documentation here:

https://github.com/jruby/jruby/wiki/RedBridge
https://github.com/jruby/jruby/wiki/RedBridgeExamples

And perhaps to the JSR-223 embedding page here: https://github.com/jruby/jruby/wiki/Embedding-with-JSR-223

FWIW the above approaches all generally try to hide org.jruby.Ruby, which we have never really blessed as a public API. The RedBridge API provides a reasonable direct API that we maintain, and the standard JSR-223 APIs provide a less direct but standard Java way to initialize and execute JRuby.

**Comment by headius** [comment]
I have made the described changes to the page. Let us know if you have trouble driving JRuby with RedBridge.
