### ISSUE TITLE
Fiddle::Function returns FFI::Pointer instead of Fiddle::Pointer

### ISSUE THREAD

**Issue by jellymann** [jruby/jruby#4510]
### Environment

* JRuby version: 9.1.8.0-SNAPSHOT
* Operating System: Mac OS X 10.11.6

### Expected Behavior

code:
```
require 'fiddle'
libc = Fiddle.dlopen('/usr/lib/libc.dylib')
f = Fiddle::Function.new(libc['strcpy'], [Fiddle::TYPE_VOIDP, Fiddle::TYPE_VOIDP], Fiddle::TYPE_VOIDP)
buff = "000"
str = f.call(buff, "123")
```

MRI:
```
str.to_s
#=> "123"
```

### Actual Behavior

JRuby:
```
str.to_s
#=> "#<FFI::Pointer address=0x7000003137a0>"
```

**Comment by headius** [comment]
Ok, I merged your PR, and thanks again for that.

This issue is a bit trickier, since it's trying to let FFI classes masquerade as Fiddle classes. The `call` for the Fiddle::Function gets bound directly to the `call` of the FFI::Function, so unsurprisingly it returns an FFI::Pointer. I think we need to rework this to wrap the FFI::Function rather than binding it directly to `call`, so we can produce an appropriate Fiddle type on the way out.

**Comment by headius** [comment]
No time to work on this for 9.1.8.0 but with your help we'd like to fix it for 9.1.9.0 or 9.2 (whichever comes first).

**Comment by jellymann** [comment]
@headius I've made a PR to fix this into your Fiddle Fixes branch here: headius/jruby#2

**Comment by headius** [comment]
The PR in question was merged, so hopefully this was fixed around the same time.

**Comment by jellymann** [comment]
@headius I believe it was merged into your fork of JRuby, not sure if the changes made it into this repo?

**Comment by jellymann** [comment]
Okay it looks like this commit fixed the issue: https://github.com/jruby/jruby/commit/366f9f1a7efd57e2e624030dd448231b0a6f6650
Not mine but it does the same thing 👍
