### ISSUE TITLE
interface implementation example does not work with JRuby 9000 series

### ISSUE THREAD

**Issue by botchniaque** [jruby/jruby#4573]
### Environment

Provide at least:
* JRuby version 9.1.8.0
* Operating system and platform: *Ubuntu 16.10* oracle JVM 1.8.0_181

Other relevant info you may wish to add:
* Installed or activated gems: None
* Application/framework version None
* Environment variables: None

### Expected Behavior
Running [JRuby embed example on how to cast JRuby code to java interface](https://github.com/jruby/jruby/wiki/RedBridgeExamples#interface-implementation) should work as described. 

### Actual Behavior

Running the example with JRuby 9.1.8.0 throws an exception

```
org.jruby.exceptions.RaiseException: (TypeError) can't define singleton
	at org.jruby.RubyModule.extend_object(org/jruby/RubyModule.java:2578)
``` 

Using JRuby 1.7.26 works fine. 

Runnable example can be found here https://github.com/botchniaque/embed-jruby-test

**Comment by enebo** [comment]
fwiw, I think that FluidForce part of the example is a bad example and one we do not want anyone  to use.  So someone should consider a better mechanism for showing the .getInstance part of our embedding API.

This is not technically a bug because in Ruby 2.x 'def' will now return a Symbol of the method being added.  Prior to Ruby 2, def would return nil.  So in this example in JRuby 1.7.x we get back 'null' which is passed to getInstance which then uses self so the example works.  In JRuby 9.1.x we get back :getFluidForce and then try to use the symbol to get an instance of the FluidForce interface (which of course a symbol does not implement that interface).    So embedding API is working as expected but new Ruby semantics broke the example.

II will update the documentation to better illustrate what is happening (add self at bottom of fluid_force.rb) but I find this example to be a bit confusing with .getInstance.

**Comment by botchniaque** [comment]
@enebo thanks for clarifying. I will stick to `container.callMethod` in this case and implement the interface myself.
