### ISSUE TITLE
Definite bug in core/src/main/java/org/jruby/util/io/SelectExecutor.java

### ISSUE THREAD

**Issue by nglorioso** [jruby/jruby#4867]
Coming from #4860

https://github.com/jruby/jruby/blob/078193288fbcad0fb5b90dbf21e5b05614ceade4/core/src/main/java/org/jruby/util/io/SelectExecutor.java#L212

Here and just below, `errorKeyList`, a `List<ErrorKey>`, is queried for containment of `fptr.fd()` (a `ChannelFD`). Perhaps, instead, `pendingReadFDs` or one of the other `List<ChannelFD>` fields in the file should be checked instead?

**Comment by headius** [comment]
The logic here is a bit misleading. The code here is largely in place just for matching up with the MRI implementation of select.

In JRuby, no IO are ever put into the `errorKeyList` which means none of them will ever trigger the logic you pointed out. This is because there's no logic in the JDK's Selector to select streams for errors. We just go through the motions, as mentioned [earlier in the file](https://github.com/jruby/jruby/blob/078193288fbcad0fb5b90dbf21e5b05614ceade4/core/src/main/java/org/jruby/util/io/SelectExecutor.java#L135), but since there's no way to register for errors...we don't.

The logic could probably be boiled down to just the side effect calls (such as verifying opennes of IO passed in the error argument), but it would only be to clean up the code (which is a valid reason).

**Comment by headius** [comment]
To be honest, this whole thing should be rewritten for efficiency, but the complexities of handling both selectable and non-selectable, native and JDK-provided streams has kept me from tackling it.

**Comment by headius** [comment]
Closing this for now. I tried a simple optimization that fast-paths single read selects and it seemed to have little effect on overall performance. The dummy error logic will remain in place for now, since it's rarely used and reflects how MRI's select is implemented.
