### ISSUE TITLE
jruby uses absolute pathnames in batch files generated by rubygems

### ISSUE THREAD

**Issue by oxygene** [jruby/jruby#4890]
I'm planning to use jekyll running on jruby on Windows and Linux build machines without internet access. Therefore, I "bootstrap" jruby and install the jekyll gem on a machine with internet access first, and then make a tarball that can be then deployed to the build-machines.

This works fine in principle, however the `bin/jekyll.bat` files uses an absolute path to jruby like this:

> @"C:\Users\username\Documents\path-to-jruby-9.1.15.0\bin\jruby.exe" "%~dpn0" %*

This will of course fail on the build machines when installed to a different path.
It works fine when I change the line to

> @"%~dp0jruby.exe" "%~dpn0" %*

The code that generates the line seems to be here: https://github.com/jruby/jruby/blob/9ba7c10b861f1c3c7b3de02c1542471d0a899ed9/lib/ruby/stdlib/rubygems/installer.rb#L745-L755

Could that be changed to use `%~dp0` instead of the hardcoded absolute path?

### Environment
jruby 9.1.15.0 (2.3.3) 2017-12-07 929fde8 Java HotSpot(TM) Client VM 25.151-b12 on 1.8.0_151-b12 +jit [mswin32-x86]

**Comment by headius** [comment]
That seems like a reasonable change. However we ship an unmodified version of RubyGems, so this isn't a change we'd make in JRuby since it would get wiped out with the first RubyGems update.

I think you should open this with rubygems/rubygems and link to this issue. Once there's released versions of RubyGems with an appropriate fix, we can update and resolve this one.

I'll help make your case if there's any pushback.

**Comment by headius** [comment]
No recent progress on this and it's really out of our domain. We'll happily pull in the new RubyGems when available. Please open a new issue for that once the original issue is fixed in RubyGems.
