### ISSUE TITLE
RegexpError "invalid pattern in look-behind" for certain Regexps since 9.1.16.0

### ISSUE THREAD

**Issue by naag** [jruby/jruby#5086]
We've been running a regular expression matching certain file extensions since JRuby 9.1.12.0, but after upgrading to 9.1.16.0, it breaks. 9.1.15.0 is the last release where it works.

We've stripped down the regular expression a lot and it still fails with `RegexpError: invalid pattern in look-behind: /^.*(?<!css)$/i` for the most basic case. Example:

```
$ irb
jruby-9.1.16.0 :001 > "foo.html" =~ /^.*(?<!css)$/i
RegexpError: invalid pattern in look-behind: /^.*(?<!css)$/i
	from org/jruby/RubyRegexp.java:1097:in `=~'
	from org/jruby/RubyString.java:1613:in `=~'
	from (irb):1:in `<eval>'
	from org/jruby/RubyKernel.java:995:in `eval'
	from org/jruby/RubyKernel.java:1316:in `loop'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from org/jruby/RubyKernel.java:1138:in `catch'
	from /usr/local/rvm/rubies/jruby-9.1.16.0/bin/irb:13:in `<main>'
```

Another expression that fails is `/^.*(?<!tiff)$/i`. Both work if we change the last letter from `s` to something else or `t` to something else. They also work in case sensitive mode. MRI 2.4.3 works fine with all of these variants.

Is there any other input you need?

### Environment

```
$ jruby -v
jruby 9.1.16.0 (2.3.3) 2018-02-21 8f3f95a Java HotSpot(TM) 64-Bit Server VM 25.161-b12 on 1.8.0_161-b12 +jit [linux-x86_64]

$ env | grep '\(JRUBY\|JAVA\)' | sort
JAVA_HOME=/usr/lib/jvm/java-8-oracle
JRUBY_OPTS=--server -J-Xmn128m -J-Xms1536m -J-Xmx1536m

$ uname -a
Linux 6ee27f8ee9cd 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

**Comment by lopex** [comment]
MRI has special case for us-ascii regexps and strings with 7-bit coderange where it uses regexp encoding for the match, whereas we're creating new regexp with actual string encoding. So ultimately this could be a big performance penalty for two reasons:
- we're polluting regexp cache and/or creating new regexps every time in case of dregexps
- we're matching using utf-8 encoding unnecessarily which can be tens of times slower and even more if the match is case insensitive.

Fixed in 36b44dfcca

**Comment by naag** [comment]
Thanks a lot @lopex, going to test it tomorrow with our code base!

**Comment by lopex** [comment]
I think the root cause also deserves some explanation. Character series like ss and ff are special because in Unicode for example ss is https://en.wikipedia.org/wiki/%C3%9F.
In case insensitive mode ss is unfolded to [S, ſ, ß, ẞ] alternatives (having different length in bytes). Another factor that triggered this issue is look-behind limitations - it doesnt allow variable length match as in (?<!.*) for example. For some reason Onigmo treats (?<!css) as a variable (not to be confused with different) length alternative in case insensitive mode even though all alternatives are fixed in size, why then is (?<ss) ok ? this is a mystery right now.

So right now there's some caviats regarding MRI "us-ascii regexps by default":    

- "foo" =~ /(?<!css)/i # works
- "foą" =~ /(?<!css)/i # blows
- "foo" =~ /(?<!css)/iu # blows

If either string or regexp happens to end up with unicode encoding, look-behind will blow.

**Comment by lopex** [comment]
Also, great majority of regexps will end up being up to multiple times faster by default, with cases like e ("_" * 1000) + "" =~ /[a-z]+/i being 35 times faster.

**Comment by naag** [comment]
Thank you for the detailed explanation! Unfortunately I was unable to build JRuby locally, but I can try again when 9.1.17.0 is released :-)

**Comment by enebo** [comment]
@naag I just corrected an issue with our nightlies link: http://jruby.org/nightly  (click stable).

**Comment by lopex** [comment]
Onigmo issue: https://github.com/k-takata/Onigmo/issues/92
