### ISSUE TITLE
Status for MRI-related security issues?

### ISSUE THREAD

**Issue by thbar** [jruby/jruby#5126]
I'm maintaining Ruby installations for a client on a regular basis (including both MRI & JRuby on various servers).

MRI got multiple releases to cover multiple CVEs:
* https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-5-1-released/
* https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-4-4-released/
* https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-3-7-released/
* https://www.ruby-lang.org/en/news/2018/03/28/ruby-2-2-10-released/

Before that, MRI got other fixes recently:
* https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-3-6-released/
* https://www.ruby-lang.org/en/news/2017/09/14/ruby-2-3-5-released/

I wondered what the situation is for JRuby with regard to the related CVEs.

The [JRuby security page](http://jruby.org/security) doesn't mention recent CVEs, and the [news page](http://jruby.org/news) hasn't had one for a while if I'm not mistaken.

Does this means that JRuby is unaffected (e.g. if it uses different, underlying JVM components rather than pure Ruby code), or that the evaluation hasn't necessarily been conducted so situation is unknown?

I don't know if opening an issue is the way to go for this, but I thought it is worth clarifying, so this could start a discussion!

Thanks for your work on JRuby.

**Comment by thbar** [comment]
PS: I do realise that like anything else, asserting & following all this takes time, and that resources are limited - I don't feel entitled to anything, just wondering what is the current status! Thanks.

**Comment by headius** [comment]
We have been monitoring the various CVEs but have not been able to review them all. In general, most CVEs for CRuby don't apply to JRuby because they involve unsafe memory accesses that are not possible on the JVM. In native code, usually only DoS-type issues will also apply to JRuby, since much of our code uses the same algorithms as CRuby.

Any CVE that affects the Ruby-based standard library merits investigation. We ship a largely-unmodified copy of CRuby's standard library. That has not been updated in the 9.1 line since around Ruby 2.3.2 timeframe, so any CVEs affecting it after that time should get incorporated. I believe we have held off updating the standard library mostly because we expected JRuby 9.2 to be finished sooner, with support for current 2.4 or 2.5 and current stdlib to go with them.

**Comment by headius** [comment]
I'm going to bump this to 9.2 so we have time to review these CVEs. We could use some help figuring out which ones might affect JRuby...they hide the related commits rather well.
