### ISSUE TITLE
Using certain Java JAR files work in program execution, but not in 'jirb'

### ISSUE THREAD

**Issue by sharkos** [jruby/jruby#5300]
### Environment
Tested on both Linux & MacOS

jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [darwin-x86_64]
Darwin CTusa-MacBook.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 OpenJDK 64-Bit Server VM 9.0.1+11-Debian-1 on  9.0.1+11-Debian-1 +jit [linux-x86_64]
Linux ctusa-lenovo 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux

*** LOCAL GEMS ***

bcrypt (3.1.12 java)
cmath (default: 1.0.0)
csv (default: 1.0.0)
fileutils (default: 1.1.0)
ipaddr (default: 1.2.0)
jar-dependencies (default: 0.3.12)
jruby-openssl (default: 0.10.0 java)
jruby-readline (default: 1.2.2 java)
json (default: 2.1.0 java, 1.8.6 java)
psych (default: 3.0.2 java)
rake (12.3.1)
rake-ant (default: 1.0.4)
rdoc (default: 6.0.1, 3.12.2)
rdoc-rake (1.0.1)
scanf (default: 1.0.0)
sequel (5.11.0)
webrick (default: 1.4.2)

$JRUBY_HOME = /opt/telegard/contrib/jruby

### Expected Behavior
See this example:
```
# Script to demonstrate a bug with JRuby 9.2.0.0
# Chris Tusa <ctusa_AT_redhat.com>
#
# notes: This code works when running the script via 'jruby'.
#        Does not work when pasted into 'jirb'
#
require 'java'

# Imports JLine Jar for ANSI Console Functions
#
# https://sourceforge.net/projects/jline/files/jline/0.9.94/jline-0.9.94.zip/download
#
# crusty old jar file from 2008, but it works
#
require './jline-0.9.94.jar'
module JLine
  include_package "jline"
end

# clear the screen using JLine ConsoleReader method
def ansiclear
    JLine::ConsoleReader.new.clearScreen
end

ansiclear
```

### Actual Behavior

Script works perfectly as expected when running it from the command line:
jruby ./test.rb

Spits out errors in 'irb'
irb(main):026:0> ansiclear
Traceback (most recent call last):
       16: from org.jruby.RubyKernel.rbCatch19Common(org/jruby/RubyKernel.java:1187)
       15: from org.jruby.RubyContinuation.enter(org/jruby/RubyContinuation.java:108)
       14: from org.jruby.RubyKernel$INVOKER$s$0$0$loop.call(org/jruby/RubyKernel$INVOKER$s$0$0$loop.gen)
       13: from org.jruby.RubyKernel.loop(org/jruby/RubyKernel.java:1418)
       12: from org.jruby.RubyKernel$INVOKER$s$0$3$eval19.call(org/jruby/RubyKernel$INVOKER$s$0$3$eval19.gen)
       11: from org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1037)
       10: from org.jruby.RubyKernel.evalCommon(org/jruby/RubyKernel.java:1070)
        9: from RUBY.<eval>((irb):26)
        8: from RUBY.ansiclear((irb):23)
        7: from org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
        6: from org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:997)
        5: from org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:263)
        4: from java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:423)
        3: from jline.ConsoleReader.<init>(jline/ConsoleReader.java:174)
        2: from jline.ConsoleReader.<init>(jline/ConsoleReader.java:186)
        1: from jline.ConsoleReader.<init>(jline/ConsoleReader.java:191)
Java::JavaLang::NoSuchMethodError (jline.Terminal.getTerminal()Ljline/Terminal;)

**Comment by headius** [comment]
Closing the loop...

We chatted on IRC. The problem here is almost certainly because `readline` loads a newer version of the jline library into the JRuby classloader, which then conflicts with (really, prevents loading from) the older version that @sharkos intended to use.

Workarounds for this problem:

* Pass --no-readline to IRB. The console capabilities of IRB will be someone crippled but it won't conflict with the older jline.
* Use readline-ffi as detailed in https://github.com/jruby/jruby/issues/3721#issuecomment-245610391

However, after some discussion it might be the case that @sharkos can use the `io/console` library from Ruby instead, since the requirement is mostly just to read single characters from the console. @sharkos is looking into this option now.

In any case, this is another issue with our existing jline-based `readline` library that will go away once we adopt readline-ffi, so I'm closing this.
