### ISSUE TITLE
`autoload` should delegate to `require`

### ISSUE THREAD

**Issue by tenderlove** [jruby/jruby#5403]
Team Rails wants to use [this gem](https://github.com/Shopify/autoload_reloader), but it depends on an implementation detail that changed in Ruby 2.3 [here](https://github.com/ruby/ruby/commit/cd465d552c3a00341f4cb7f1d7a793d0ebcb6cde).  The commit includes a test, but I think JRuby adds a skip for that test.  Please make the test pass!

Thanks!!

/cc @enebo

**Comment by headius** [comment]
I did attempt to fix this once, but got many weird errors that scared me off for a while. Now I guess we have a consumer, so it's a good time to get it right.

**Comment by fxn** [comment]
Hey! I am going to release https://github.com/fxn/autoloader soon.

The plan is to integrate with Rails 6 (either in the gem or in Rails, to be decided). But I'd like the gem to be used by any Ruby gem. That is my plan, and Autoloader is designed in a way that each gem can have its own separate autoloader, with its own configuration, separate inflector, and logger.

It relies on the ability to decorate `Kernel#require` to trace autoloads, and more importantly to intercept autoloads on directories, since that's the way the gem implements lazy descend into subdirectories.

**Comment by fxn** [comment]
❤️

**Comment by headius** [comment]
Fixed by #5764.
