### ISSUE TITLE
Hash corrupts some data when working along linear/open threshold

### ISSUE THREAD

**Issue by headius** [jruby/jruby#5406]
This is a call for @ChrisBr to help us audit some of the RubyHash work in 9.2.1 😁 

In 6b2fa457a05d2cfa8e250b3c00dec7e227ec5e73, @enebo added a null check for a delete in open addressing mode. However it seems like the null check should not be necessary.

In order to get to this line in the code, there would have to be a bin that's not EMPTY and not DELETED. In such a case, there should be a non-null entry at that point in the entries array. However it comes up as null, as guarded by Tom's fix.

My theory for this involves transitioning back and forth across the size threshold for linear search versus open addressing. For example, the following scenario:

* Hash `myhash` is filled up to the threshold for linear search.
* An additional entry `A` transitions it to open addressing. The new entry gets a proper  value in `bins` but the other entries remain `EMPTY`. This seems wrong.
* A different entry `B` gets removed. Its bin gets marked as DELETED. We are now back in linear search size.
* The `A` entry gets deleted. Now that we are in linear addressing, the key and value are nulled but the bin is still set to a value that's not EMPTY or DELETED.
* Other adds transition us back to open addressing again.
* Now we are in open addressing with an entry in `bins` that is not EMPTY or DELETED but points at null values.

I'm not clear from reviewing the code how the transition across this boundary should be updating bins. The above scenario at least seems like a gap.

**Comment by headius** [comment]
@enebo points out that simply removing an entry shouldn't transition us back to linear addressing, since it is a factor of the size of the `entries` array. But perhaps a rehash could cause us to shrink back down? And then we have a bunch of weird bin entries?

**Comment by headius** [comment]
Hmm, perhaps it's not possible to transition back from open addressing to linear?

There are still questions for me about how the transition from linear to open works, since at that point we have a `bins` filled with `EMPTY`.

**Comment by enebo** [comment]
I think at least a single case of this seems to be that sprockets memory cache (a hash) is getting/deleting concurrently across puma threads.  I see no synchronization.

**Comment by ChrisBr** [comment]
> @enebo points out that simply removing an entry shouldn't transition us back to linear addressing, since it is a factor of the size of the entries array. But perhaps a rehash could cause us to shrink back down? And then we have a bunch of weird bin entries?

This is correct, your initial theory should not happen.

IIRC (did not check the code) we do not compact the hash when removing elements. However, rehash does compact the hash.

@enebo @headius sorry for causing so much trouble :crying_cat_face: Do you have a script / test to reproduce this behavior?

**Comment by ChrisBr** [comment]
> I think at least a single case of this seems to be that sprockets memory cache (a hash) is getting/deleting concurrently across puma threads. I see no synchronization.

You mean deleting should be synchronized? It wasn't before either ... The only issue I could think of is now that we have two arrays to clean and it could happen that one array is already cleaned but the other not?

**Comment by enebo** [comment]
@ChrisBr no before and after we never guaranteed concurrent access while modifying the hash.  So sprockets should be sync'ing or using concurrenthashmap impl (e.g. should not be our responsibility -- we have never actually guaranteed thread safety)....however, this code (sprockets)  has not changed in 3-5 years so having it work with the null guard for 9.2.1.0 will help us out since Rails will not crash.  Not our responsibility is a fine logical argument, but having rails crash in a point release from ancient code will not go over well.  With that said I think the null check I added may be good enough...

I do have a question regarding delete though.  If bin points to something which is mysteriously null keywise (another concurrent delete where we see entries key null but bin no yet marked deleted) we are not really in danger of not finding the eventual key are we?  The algo appears to just go to first bin which would hash that way and then use index(bin) for secondary bin(s) to keep walking the logical bucket.  So long as that null did not represent the original key we were looking for it should still find the proper key?  Otherwise if another thread had also deleted the same key we would return null and more or less still be correct.

**Comment by enebo** [comment]
@ChrisBr I should add that I think @headius and I may have different thoughts here.  The one case I narrowed down more with sprockets looks like a concurrency issue.  Another issue we could not nail down it was not clear what was causing it (but that same null fix in deleteOpenInternal fixed it as well).

  I think @headius has been trying to figure out if we have a non-concurrent issue since that is something we guarantee.    If you could review the code again and try and think about any possible holes in the implementation then it will help us out.

**Comment by ChrisBr** [comment]
> I do have a question regarding delete though. If bin points to something which is mysteriously null keywise (another concurrent delete where we see entries key null but bin no yet marked deleted) we are not really in danger of not finding the eventual key are we? The algo appears to just go to first bin which would hash that way and then use index(bin) for secondary bin(s) to keep walking the logical bucket. So long as that null did not represent the original key we were looking for it should still find the proper key? Otherwise if another thread had also deleted the same key we would return null and more or less still be correct.

This should be correct. We use ``internalKeyExists``, in this case otherKey should be null and otherHash should be 0. So it should return false and NullPointer should also not a problem as we call ``key.eql`` and key should always exist (or NilObject).

```java
    private boolean internalKeyExist(IRubyObject key, int hash, IRubyObject otherKey, int otherHash) {
        return (hash == otherHash && (key == otherKey || (!isComparedByIdentity() && key.eql(otherKey))));
    }
```

But yes, I will have a second look at the implementation. @headius let me know if you narrow down the issue in a non concurrent case.

Do I get it correct that with the additional null checks you added @enebo the code works again as expected and this issue is just for auditing again?

**Comment by enebo** [comment]
@ChrisBr yep. I cannot get anything to fail under any release testing I do before a release with that null value check added.  So auditing is just to be sure.  Earlier in the week I added another null check to the any? implementations (but that largely just matched the other accesses of entries).  So one more look around will help us feel a bit more confident.

**Comment by headius** [comment]
I no longer believe there's any inherent issue with the transition across this boundary. There may indeed be issues with concurrency, see #5412 and related issues.
