### ISSUE TITLE
Fatal is not a module

### ISSUE THREAD

**Issue by ioquatix** [jruby/jruby#5648]
In MRI, `Fatal` is not defined.

But in JRuby, it is.

Code that expects to be able to create it's own `module Fatal` or otherwise will fail.

In MRI, `fatal` is not exposed to user. But you can access it by using ObjectSpace to find it.

I suggest that initially, you remove `class Fatal` from global namespace. Then, perhaps with agreement from MRI, we can make something like `FatalError`, perhaps defined under `RubyVM` or something else.

**Comment by ioquatix** [comment]
```
koyoko% irb
jruby-9.2.5.0 :001 > module Fatal; end;
Traceback (most recent call last):
        6: from /home/samuel/.rvm/rubies/jruby-9.2.5.0/bin/irb:13:in `<main>'
        5: from org/jruby/RubyKernel.java:1181:in `catch'
        4: from org/jruby/RubyKernel.java:1181:in `catch'
        3: from org/jruby/RubyKernel.java:1415:in `loop'
        2: from org/jruby/RubyKernel.java:1046:in `eval'
        1: from (irb):1:in `evaluate'
TypeError (Fatal is not a module)
jruby-9.2.5.0 :002 > 
koyoko% rvm use 2.6.1
Using /home/samuel/.rvm/gems/ruby-2.6.1
koyoko% irb          
2.6.1 :001 > module Fatal; end
 => nil 
2.6.1 :002 > 
```

**Comment by enebo** [comment]
@ioquatix we can talk about whether or not we can hide this name since it is somewhat likely to hit user code which may also end up using global namespace for a common word.  We usually try to avoid this practice but generally mostly out of fear MRI will introduce it.  

It looks like 9.2.x has this since feb 2018.  We maybe can deprecate and 9.3.x can not use global namespace.  We will talk about the complexities of making the change.  Once people use code it is more difficult to just remove it.

**Comment by headius** [comment]
It doesn't look like any Ruby code tries to access this exception, which makes sense since it's not accessible in MRI. They appear to be defining it as a lower-case "fatal" so it doesn't show up in constant lists. I don't like the practice, but this isn't the only class or module they define this way. However simply changing our code to use the lower-case name causes Object.constants to have an entry for `:fatal`. I'm not sure why this doesn't appear in MRI yet.

**Comment by headius** [comment]
Short term workaround would be to `undef_const` the offending name before you try to open your own class called `Fatal`.

**Comment by ioquatix** [comment]
I only mentioned this because I think it's a consistency issue. I personally agree, there probably should be a constant.

In MRI:

```ruby
Fatal = ObjectSpace.each_object(Class).find{|klass| klass < Exception && klass.inspect == 'fatal'}
```

finds the right constant.

**Comment by headius** [comment]
I have done a PR to remove the constant from Object. I'm not sure how well our internals would handle the lower-case class name, so I have not made that change.

Are you expecting the ObjectSpace mechanism to work as well, or just hoping to get rid of the conflicting constant? Given that this class is intended to be a non-recoverable error, I'm inclined to not worry about "Fatal" versus "fatal".

**Comment by ioquatix** [comment]
I'm honestly not that concerned, the `ObjectSpace` lookup is a hack :p
