### ISSUE TITLE
Stack overflow with deeply nested GuardWithTestHandle.invokeExact_thunkArchetype_X calls

### ISSUE THREAD

**Issue by JamesKingdon** [jruby/jruby#5673]
### Environment

I apologise for not having all the requested information.  I'll try and acquire more details over time.

I'm investigating this problem from the perspective of possible JVM/JIT errors, but wanted to check if it sounded like a potential problem at the jruby level (I didn't find anything searching the github issues).

Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

9.1.2

No jruby specific options or env vars that I can see.

* Operating system and platform (e.g. `uname -a`)

RHEL 7.6 running under vmware on 64 bit x86
JVM is IBM Java 8 SR4 

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

### Expected Behavior

No stack overflow

### Actual Behavior

The JVM reports a stack overflow where the stack includes roughly 16000 nested calls to GuardWithTestHandle.invokeExact_thunkArchetype_X. The stack does leave those calls before hitting overflow, leading me to suspect that the maximum stack depth has been slowly growing over time. This would be consistent with the customer reporting 1 to 2 month intervals between failures, with the JVM not normally restarted between failures.

Is there anywhere in the code where a conditional handle is wrapped in another, that might build up a deep chain of nested handles?

The stack looks like:

```
4XESTACKTRACE                at java/util/logging/Logger.getLogger(Logger.java:513(Compiled Code))
4XESTACKTRACE                at com/headius/invokebinder/Binder.<init>(Binder.java:70(Compiled Code))
4XESTACKTRACE                at com/headius/invokebinder/Binder.from(Binder.java:161(Compiled Code))
4XESTACKTRACE                at org/jruby/ir/targets/ConstantLookupSite.searchConst(ConstantLookupSite.java:82(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/VirtualHandle.invokeExact_thunkArchetype_L(VirtualHandle.java:122(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/BruteArgumentMoverHandle.invokeExact_thunkArchetype_X(ArgumentMoverHandle.java:389(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:54(Compiled Code))

... roughly 16000 copies of GuardWithTestHandle.invokeExact_thunkArchetype_X

4XESTACKTRACE                at java/lang/invoke/GuardWithTestHandle.invokeExact_thunkArchetype_X(GuardWithTestHandle.java:54(Compiled Code))
4XESTACKTRACE                at java/lang/invoke/MutableCallSiteDynamicInvokerHandle.invokeExact_thunkArchetype_X(MutableCallSiteDynamicInvokerHandle.java:47(Compiled Code))
```

**Comment by headius** [comment]
Woo, neato! I bet I know what's going on here.

Some of our method or constant lookup sites in invokedynamic logic will stack up recent "hits" to a small limit in order to cache more than just the single most recent method or constant. If that logic is broken somewhere and there's a continuous stream of new targets being encountered, it would eventually create a chain of caches that blow the stack.

Looking at your stack, it appears this would be due to constant lookup never finally settling down, so there's always new constant values (or possibly there are many constant values continuing to be defined at runtime). This would not be a typical case; we optimize constants with this chain because in general they are expected to settle down shortly after an application boots.

However there does come to mind a few places where this logic might be flawed:

* If a module contains a method that accesses a constant *not* defined in the module, it may grow a chain of values as long as the number of hierarchies into which the module is included. I don't believe the current constant caching logic detects this situation.
* Reloading code in a development environment. However you say this is happening in production, and development envs typically don't run for very long at a stretch.
* Simply bad code. If there's logic abusing constants within `eval` or forcibly removing and replacing constant values, this chain could grow indefinitely.

I do believe there's a fix required here.

Given that this is a 1-2 month cycle, can I assume this is not a critical issue per se? We have a release going out tomorrow, and another in roughly a month. We would target the latter.

FWIW your environment is intriguing! We don't know many folks deploying on IBM's JDK, but we're very excited to experiment with it now that it is open source.

**Comment by headius** [comment]
I actually looked at the code in question, and it appears I fixed something very similar in 9.1.3.0. I suspect this fix will work for you too!

https://github.com/jruby/jruby/issues/4003

As you'd expect, we would always recommend using the most recent JRuby version (9.2.7 out this week), but the shortest path to a fix would be to update the JRuby you're using from 9.1.2 to 9.1.3.

I'm going to close this bug as a duplicate of #4003. Please let us know if you still see issues after updating to JRuby 9.1.3 or higher.

I'd also love to hear more about your application and environment! You can find us on Gitter (jruby/jruby), Matrix, IRC (freenode #jruby), or Twitter (@headius, @jruby).

**Comment by JamesKingdon** [comment]
Many thanks Charles. I'll pass the information back up to the product team and see if I can get them to test with a newer version. I don't have details, but I believe several IBM products make use of jruby, so you have quite an installed user-base running with OpenJ9/IBM SDK :) The product in this case is Watson Explorer. The whole team that works on OpenJ9 is really excited to have it open source, and we're enjoying the chance to working more closely and openly with everyone.

**Comment by headius** [comment]
@JamesKingdon Hey James! Have not checked in with you in a long time and I was wondering about the state of JRuby use at IBM. We're making a big push for the next version of JRuby and I'm hoping to contact as many users as possible to ensure we're considering their needs. Perhaps you can put me in contact with someone at IBM that's familiar with JRuby-based projects and how we might be able to help?
