### ISSUE TITLE
Verifying that info on FAQ page of wiki is accurate WRT jruby master and JDK9-11

### ISSUE THREAD

**Issue by guyboertje** [jruby/jruby#5742]
Logstash engineer here and owner of the jdbc* plugins. We have had some problems with loading drivers recently (fixed now but not released).

Please confirm that the info on the [FAQ wiki page](https://github.com/jruby/jruby/wiki/FAQs) is correct with respect to versions 9.2.6.0+ and JDK 9,10,11.

I'm especially interested in the sections "How can I load a ResourceBundle from the Rails config directory ?" and "Why do I get ClassNotFoundException when I call java.lang.Class.forName from Ruby?"

Not the Rails bit obviously, but the appending to the $CLASSPATH - does JRuby have a utility to prefix the file or folder correctly and check that it exists?

**Comment by headius** [comment]
@guyboertje Perhaps your issues would be helped by a change to the launch script we made in 20e4278d3e4b9b3c0e646d7b14ab9516c9808a14? We were mistakenly putting everything in $CLASSPATH into the module path which appears to have some odd impacts on loading.

**Comment by headius** [comment]
@guyboertje I think I need more info here and this isn't really attached to a release, so I'm marking it as such. Have you been able to verify your issues on a more recent JRuby?

**Comment by guyboertje** [comment]
@headius 
Thanks for circling back.
I mean that I am curious about whether the wiki page mentioned is still accurate W.R.T Java 9 modules and how class loading has changed.
We have had to implement a hack to get the DriverManager to "see" drivers jars that are not put on the CLASSPATH before JRuby loads. IIRC the DriverManager uses a different classloader than the rest of JRuby.

**Comment by headius** [comment]
Aha, so one thing I can think of relating to `$CLASSPATH` is that there's probably some integration with the Java module system missing. Did you have to start doing your hack just recently? As of a few releases ago we started loading JRuby itself into the *module path* of the JDK so we could start opening up some packages we need access to; this may interfere with libraries loaded at runtime.

I know we also do some classloader-juggling for JDBC drivers because of the stupid way they get loaded. All of this is related, to be sure.

If you can provide more information about your hack, that might help me understand.

**Comment by guyboertje** [comment]
Sure.
There is this wrapper we needed to create...
```ruby
module LogStash module PluginMixins module Jdbc
  class WrappedDriver
    java_implements java.sql.Driver

    def initialize(drv)
      @driver = drv
    end

    java_signature 'boolean acceptsURL(String u) throws SQLException'
    def accepts_url(u)
      @driver.accepts_url(u)
    end

    java_signature 'Connection connect(String u, Properties p)'
    def connect(url, props)
      @driver.connect(url, props)
    end

    java_signature 'int getMajorVersion()'
    def get_major_version()
      @driver.get_major_version()
    end

    java_signature 'int getMinorVersion()'
    def get_minor_version()
      @driver.get_minor_version()
    end

    java_signature 'DriverPropertyInfo[] getPropertyInfo(String u, Properties p)'
    def get_property_info(url, props)
      @driver.get_property_info(url, props)
    end

    java_signature 'boolean jdbcCompliant()'
    def jdbc_compliant()
      @driver.jdbc_compliant
    end

    java_signature 'Logger getParentLogger() throws SQLFeatureNotSupportedException'
    def get_parent_logger()
      @driver.get_parent_logger
    end
  end
end end end
```
And it is used like this...
```ruby
      driver_jars.each_with_index do |driver, idx|
        urls[idx] = java.io.File.new(driver).toURI().toURL()
      end
      ucl = java.net.URLClassLoader.new_instance(urls)
      begin
        klass = java.lang.Class.forName(@jdbc_driver_class.to_java(:string), true, ucl);
      rescue Java::JavaLang::ClassNotFoundException => e
        raise LogStash::Error, "Unable to find driver class via URLClassLoader in given driver jars: #{@jdbc_driver_class}"
      end
      begin
        driver = klass.getConstructor().newInstance();
        java.sql.DriverManager.register_driver(WrappedDriver.new(driver.to_java(java.sql.Driver)).to_java(java.sql.Driver))
      rescue Java::JavaSql::SQLException => e
        raise LogStash::Error, "Unable to register driver with java.sql.DriverManager using WrappedDriver: #{@jdbc_driver_class}"
      end
```
Whereas, in JDK8 we could just do (IIRC `add_url` is no longer public, and the DriverManager is using a class loader we can't get to)...
```ruby
      drivers_jars.each do |driver|
        begin
          class_loader = java.lang.ClassLoader.getSystemClassLoader().to_java(java.net.URLClassLoader)
          class_loader.add_url(java.io.File.new(driver).toURI().toURL())
        rescue => e
          @logger.error("Failed to load #{driver}", :exception => e)
        end
      end
```
[Here is a Gist of my experiments](https://gist.github.com/guyboertje/354c617e910e32610fedb8936e3e3af1).

**Comment by headius** [comment]
Aha, that clarifies things for me!

So yes, on Java 8, the system classloader is (usually) a URLClassLoader:

```
irb(main):001:0> p java.lang.ClassLoader.system_class_loader
#<Java::SunMisc::Launcher::AppClassLoader:0x378fd1ac>
=> #<Java::SunMisc::Launcher::AppClassLoader:0x378fd1ac>
irb(main):002:0> p java.lang.ClassLoader.system_class_loader.kind_of? java.net.URLClassLoader
true
=> true
```

Whereas on Java 9+, it's not:

```
irb(main):001:0> p cl = java.lang.ClassLoader.system_class_loader
#<Java::JdkInternalLoader::ClassLoaders::AppClassLoader:0x7c30a502>
=> #<Java::JdkInternalLoader::ClassLoaders::AppClassLoader:0x7c30a502>
irb(main):002:0> cl.kind_of? java.net.URLClassLoader
=> false
irb(main):003:0> cl.class.ancestors
=> [Java::JdkInternalLoader::ClassLoaders::AppClassLoader, Java::JdkInternalLoader::BuiltinClassLoader, Java::JavaSecurity::SecureClassLoader, Java::JavaLang::ClassLoader, Java::JavaLang::Object, ConcreteJavaProxy, JavaProxy, JavaProxyMethods, Object, Kernel, BasicObject]
```

This is part of Java modules locking down the system classloader to ensure new libraries aren't loaded outside of module-loading mechanisms.

The `$CLASSPATH` variable basically points at a JRuby-local URLClassLoader, which allows us to dynamically add jars (as you probably know). However the libraries added here are only visibile to other libraries also added this way.

So, I believe you need a way to add jars at the system level because of the, ahem, challenges of getting JDBC to see drivers and because you're generating code (by implementing Driver in Ruby). Am I getting it?

Regarding the subject of this issue... yes, I believe the is accurate, in that our `$CLASSPATH` will still work the same on Java 9; it is a URLClassLoader and you can load libraries and see them from Ruby. But the system classloader is out of our control (without other hacks) so in Java 9+ you'll need to use some other mechanism to load those libraries dynamically at runtime, or to put them on the system classpath or modulepath before JRuby starts up.

Maybe you could stop by Gitter, IRC, or Matrix to chat about this further?

**Comment by headius** [comment]
One thing that might be relevant is some code we use to work around the DriverManager nonsense in JRuby: https://github.com/jruby/jruby/blob/4e8bb2666a7257f0f5986800f96bb88efdd6acbd/core/src/main/java/org/jruby/util/JDBCDriverUnloader.java

**Comment by guyboertje** [comment]
> So, I believe you need a way to add jars at the system level because of the, ahem, challenges of getting JDBC to see drivers and because you're generating code (by implementing Driver in Ruby). Am I getting it?

Yes, you are. We only generate code because, while we are migrating our JDBC plugins to Java and then can have the Driver implementation in Java, it was easier to use Ruby for now. As the plugins used in a Logstash config are evaluated after the JVM starts we (in the LS code) don't know which database technologies the JDBC endpoints use until the config is parsed and the user gives us a path to their driver jar(s).

> Regarding the subject of this issue... yes, I believe the is accurate
Great. I'll close this issue.
