### ISSUE TITLE
Difference in behavior using eval(or a file) vs IRB.

### ISSUE THREAD

**Issue by Adithya-copart** [jruby/jruby#5844]
### Environment

Provide at least:
* JRuby version: 9.2.8.0
* `Darwin MB-ADPENTELA.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64`

### Expected Behavior

* There should be no difference when in IRB vs executing the same code in a file.

### Actual Behavior

I ran into [this](https://github.com/puma/puma/pull/1868#issuecomment-520887732) while trying to come up with a test case using puma with JRuby.

```
# io_popen.rb


require 'open3'

server = IO.popen("rackup ./jruby-sigint.ru")

# Wait for bootup
true while server.gets !~ /Ctrl-C/

t1 = Time.now
Process.kill(:INT, server.pid)
Process.wait(server.pid)
p "Time elapsed: #{Time.now - t1}"
```

```
### jruby-sigint.ru


# frozen_string_literal: true

java_import java.util.concurrent.ThreadPoolExecutor
java_import java.lang.Runnable

# From https://github.com/ruby-concurrency/concurrent-ruby/blob/d11b29c37b81320ca7126cc9cd85f4f3d17a78a3/lib/concurrent/executor/java_thread_pool_executor.rb#L111-L117
pool = java.util.concurrent.ThreadPoolExecutor.new(
    2,
    2,
    60,
    java.util.concurrent.TimeUnit::SECONDS,
    java.util.concurrent.LinkedBlockingQueue.new,
    java.util.concurrent.ThreadPoolExecutor::AbortPolicy.new
  )

# From concurrent-ruby: https://github.com/ruby-concurrency/concurrent-ruby/blob/d11b29c37b81320ca7126cc9cd85f4f3d17a78a3/lib/concurrent/executor/java_executor_service.rb#L77-L87
class Job
  include Runnable
  def initialize(args, block)
    @args = args
    @block = block
  end

  def run
    @block.call(*@args)
  end
end

2.times do
  pool.submit Job.new(nil, proc { sleep })
end

at_exit do
  # Request threadpool shutdown.
  pool.shutdown
  # Add two seconds wait to let the threads finish and then kill the threads.
  deadline = Time.now + 2
  while true
    break if pool.get_active_count.zero?
    if Time.now > deadline
      pool.shutdownNow
      break
    end
  end
end

run lambda { |env| [200, {"Content-Type" => "text/plain"}, ["Hello World"]] }
```

### Output
```
# Executing the file
$ jruby -S io_popen.rb 
"Time elapsed: 2.037766"

# IRB session
$ irb
jruby-9.2.8.0 :001 > eval(File.read('./io_popen.rb'))
"Time elapsed: 2.039838"
 => "Time elapsed: 2.039838" 
jruby-9.2.8.0 :002 > require 'open3'
 => false 
jruby-9.2.8.0 :003 > 
jruby-9.2.8.0 :004 > server = IO.popen("rackup ./jruby-sigint.ru")
 => #<IO:fd 17> 
jruby-9.2.8.0 :005 > 
jruby-9.2.8.0 :006 > # Wait for bootup
 => nil 
jruby-9.2.8.0 :007 > true while server.gets !~ /Ctrl-C/
 => nil 
jruby-9.2.8.0 :008 > 
jruby-9.2.8.0 :009 > t1 = Time.now
 => 2019-08-22 10:50:18 -0500 
jruby-9.2.8.0 :010 > Process.kill(:INT, server.pid)
 => 1 
jruby-9.2.8.0 :011 > Process.wait(server.pid)
 => 11266
jruby-9.2.8.0 :012 > p "Time elapsed: #{Time.now - t1}"
"Time elapsed: 18.488332"
 => "Time elapsed: 18.488332" 
jruby-9.2.8.0 :013 > 
```
`I had do kill -9 the process manually`

**Comment by headius** [comment]
IRB is actually quite a different environment from normal code execution (via loads and evals and such) so I can't say I quite agree that it should always behave the same.

However, I also don't see why this should behave any differently.

I just tried it locally and can reproduce. In the IRB case, the subprocess appears to have exited its "main" method, but there are two non-daemon threads still active for the thread pool. So my working theory is that running it this way from IRB is somehow interfering with the eventual interrupt of the subprocess. Still investigating.

**Comment by headius** [comment]
Ok, so I can explain the main thread being finished because the script does not keep it alive; it starts up the thread pool, installs an at_exit hook, and then main exits leaving the thread pool to run and hook to shut down. So that's not unexpected.

I think the problem here is due to IRB mucking about with signal traps. In order to allow users to interrupt the execution of long-running code *without* interrupting IRB itself, it does this around the evaluation of that code:

https://github.com/jruby/jruby/blob/66570f070229525f1c1b37fc4eb6f51c0fc96dec/lib/ruby/stdlib/irb/xmp.rb#L80-L97

If somehow that trap to ignore interrupts is propagating to the child process, it could cause this problem.

Unfortunately I would have expected that evaluating or loading the file from within IRB behaved the same way, and they do not.

**Comment by Adithya-copart** [comment]
@headius Sorry for not being clear in the bug report. I somehow missed to mention that the behavior within IRB mimics executing `rackup ./jruby-sigint.ru` from the shell.

I expected this script to wait at `Process.wait(server.pid)` while trying to come up with a failing test when puma runs `graceful_stop` in the signal handler thread instead of the main thread.

```
$ rackup jruby-sigint.ru 
Puma starting in single mode...
* Version 4.1.0 (jruby 9.2.8.0 - ruby 2.5.3), codename: Fourth and One
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
Use Ctrl-C to stop
^C- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2019-08-22 17:58:01 -0500 ===
- Goodbye!
Killed: 9

```
https://github.com/puma/puma/pull/1868.

**Comment by Adithya-copart** [comment]
This is what I found while investigating why the main thread exits before shutting down the thread pool.

https://github.com/jruby/jruby/issues/5437#issuecomment-515509832

**Comment by headius** [comment]
@Adithya-copart Ok thanks for clarifying that.

I believe I'm closing on in the problem and I don't think it's a JRuby issue. Adding some logging to your `at_exit` shutdown I can see that it loops several times waiting for the 2 seconds to elapse...but it terminates prematurely, after just a few milliseconds. It never enters the logic to `shutdownNow` which leaves the thread pool running, and since those threads aren't daemon threads they keep the JVM from exiting. You can't interrupt the process again because Puma has uninstalled its trap, so we're stuck.

I'm investigating why the at_exit block is not running to completion.

**Comment by headius** [comment]
And there we have it:

```
org.jruby.exceptions.SystemExit: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:750)
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:713)
	at RUBY.setup_signals(/Users/headius/projects/jruby/lib/ruby/gems/shared/gems/puma-4.1.0-java/lib/puma/launcher.rb:412)
```

Puma is forcing the system to shut down after it is satisfied that its own worker threads have completed. Unfortunately this happens while your `at_exit` is still waiting to shut down the thread pool. The logic for this is part of Puma's INT handler here:

https://github.com/puma/puma/blob/master/lib/puma/launcher.rb#L408-L416

Adding insult to injury, this logic is only used on JRuby. If I comment out this block, everything appears to terminate properly, so it may no longer be necessary to shut down JRuby in this way.

```
$ rackup jruby-sigint.ru ; echo OK
Puma starting in single mode...
* Version 4.1.0 (jruby 9.2.9.0-SNAPSHOT - ruby 2.5.3), codename: Fourth and One
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:9292
Use Ctrl-C to stop
^C"a"
[]
- Gracefully stopping, waiting for requests to finish
=== puma shutdown: 2019-08-23 02:20:27 -0500 ===
- Goodbye!
OK
```

This does not appear to be a bug in JRuby, so that's good!

**Comment by headius** [comment]
@Adithya-copart I'm going to close this, since there doesn't appear to be anything we're doing wrong in JRuby. I would suggest a couple possible ways forward for you:

* Your at_exit could be reworked to immediately shut down the threads, but that obviously might interrupt work you don't want to interrupt.
* The same logic could possibly be registered with Puma, somehow, so it's part of the same shutdown sequence.
* You could reach out to the Puma folks to figure out why this JRuby-specific logic exists and perhaps get it removed.

I don't think it would make much difference if we handled the signal on the main thread, since the hard call of `exit` would just happen before we even run the `at_exit` blocks, prematurely terminating our normal shutdown procedure. The `exit` is the real cause.

**Comment by headius** [comment]
I see now you did come to a similar conclusion in puma/puma#1868 and I understand now what you meant by coming up with a test case...

So the original issue you reported here was that sometimes it works, like when run in an eval in IRB, yes? I'm going to reopen and try to get a good answer for that.

**Comment by headius** [comment]
I've tried running your example in several ways...

* Running `io-popen.rb`at the command line always seems to work.
* Running it via an eval or load inside IRB also seems to work.
* Running `rackup` directly leads to the stuck process.
* Pasting the contents of `io-popen.rb` into IRB also gets stuck.
* Pasting the contents of `io-popen.rb` into IRB as a single line does not get stuck.

I also notice that the cases that get stuck output the logging I put in place to show why the `at_exit` block terminates prematurely. The other cases do not.

**Comment by headius** [comment]
Ok, it definitely looks like this is a problem with how IRB traps INT between lines.

I managed to isolate the failing case in IRB. If you run the `popen` call on its own, things go wrong. That tells me there's something up with how IRB re-enables its INT-ignoring trap.

If I change this line to false, all forms of your example code work properly in IRB:

https://github.com/jruby/jruby/blob/ef5e53afb383f0497c0d6052a3e29d9ebf7224b2/lib/ruby/stdlib/irb/init.rb#L50

I believe this is a problem with how we handle the signal mask or signal default for the child process.

IO.popen (and spawn and others) eventually bottom out in `posix_spawn`. This issue is partially described in https://github.com/jruby/jruby/issues/2796.

We do not currently manipulate the signal default or mask for the child process, due to some issues getting this to work via our native interface. I think the result of this is that in some scenarios, this mask is causing the Puma process to not register a signal handler, skipping the problematic `exit` logic

**Comment by headius** [comment]
Ok so I can make your `io-popen.rb` script fail by simply having it ignore SIGINT before it spawns the server. That shows we're propagating at least some signal defaults to the child. According to `posix_spawn` docs, any signals ignored in the parent will be ignored in the child.

https://pubs.opengroup.org/onlinepubs/009695399/functions/posix_spawn.html

Of course in this case IRB is not using SIG_IGN to ignore the signal...it is installing its own handler. I'm trying to simulate this in the script so we have a better isolated case.

**Comment by headius** [comment]
To clarify something else...I did not link to the right code for the irb INT logic above. I believe this is the only trap that irb installs in typical execution:

https://github.com/jruby/jruby/blob/7b964fdd9c07e2af3d94d300bd676cde847d621a/lib/ruby/stdlib/irb.rb#L422-L424

**Comment by Adithya-copart** [comment]
@headius Thanks for looking into this as always and trying to come up with a detailed explanation of what is going on. I would like to point out that this is not an issue that is really impacting us. It is just a behavior that I found to be peculiar and couldn't figure out myself.

This is the other approach that worked for me in IRB and inside a script to write that failing test where the puma process is not shutdown completely. I'm not sure how the signals are propagated to the child in this case.

```
pid = spawn("rackup jruby-sigint.ru")

# Wait until bootup
sleep 6
t1 = Time.now
Process.kill(:INT, pid)
Process.wait(pid)
p "Time elapsed: #{Time.now - t1}"
```

I'm assuming that the only take-away from https://github.com/jruby/jruby/issues/5844#issuecomment-524209080 is the [use of exit in puma](https://github.com/puma/puma/blob/9fb12283dbadf6e2bad04d5e67fe3fc9c29eede5/lib/puma/launcher.rb#L412) is not really necessary as the puma process can shutdown properly without that in JRuby.

The code-change I'm trying to make in puma is to make sure the puma server is shutdown as part of an `at_exit` block that will be registered as part of the `SIGINT` signal handler which ensures the threads created in `jruby-sigint.ru` will have a chance to be shutdown.

**Comment by nateberkopec** [comment]
@headius, I am in awe of your debugging abilities

![](https://media.giphy.com/media/MUeQeEQaDCjE4/giphy.gif)

**Comment by Adithya-copart** [comment]
@headius I made progress and I found out that the execution of [this](https://github.com/puma/puma/blob/1046165a9c8766ce5c1db8db4d894e200f4c981c/lib/puma/single.rb#L111-L120) code in Puma is altering the behavior of the process. If we send a `SIGINT` before this is executed then the process dies otherwise it does not.

Just adding a `sleep 0.1` in the script after the while loop or in the `Signal.trap(:INT)` block in [puma](https://github.com/puma/puma/blob/1046165a9c8766ce5c1db8db4d894e200f4c981c/lib/puma/launcher.rb#L409) ensures that IRB and eval behave the same way. I will close this issue as this behavior cannot be attributed to JRuby as of now.

@nateberkopec I don't know if I can call this an issue in puma because the issue I reported in https://github.com/puma/puma/issues/1675 can be fixed by https://github.com/puma/puma/pull/1868. I don't know if this is something puma should be concerned about.

In my case, IRB is probably adding enough delay as it needs to execute its own logic which ensures the code in puma is executed in a  [background thread ](https://github.com/puma/puma/blob/1046165a9c8766ce5c1db8db4d894e200f4c981c/lib/puma/server.rb#L282-L359). Using `eval`, this delay is non-existent so the process will shutdown.

**Comment by Adithya-copart** [comment]
Looks like this issue is a result of a race-condition with `server.run.join` combined with the `exit` call in the trap. There is no issue in JRuby.

If the exit is called after the thread is joined then the process hangs, otherwise it exits fine.
This will be resolved in puma once the change mentioned in https://github.com/jruby/jruby/issues/5844#issuecomment-524203618 is implemented.

I'm not sure if the puma tests should wait until the server thread is joined onto main as `true while server.gets !~ /Ctrl-C/` is a pattern observed in the test suite which is responsible in a way for this false alarm.

Thank you both for your time and patience. Here is a sample reproduction to validate this hypothesis.
```
t = Thread.new do
  Signal.trap(:INT) do
   p 'Receved INT'
   Thread.kill t
   exit
  end
  sleep
end

p 'Main will be busy for 5 sec'
t1 = Time.now
while true
  a = !a
  break if (Time.now - t1) > 5
end

p 'Joining now'
t.join
p 'Joined'

#####################
        Output
#####################
# With exit
$ ruby test_int.rb 
"Main will be busy for a 5 sec"
^C"Receved INT"

# Without exit
$ ruby test_int.rb 
"Main will be busy for 5 sec"
^C"Receved INT"
"Joining now"
"Joined"
```

**Comment by headius** [comment]
Good investigation @Adithya-copart! Thanks for the follow-up work. I'm glad we have an explanation.
