### ISSUE TITLE
Memory leak issue on JRuby 9.1.17

### ISSUE THREAD

**Issue by mrnonz** [jruby/jruby#5890]
### Environment

Provide at least:
* JRuby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 +jit [linux-x86_64]
* Linux 635fd1dddd58 4.18.0-1024-azure #25~18.04.1-Ubuntu SMP Fri Jun 28 23:27:46 UTC 2019 x86_64 Linux

Other relevant info you may wish to add:
* rails 4.2.11

### Expected Behavior

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.

### Actual Behavior

* Memory leak and I need to restart service to normal state.

<img width="651" alt="Screen Shot 2562-09-25 at 17 22 27" src="https://user-images.githubusercontent.com/9113726/65592867-9861c980-dfb9-11e9-8bf7-da6176749512.png">

**Comment by enebo** [comment]
One IRMethod instance is created per Ruby method defined within a JRuby runtime.  Are you sure you do not have 25k methods defined?  An empty rails6 app makes 18k methods.   If you keep seeing this count increasing over time and you are not constantly creating new methods there could be a leak.  Some amount of increase in Rails can appear to be from lazy loading of uncommon parts of an app.

Also JRuby 9.2.8.0 reduced a lot of memory associated with org.jruby.ir.* as well as some other runtime related objects.

**Comment by mrnonz** [comment]
<img width="659" alt="Screen Shot 2562-09-27 at 16 14 34" src="https://user-images.githubusercontent.com/9113726/65757739-f28d9680-e141-11e9-87e3-702794c0484f.png">

I found another memory leak suspect, but am not sure about this leak.

I will try to upgrade my application to running on JRuby 9.2.8.0

**Comment by enebo** [comment]
Ok 7000 classes sounds like a lot and if they define methods then you would see lots of IRMethod instances since they would never garbage collect because the class still exists.  Hopefully 9.2.8.0 does not exhibit this.

**Comment by headius** [comment]
How large is it getting before you have to restart it? Could be it's not a leak, but just excessive memory use.

**Comment by ckpeter** [comment]
Just as a tip: Give your JVM plenty of extra heap / metaspace.

In my experience, JRuby 9.x series is significantly heavier in memory usage than 1.7. I too had a Rails 4 app that, when first upgraded to 9.0/9.1/9.2, would constantly OOM, leading me to suspect leak. However, when I gave it 2-3G of heap and 1G metaspace, the usage eventual plateaus. With 9.2.9, my class load count would go to 30K within the first few minutes, then grows to 70K within the first 3 days, then it slows the growth to 2k/day. So it still look like some kind of leak, but at least it is a very slow one. The class unload count is usually 10% of the running total at any given time. Heap usage is usually between 900 MB to 1500 MB, with no obvious leak (because every few days when I GC, the memory goes down to below 1 GB).

In comparison, with the same Rails 4 app, running on JRuby 1.7, the class count would stay flat at around 25k-30k for 4 weeks easily. Heap usage is usually 400 MB - 700 MB.

**Comment by headius** [comment]
@ckpeter We would very much like to see those heap dumps. It certainly should not grow without end, and the numbers you are quoting seem suspect to us. We could learn a lot more by looking at a leaky heap dump from your application and investigating why so many classes are being generated.

**Comment by headius** [comment]
@ckpeter I should also mention this is a top priority for us. We want to do whatever necessary to get 9k memory use down, and a lot of that work should be in 9.2.9. Apparently we haven't hit the magic combination for your app.

**Comment by enebo** [comment]
@ckpeter do you use the same Java runtime for both environments?  Also can you open a new issue for this?  We would like to figure out what difference is at play here.  Your memory difference is massive between the versions.  This is surprising.

**Comment by ckpeter** [comment]
@enebo Yes I use the exact same 64-bit VM 1.8.0_101. The only difference is JRuby version (1.7.25 vs. 9.2.9)

@headius I'd be happy to investigate and get your the heap dumps. Unfortunately I just restarted the web server a few hours ago, so that blew away the history in the last 8 days. Let me run the app over 9.2.9 for a week, dump heap, and then run it over 1.7.25 fo a week, and dump heap. Assuming the memory differential is noticeable, I'll file a separate bug in a few weeks.

I assume it'd be enough to dump heaps and jconsole screenshots for both 1.7 and 9.2. If there is any other kinds of dumps or measurements you want me to collect, please let me know.

**Comment by headius** [comment]
@ckpeter I have gone ahead and opened #6020 from your two comments above so this discussion doesn't get lost if this issue stays unresolved.

I will comment there on what sort of information we need from a heap dump.

**Comment by headius** [comment]
@mrnonz The recent comments may or may not be relevant to this issue. At this point we are still hoping that you will try your app on JRuby 9.2.9 so we can confirm whether the problem still exists.

**Comment by mrnonz** [comment]
@headius I have already move to JRuby 9.2..9.0 but Problem still occur. You can see here #5993

**Comment by headius** [comment]
@mrnonz Oh I did not see that #5993 was connected with this issue. So perhaps we should close this one, since you appear to have reduced it to json in #5993. We can proceed to investigate there.
