### ISSUE TITLE
Nailgun Error - org.jruby.util.NailMain: command not found

### ISSUE THREAD

**Issue by rwilliams** [jruby/jruby#5981]
### Environment

jruby 9.2.9.0 (2.5.7) 2019-10-30 458ad3e OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [linux-x86_64]

**Host OS - WSL2**
Linux 975c34fa2e2c 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

**Docker Container**
GNU/LinuxDistributor ID: Debian
Description:    Debian GNU/Linux 9.11 (stretch)
Release:        9.11
Codename:       stretch

**Gem/Framework info:**
Rails 6.1 nothing too exciting

**Environment variables**
JRUBY_OPTS=--dev. I set JRUBY_OPTS to `--ng` after starting the server.

### Expected Behavior
I expect `rails routes` to show routes and run fast after warmup.

### Actual Behavior
I get the following error `/opt/jruby/bin/jruby: line 488: org.jruby.util.NailMain: command not found`

![image](https://user-images.githubusercontent.com/29144/69594765-38d06c00-0fb2-11ea-9d30-c5bbcafd086e.png)

**Comment by headius** [comment]
Ah yes...I didn't figure anyone would notice this being removed in 9.2.9. I guess I was wrong!

We'll have to debate if we want to restore it, and whether it's worth maintaining given that the slave JVM tends to always leak resources until it crashes.

**Comment by rwilliams** [comment]
Should it be removed from the docs until that time?

**Comment by headius** [comment]
I pushed changes for the launcher in a5b82328ff that replace the nailgun options with hard errors, so at least it's made clear that Nailgun is no longer supported.

I lament that this was necessary, but Nailgun never really worked well due to its inability to enforce "red line" memory and thread lifetime limits. It's best that we direct folks to more robust options like Drip or Theine.
