### ISSUE TITLE
NO SUCH METHOD ERROR GUAVA CHECK ARGUMENT

### ISSUE THREAD

**Issue by mufti1** [jruby/jruby#6013]
* I use Jruby 9.1.17.0

I got error `Java::JavaLang::NoSuchMethodError ('void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'):`

I have added `jar 'com.google.guava:guava', '21.0'` because the error above is because guava < 20 doesn't support that method, so I require jar in jar file to use guava 21.0 but still get the error. 

I try to use jruby 9.1.6.0 and its work but do you know but its not working at jruby 9.1.17.0?

**Comment by headius** [comment]
@mufti1 First of all, could you test on JRuby 9.2.9? There have been various changes to Java binding and dispatch since 9.1.17.0 and this may no longer be an issue.

Secondly, there are known issues with Java 9+ due to the way Java modules interact with JRuby's Java dispatch. If you are running Java 9 or higher we need to know that.

Finally, if it's still failing for you on JRuby 9.2.9 (regardless of Java version) it would be helpful if we had some code to reproduce the issue.

Thank you for reporting this problem!

**Comment by mufti1** [comment]
@headius I've tried to use JRuby 9.2.9.0 and still getting the same error

`Java::JavaLang::NoSuchMethodError ('void com.google.common.base.Preconditions.checkArgument(boolean, java.lang.String, char, java.lang.Object)'):`

**Comment by mufti1** [comment]
stacktrace
```
io.grpc.Metadata$Key.validateName(io/grpc/Metadata.java:629)
io.grpc.Metadata$Key.<init>(io/grpc/Metadata.java:637)
io.grpc.Metadata$Key.<init>(io/grpc/Metadata.java:567)
io.grpc.Metadata$AsciiKey.<init>(io/grpc/Metadata.java:742)
io.grpc.Metadata$AsciiKey.<init>(io/grpc/Metadata.java:737)
io.grpc.Metadata$Key.of(io/grpc/Metadata.java:593)
io.grpc.Metadata$Key.of(io/grpc/Metadata.java:589)
io.grpc.internal.GrpcUtil.<clinit>(io/grpc/internal/GrpcUtil.java:86)
io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(io/grpc/internal/AbstractManagedChannelImplBuilder.java:83)
```

**Comment by ashuvyas45** [comment]
@mufti1  If you are using Jbundler for managing the dependencies you may come across this. The issue I faced with Jruby 9.1.17.0 and using Jbundler is that it adds two dependencies which are:
- com.google.protobuf:protobuf-lite:jar:3.0.1
- com.google.protobuf:protobuf-java:jar:3.1.0

Try using lock_jar to manage your java jars and hopefully it will fix this problem.

**Comment by headius** [comment]
@ashuvyas45 That's helpful, thank you!

Based on the Java trace you provided this does not appear to be a JRuby issue. I suspect you are getting conflicting versions of jars somewhere in your stack (similar to what @ashuvyas45 describes) because a `java.lang.NoMethodError` is only thrown when code compiled to call a given method can't actually find that method at runtime. If this were a JRuby issue, you'd either get a Ruby `NameError` or `NoMethodError` or possibly a Java reflection error like `java.lang.NoSuchMethodException`.

**Comment by mufti1** [comment]
> @mufti1 If you are using Jbundler for managing the dependencies you may come across this. The issue I faced with Jruby 9.1.17.0 and using Jbundler is that it adds two dependencies which are:
> 
> * com.google.protobuf:protobuf-lite:jar:3.0.1
> * com.google.protobuf:protobuf-java:jar:3.1.0
> 
> Try using lock_jar to manage your java jars and hopefully it will fix this problem.

Thanks this is works
