### ISSUE TITLE
Less modes to run JRuby, and one single mode to benchmark JRuby

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6094]
Currently JRuby seems to have at least 3 major modes to run:
* `jruby myscript.rb`, the default.
* `jruby --dev ...` for improving startup, at the cost of degrading peak performance.
* `jruby -Xcompile.invokedynamic=true ...` which uses invokedynamic.

That's I think more modes than any other Ruby implementation.
MRI has default and `--jit`, TruffleRuby has default and `--jvm` (in GraalVM, otherwise only the default mode).

When I (or someone else) benchmark JRuby, let's say with a `benchmark-ips` benchmark so startup is not the biggest concern, I would like to only run JRuby in just one mode and not have to guess the right one or run in different modes and need to compare.
So which mode should I choose?

I think the default mode should be the one producing good benchmark results.
Otherwise, any numbers reported should specify the alternative mode used and also risks being very far from what people use in production.
`-Xcompile.invokedynamic=true` is so long and so hard to find that I guess very few JRuby users use it in production, it looks more like a performance debugging option to me (much like the other 23 `-X` options with `invokedynamic` in the name).

In fact, I think many people don't even know `-Xcompile.invokedynamic=true`, which seems a pretty obscure option, by being not mentioned in `jruby -h`, `jruby --help` nor `jruby -X`.
For comparison, `--jit` is listed by `ruby -h/--help` and `--jvm` is listed by `truffleruby --help`.
The only way I found to list this option is `jruby '-X?' | grep invoke`, so I expect very few will manage to even find the option or even know about it.

One example to illustrate what I'm saying is https://twitter.com/headius/status/1230915989786648576:
> JRuby's now pushing close to 100FPS for me locally on the Ruby "optcarrot" benchmark, with CRuby around 35FPS

That I think is misleading, `jruby bin/optcarrot ...` is [about 27 FPS](https://twitter.com/eregontp/status/1231170402497519618).
`jruby -Xcompile.invokedynamic=true bin/optcarrot ...` is about 86 FPS, and about the same as `ruby --jit`.
The reason I think it's misleading is:
* People can't reproduce these numbers without guessing and searching hard for that flag
* People are unlikely to experience such performance when running `jruby ...`.

I think there are two ways forward:
* Make `-Xcompile.invokedynamic=true` the default. Then it's actually true `jruby ...` has that performance, and everyone experiences it.
* Have an easier-to-find, better documented flag like `--indy`, and mention it whenever benchmark results depend on it.

I think the second is not nearly as good as the first one, because it will again mean people will most likely observe fairly different performance in their production applications running on JRuby with default flags. But it'd be an improvement over the current state.

**Comment by PragTob** [comment]
I'm in favor of `--indy` - I know of the problems why invokedynamic isn't default but a more easy to discover option seems nice.

I still haven't published new benchmarking results, bu in my rubykon benchmarks ID is a huge factor as well: https://pragtob.wordpress.com/2017/01/24/benchmarking-a-go-ai-in-ruby-cruby-vs-rubinius-vs-jruby-vs-truffle-a-year-later/

However, not sure where to call it quits. The new default GC can have a huge impact as well ( #5789 ) should there be an easy option to switch that around as well? Yes/no/maybe?

I think indy is a more common case than GC tuning though.

**Comment by eregon** [comment]
I think such a blog post is actually good motivation to have invoke dynamic by default.

Otherwise we're just reporting numbers based on some flags people are just unlikely to use in production, and so numbers which just don't matter for most people using JRuby (which just use the default and no flags).

Why should JRuby need two measurements instead of 1 like every other implementation in that blog post? I think it shouldn't and it would make for an easier story for JRuby performance and the blog post if invokedynamic was the default.

Yes, the JVM is always an extra dimension for JRuby. I would guess 90+% use HotSpot though, so the only significant variance is probably JDK11+ vs JDK8. I think whatever is installed on the system ends up being used in most cases, so it's often not much of a choice. If ParallelGC performs better in most JRuby workfloads, it could be parts of the defaults when running `jruby ...`.
I think no one wants to run a benchmark in e.g. 8 different configurations (default/indy + JDK8/11 + ParallelGC/G1), the default configuration should perform well, and by being the default it is representative of what most JRuby users experience.

**Comment by PragTob** [comment]
Iirc indy was slowing down rails performance both in dev and in prod (not sure about most recent developments) and as that's still most of the ruby use cases I think that's what should be mostly indicative of what should be the default - not performance blog posts.

I agree it's odd to have that bit extra in the blog post. To be fair, the newest edition will also include the jit flag for CRuby so it's not that different in the end :)

**Comment by enebo** [comment]
@eregon this has been a balancing act for us.  In theory we would like to have invokedynamic fully on all the time.  We do have users and when we have enabled this in the past we had a collection of happy users and a stream of issue reports that warmup was unacceptable from a second group.

My take has been if you are about redmine or smaller having compile.invokedynamic on is faster and warmup is not much worse than not having it enabled.  For larger web apps it is problematic for warmup.  I will even qualify this a bit more in saying it depends how broad the application is (tons of controllers).

So until we address warmup with that mode on for large web applications we will not be having this be the default.

Personally, I am meh on --indy but I agree it would be easier to remember for new users.  Your issue does underscore that we should be doing a better job on documentation.

**Comment by headius** [comment]
> Have an easier-to-find, better documented flag like --indy, and mention it whenever benchmark results depend on it.

I'm leaning this way right now (and have advocated for it in the past) since there's still concerns about whether indy is always a gain. I would consider it a bug when it's not faster than running without indy, but that has been difficult to quantify. It also has several knock-on effects:

* Increased JVM bytecode to support method handle changes
* Increased metaspace consumption to load all that bytecode
* Possibly increased code cache usage because of better inlining and specialization of call paths.

I'm, also not convinced why optimized-by-default is better than fast-startup-by-default. We have had plenty of folks make compelling cases for `--dev` to be the default and production mode to be the option you have to turn on.

Once I'm back from travel I will be doing some exploration into better "gradual" indy use, where we might bind simple invocations at first and more optimized, specialized call paths as those sites get hot. This may make reduce the startup and memory impact of indy and focus the heaviest, most optimizable indy usage on the sites that need it most.

**Comment by headius** [comment]
Some other thoughts on a new flag...

* Having something in `--help` would clearly improve visibility. I think we all agree on that.
* `--indy` is probably a poor name since there will be other things besides indy we might enable in an optimized mode (e.g. deeper specialization of objects and arrays, unboxing optimization passes, fixnum cache changes, method splitting...).
* There may be other levels of optimization to consider. Currently the `compile.invokedynamic` mode actually has a number of other flags that can enable/disable specific uses of indy, and there are tunables like polymorphic cache size.

Flag ideas:

* `--optimize` would be fairly clear, and doco would say this flag may improve the performance of your application, perhaps with a wiki link for more information.
* Along the same lines, a `-O` flag would probably be recognized by most users as a standard optimization flag., `-O0` might be equivalent to dev mode, `-O1` might be current "normal" execution", and `-O2` might be "optimized" mode.

I should be clear on one thing: I've always wanted a specific flag for "optimized mode", because of the improved visibility and ease of use.

**Comment by enebo** [comment]
--optimize is much better than --indy and it would be good to come up with an even nicer intent-based name if one exists.  --indy is not really even completely understood by people who know what invokedynamic is.  My only complaint with --optimize is there are lots of things which can be optimized.  Straight-lined peak performance is just a common one.  I do not have a better suggestion though.

 Personally -O{n} seems ugly to me even if it allows a numeric rating along with a commonly understood analogue...I guess I might come around on that :) 

I still have hopes we can have something like jit time threshold pan out.  That would largely eliminate the warmup time aspect that our current runtime has.  That does not mean we would not want some extra flag(s) for additional optimizations though.

**Comment by headius** [comment]
@enebo Remember years ago we flirted with the idea of a `--fast` flag :-)

**Comment by headius** [comment]
Another idea related to `-O` would be something more like `-Ostartup`, `-Opeak`. I admit I don't like the `-O` options as much as something simple like `--optimize`.

**Comment by eregon** [comment]
> * Increased JVM bytecode to support method handle changes
> * Increased metaspace consumption to load all that bytecode

Isn't at least some of the invokedynamic constructs like MethodHandle and SwitchPoint used all the time? Then is it significantly more bytecode to load just with `-Xcompile.invokedynamic=true`?

**Comment by eregon** [comment]
> My take has been if you are about redmine or smaller having compile.invokedynamic on is faster and warmup is not much worse than not having it enabled. For larger web apps it is problematic for warmup. I will even qualify this a bit more in saying it depends how broad the application is (tons of controllers).

Should the default really be to optimize warmup for these large apps at the cost of peak performance? 
Those large apps probably want to compare with indy on, and trading (potentially a lot of) peak performance by default (silently) seems suboptimal.

---

One thing I know is the next time I benchmark JRuby I don't want to fiddle with multiple modes, I want to measure just one mode. And I think the default mode is the most used mode, and so the one I should measure to represent most usages of JRuby.

**Comment by headius** [comment]
@eregon Does TruffleRuby not achieve better performance in JVM mode? Why then do you have to explicitly install and request that mode? I see this as a very similar situation... your default native execution mode is a balance between peak and startup performance. By your logic, everyone should run TruffleRuby in JVM mode by default, since that's the best mode for performance.

**Comment by eregon** [comment]
To clarify, what I wrote just above is what I would like (just measure one mode of JRuby, not having to compare multiple modes, and I think that mode should be the default), not necessarily what I will do. I'm discussing some inconsistency here between what JRuby users run and what's reported in benchmarks of JRuby, and the complications that 3 modes bring.

It goes back to my first question:
> So which mode should I choose (for benchmarking)?

Should that be the invokedynamic mode? Should that be the current default mode?

To me, `-Xcompile.invokedynamic=true` feels like a highly specialized flag that JRuby users seem rather unlikely to use in production. Something a bit like a (imaginary) `--split-every-method` flag, that might gain something on peak, but would be a bad trade-off for warmup that most if not all people wouldn't want to take in production. That example is more extreme of course, but maybe it helps to explain my view on this. I think `-Xcompile.invokedynamic=true` is not such an extreme trade-off and could be the default.

In some cases the JVM mode of TruffleRuby has higher performance. I guess the main difference is I would be fine with people reporting numbers (only) for TruffleRuby Native, since that's the default mode, but I guess you might be less happy if somebody reports benchmark numbers of JRuby (only) in the default mode.

I think anyone benchmarking JRuby shouldn't need to know anything more than when they benchmark MRI, TruffleRuby, Rubinius, etc. The default mode is what most people use and it should be a good way to benchmark in a mode representative of most usages.

**Comment by headius** [comment]
Fixed by #8450.
