### ISSUE TITLE
Consider defining RUBY_PLATFORM similar to other Rubies

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6152]
JRuby currently defines `RUBY_PLATFORM` as `"java"`.
This is an incompatibility with MRI, TruffleRuby and AFAIK all other Ruby implementations, and it makes that constant not so useful on JRuby. `RUBY_PLATFORM` should be I guess "the platform on which the Ruby runs on" and `"java"` is inaccurate, there are many differences when running JRuby on Linux vs Windows.

`RbConfig::CONFIG['host_os']` is a pretty long workaround.

For instance code like this will fail to check correctly on JRuby:
```ruby
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

if /mswin|mingw/ =~ RUBY_PLATFORM
```

Could you consider defining RUBY_PLATFORM like other Ruby implementations for better compatibility, and for gems not having to treat JRuby specially because of this?

There are usages depending on it being in the wild though, so it would need a migration plan, for instance by detecting things like `RUBY_PLATFORM =~ /java/` and `RUBY_PLATFORM == "java"` and warning in the parser to instead use `RUBY_ENGINE == "jruby"`.

**Comment by headius** [comment]
Adding a bit more from Slack discussion...

This was originally set to "java" because RubyGems used it to determine platform-specific gems. Because our extension gems work the same on all platforms, "java" made the most sense. RubyGems has since moved to using `RbConfig::CONFIG['arch']`, which we set to something like "universal-java18".

This also appears to have been used by a large number of libraries and apps to simply detect JRuby, a la either `RUBY_PLATFORM == "java"` or `RUBY_PLATFORM =~ /java/`. A Github search yields over 200k instances of these forms. A gem search by @eregon yielded these numbers:

```
$ csearch RUBY_PLATFORM | wc -l
19420
$ csearch 'RUBY_PLATFORM.+\bjava\b' | wc -l
5335
$ csearch 'RUBY_PLATFORM\s*[=!][=~]\s*['"'"'"/]java['"'"'"/]' | wc -l
4868
$ csearch 'RUBY_PLATFORM.+(win|mingw)' | wc -l
6971
```

So there's thousands of lines of library code out there expecting this constant to at least contain the substring "java", and another bunch of code that wants it to be exactly "java". Beyond gems there are thousands of JRuby users out there with their own code, many of whom are likely also using this pattern.

This would certainly not be a change in JRuby 9.3. At best it would be in 9.4 some time in 2021 (or later) and we'd need a long deprecation and lots of PRs before we flipped the switch.

**Comment by eregon** [comment]
Related as a better way do do platform checks: https://bugs.ruby-lang.org/issues/16742

**Comment by enebo** [comment]
@eregon once all our users are able to use your suggested windows? check and have switched to that we will consider deprecating and changing that value (and also changing jruby detection to be consistent).  As it stands you are asking a TON of us because you don't think it makes sense.  

Even if I agree with you that it could be better...legacy software is tough.  Considering there is a lot of gems out there which are very occasionally updated.   I suspect 2021 is EXTREMELY generous even if we did commit to this.  I do not see a big pay off for that much effort.

Not trying to sound too negative but we have lots of things we can be working on which improve users lives a lot more.

**Comment by headius** [comment]
This is not going to happen for the foreseeable future. We were able to find hundreds of gems and thousands of source code files on github that still use the `RUBY_PLATFORM == "java"` check. Changing this to any other value would break that code, and making it be a "special" string that allows `==` to return true for a partial substring seems very sketchy to me, especially since this string is often passed on and used for other purposes.

Perhaps it is unfortunate that we set this value in stone so long ago, but for our purposes it makes sense; JRuby's platform is Java, so our RUBY_PLATFORM is "java".

The path forward would seem to be getting everyone using RUBY_PLATFORM to determine if they're on JRuby to switch to RUBY_ENGINE. We'll need to do a lot of pull requests. Perhaps a "fun" activity for some contributor.

**Comment by eregon** [comment]
OK, let's close this issue.
Checking for `RUBY_ENGINE == "jruby"` seems a nice improvement over `RUBY_PLATFORM == "java"` which is a non-standard to check the interpreter.

It's an unfortunate decision back then, since of course even JRuby behaves differently based on the underlying operating system. But I understand for compatibility it's not realistic to change it.

**Comment by eregon** [comment]
FWIW looking at https://github.com/search?q=%2FRUBY_PLATFORM.%2Bjava%2F+language%3ARuby&type=code&l=Ruby&p=1 most matches displayed there are the same:
```ruby
# Windows and JRuby do not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
install_if -> { RUBY_PLATFORM =~ %r!mingw|mswin|java! } do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end
```

https://github.com/search?q=%2FRUBY_PLATFORM.%2B%5B%27%22%5Djava%5B%27%22%5D%2F+language%3ARuby&type=code&p=1 ignores those and finds many usages which should probably all be `RUBY_ENGINE == 'jruby'` instead.

**Comment by headius** [comment]
I'm not sure how to fix this globally. Changing it to reflect the actual platform now would break all of these cases, whether they could move to a `RUBY_ENGINE` check or not.

We could try to introduce something into our parser/compiler that warns when seeing a `RUBY_PLATFORM` match against a `java` string or regexp, but we'd need that in place for a long time for it to trickle back to the many places it is used. Meanwhile we'd definitely get bug reports about new warnings on startup, and many users would be unable to patch around it since they don't control the libraries in question.

On the positive side, `RUBY_ENGINE` has existed for long enough now that we would not be at risk of breaking older JRuby users (it has existed since JRuby 1.1.2).

On the negative side, the minute we change `RUBY_PLATFORM` all unpatched versions of all those libraries will be broken on newer JRuby.

I hate to say it but the best option might be to add a new constant we can all agree should reflect the current host OS/arch. It would be something like `RUBY_ARCH` or `RUBY_NATIVE_PLATFORM` that reflects the same value as `RbConfig::CONFIG['arch']` (which is what RubyGems now uses instead of `RUBY_PLATFORM` or the `host_os` value).

**Comment by headius** [comment]
> the same value as RbConfig::CONFIG['arch']

Actually that would not be the value to use since it's something like `universal-java17` on JRuby.

There are a number of values in `RbConfig::CONFIG` that could be used to get OS and arch:

```
$ ruby33 -rrbconfig -e "pp RbConfig::CONFIG.select {|k,v| k =~ /host|target/}"       
{"target_os"=>"darwin23", "target_vendor"=>"apple", "target_cpu"=>"arm64", "target"=>"arm64-apple-darwin23", "host_os"=>"darwin23", "host_vendor"=>"apple", "host_cpu"=>"arm64", "host"=>"arm64-apple-darwin23", "target_alias"=>"", "host_alias"=>""}
```

Another option would be adding OS and arch into JRuby's `RUBY_PLATFORM` but that would only help uses based on a `=~ /java/` regexp; all cases doing a strict `== "java"` would still break.

**Comment by eregon** [comment]
It seems JRuby doesn't a RbConfig::CONFIG entry with a value corresponding to the correct RUBY_PLATFORM, even though there are multiple on CRuby and TruffleRuby:
```
$ ruby -v
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
$ ruby -e 'p RUBY_PLATFORM'
"x86_64-linux"
$ ruby -e 'pp RbConfig::CONFIG' | grep '"x86_64-linux"'
 "sitearch"=>"x86_64-linux",
 "arch"=>"x86_64-linux",
 "platform"=>"x86_64-linux",

$ ruby -v                                          
truffleruby 24.1.1, like ruby 3.2.4, Oracle GraalVM Native [x86_64-linux]
$ ruby -e 'p RUBY_PLATFORM'
"x86_64-linux"
$ ruby -e 'pp RbConfig::CONFIG' | grep '"x86_64-linux"'
 "arch"=>"x86_64-linux",
 "sitearch"=>"x86_64-linux",

$ ruby -v                                          
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 17.0.12+7 on 17.0.12+7 +jit [x86_64-linux]
$ ruby -e 'p RUBY_PLATFORM'                        
"java"
$ ruby -e 'pp RbConfig::CONFIG' | grep '"x86_64-linux"'
$ ruby -e 'p RUBY_DESCRIPTION'                     
"jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 17.0.12+7 on 17.0.12+7 +jit [x86_64-linux]"
```

So many gems have to workaround like https://github.com/ruby/mspec/blob/5354a405e327bb144f00157b913aa544c3b77e4b/lib/mspec/guards/platform.rb#L19-L24

**Comment by headius** [comment]
The two `arch` values shown in your example reflect `java` platform naming on JRuby. However I think we'd be pretty safe modifying them to match other "real" arch and OS values.

```
$ jruby -rrbconfig -e 'pp RbConfig::CONFIG.select{|k,v|k=~/arch$|platform$/}'
{"arch"=>"universal-java24", "sitearch"=>"java"}
```

We do not define `platform` at all. It could be defined to reflect the native platform typically in RUBY_PLATFORM.

The equivalent platform value can be inferred from `host_cpu`-`host_os` or `target_cpu`-`target_os` currently.

**Comment by headius** [comment]
I think it's still not feasible for us to change `RUBY_PLATFORM` so let's move future discussion to a new issue.
