### ISSUE TITLE
webrick tests fail on jruby

### ISSUE THREAD

**Issue by deivid-rodriguez** [jruby/jruby#6171]
We're getting [a random test failure we're getting when testing rubygems against jruby](https://github.com/rubygems/rubygems/issues/3451), which shows a backtrace inside webrick's code.

Since the failure is specific to jruby, I tried running `webrick` tests against `jruby`.

**Expected Behavior**

webrick tests pass under jruby.

**Actual Behavior**

You can see the current failures on [this WIP PR](https://github.com/ruby/webrick/pull/40) I opened at the webrick repo, where I just set up some changes so that the test suite at least runs properly.

current stable: https://github.com/ruby/webrick/pull/40/checks?check_run_id=577693801
current head: https://github.com/ruby/webrick/pull/40/checks?check_run_id=577693789

**Comment by headius** [comment]
Hmm yes, we should get those tests running again and green. So many projects, so little time!

**Comment by deivid-rodriguez** [comment]
Yeah... it happens :)

**Comment by headius** [comment]
With #6246 I believe I've made the tests as green as possible. A few issues remain:

* OpenSSL callbacks are not being called in all the right places, leading to failures in test_ssl.rb's `test_sni`. See jruby/jruby-openssl#201 and jruby/jruby-openssl#202.
* Log-testing logic from `start_server` in WEBrick's test/lib/webrick/unit.rb is not thread-safe, and attempts to read two arrays that are being concurrently modified. This sometimes leads to a concurrency error.
* Server setup in the `test_restart_after_stop` test from test_server.rb is not properly ensuring threads are started and variables initialized in proper sequence, leading to races that sometimes cause the test to fail.

The first case will need work in jruby-openssl that's probably unlikely to happen without some help from the community. The other two cases require fixes in the WEBrick tests. Only the `test_sni` failure happens consistently, at this point.

I'm going to close this since there's new issues filed for the SSL problems and the other issues are in WEBrick's tests.

**Comment by headius** [comment]
Oops, reopen until #6246 has been reviewed and merged.

**Comment by headius** [comment]
#6246 was merged some time ago and resolved as many of these failures as possible. The remaining issues are not in JRuby.
