### ISSUE TITLE
"Illegal reflective access operation" 

### ISSUE THREAD

**Issue by abelsromero** [jruby/jruby#6189]
**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)

9.2.11.1

* Operating system and platform (e.g. `uname -a`)

Linux man-pc 5.6.6-1-MANJARO #1 SMP PREEMPT Tue Apr 21 07:46:00 UTC 2020 x86_64 GNU/Linux

Other relevant info you may wish to add:
* Installed or activated gems

Using asciidoctor. All gems provided inside Java jars.

* Application/framework version (e.g. Rails, Sinatra)

Maven

* Environment variables

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.

I assumed the message was normal, but seeing other issues in this repo, maybe is not? Any clarificaction will be greatly appreciated.

* Provide an executable Ruby script or a link to an example repository.

1. Clone: https://github.com/asciidoctor/asciidoctor-maven-examples
2. Update jruby version in https://github.com/asciidoctor/asciidoctor-maven-examples/blob/81600e7ee04f4f1fab81ab9c466a65d557aa75c0/asciidoc-to-html-example/pom.xml#L17
3. Place terminal in directory *asciidoc-to-html-example* and run `mvn`.

**Actual Behavior**

* Describe or show the actual behavior.

This warrning appears during build

```
[INFO] --- asciidoctor-maven-plugin:2.0.0-RC.1:process-asciidoc (asciidoc-to-html) @ asciidoc-to-html-example ---
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/home/asalgadr/.m2/repository/org/jruby/jruby-complete/9.2.11.1/jruby-complete-9.2.11.1.jar) to method sun.nio.ch.NativeThread.signal(long)
WARNING: Please consider reporting this to the maintainers of com.headius.backport9.modules.Modules
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Rendered /home/asalgadr/github/asciidoctor-maven-examples/asciidoc-to-html-example/src/docs/asciidoc/example-manual.adoc
```

* Provide text or screen capture showing the behavior.

**Comment by headius** [comment]
These warnings are harmless and usually when running JRuby directly you won't see them (because we open the related modules up). However running this as a maven target does not pass the same flags so we get these warnings.

A full trace of this and a similar warning for `NativeThread.current` can be seen below (note I'm running JRuby from the jar file):

```
$ java --illegal-access=debug -cp lib/jruby.jar -Djruby.home=`pwd` org.jruby.Main -e 'pid = spawn("ls"); Process.waitpid(pid)'
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/Users/headius/projects/jruby/lib/jruby.jar) to method sun.nio.ch.NativeThread.signal(long)
	at com.headius.backport9.modules.Modules.checkOpen(Modules.java:62)
	at com.headius.backport9.modules.Modules.trySetAccessible(Modules.java:44)
	at com.headius.backport9.modules.Modules.trySetAccessible(Modules.java:30)
	at org.jruby.javasupport.Java.trySetAccessible(Java.java:1657)
	at org.jruby.RubyProcess.<clinit>(RubyProcess.java:939)
	at org.jruby.Ruby.<init>(Ruby.java:458)
	at org.jruby.Ruby.newInstance(Ruby.java:717)
	at org.jruby.Main.internalRun(Main.java:273)
	at org.jruby.Main.run(Main.java:234)
	at org.jruby.Main.main(Main.java:206)
WARNING: Illegal reflective access by com.headius.backport9.modules.Modules (file:/Users/headius/projects/jruby/lib/jruby.jar) to method sun.nio.ch.NativeThread.current()
	at com.headius.backport9.modules.Modules.checkOpen(Modules.java:62)
	at com.headius.backport9.modules.Modules.trySetAccessible(Modules.java:44)
	at com.headius.backport9.modules.Modules.trySetAccessible(Modules.java:30)
	at org.jruby.javasupport.Java.trySetAccessible(Java.java:1657)
	at org.jruby.RubyProcess.<clinit>(RubyProcess.java:939)
	at org.jruby.Ruby.<init>(Ruby.java:458)
	at org.jruby.Ruby.newInstance(Ruby.java:717)
	at org.jruby.Main.internalRun(Main.java:273)
	at org.jruby.Main.run(Main.java:234)
	at org.jruby.Main.main(Main.java:206)
```

This logic *should* just be giving up on the reflective access when the module isn't open... but for some reason it does not do that, and produces this warning anyway. I am investigating locally.

**Comment by headius** [comment]
It seems like we're doing the right thing and yet it still warns. We ask the module if the package is open, and it returns true. So we proceed to attempt to set the `signal` and `current` methods to be accessible, and then it warns. This does not match my expectation.

**Comment by headius** [comment]
I have narrowed this down to what seems like a JDK issue. It's always reporting `isOpen => true` for the unnamed module.

https://gist.github.com/headius/7686a5ba9b4b3233782584000a4dff19

**Comment by headius** [comment]
FWIW this should not affect anything on your end. The warning is purely informational.

**Comment by jsolomon8080** [comment]
We ship this jar and the warning, while purely informational, if not something we can tolerate in our logs or on the console. Is there an easy way to suppress or eliminate the warning message before the bug is actually fixed?

**Comment by headius** [comment]
@jsolomon8080 I appreciate your situation... we can work through this until I figure out how to make the Java module system happy.

The brute-force way would likely be to pass an `--add-opens` flag to the JVM that eventually runs JRuby, either through `MAVEN_OPTS` or `JAVA_OPTS`.

The flag format is like this (tailored to the `signal` error):

```
--add-opens java.base/sun.nio.ch=ALL-UNNAMED
```

...adding additional flags for any other packages that come up.

**Comment by headius** [comment]
More information from exploring this...

Based on some Twitter discussions, it appears that it is *expected behavior* for `isOpen` to always return true when the caller is from an unnamed module. However this means there's no way (I know of) to determine when we can safely use `setAccessible` without producing a warning.

I am continuing to chat and investigate options.

**Comment by jsolomon8080** [comment]
This is the command line that produces no warnings:

% java --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED --add-opens java.base/javax.crypto=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED -cp jruby-complete-9.2.9.0.jar org.jruby.Main --disable-gems -e '1'

Any chance there is a more concise form of this? Not only to be shorter, but also to be more global so that it may catch other instances that haven't been hit yet by this very simple example? Anyway to specify a wildcard to open up everything?

It seems that backport9 is needed to allow folks using java9 features with this jruby but still using java8. Well, we are using java11 so is there a way to just completely disable the loading and use of backport9? If we could do that, we can avoid all these warnings.

**Comment by headius** [comment]
@jsolomon8080 

First off, you should try 9.2.11+ to see if it helps some of these warnings.

The backport9 library just provides a shim to the Java 9+ module APIs. If we just removed it, the warning would move somewhere else.

The flags you have there are pretty much the answer for now. You can make it less painful by putting them into an environment variable (OpenJDK honors a hidden `_JAVA_OPTIONS` variable), or you can put them into a file and reference the file using the "arguments file" notation `@filename`, as in `java @my_opts_file ...`. See bin/.jruby.module_opts for an example of the file format (basically just stick the options in there like a command line, and newlines are allowed).

There may be a path forward for fixing this as well... it sounds like using the MethodHandle API allows accessing these APIs without causing warnings... or at least moves the warning to an exception I can handle silently. I will experiment with this.

**Comment by abelsromero** [comment]
> FWIW this should not affect anything on your end. The warning is purely informational.

I had no doubt about that. Is just that people ask and I did not know what to say :man_shrugging: If at the end this cannot be fixed at jruby level, adding `--add-opens` with `MAVEN_OPTS` and `JAVA_OPTS` if good enough to prevent the warning, especially in build pipelines.

**Comment by headius** [comment]
@abelsromero For the current release unfortunately that is the case. I am working on tweaks for the next version of JRuby (9.3) to reduce or eliminate these warnings.

**Comment by wjcarpenter** [comment]
> Based on some Twitter discussions, it appears that it is expected behavior for isOpen to always return true when the caller is from an unnamed module

That seems like a pretty weird design. The entire intent of `isOpen()` is to see if you're allowed to do the thing you later get warned about. So, if you are in an unnamed module, there is no point to even calling `isOpen()`. If you were to put `backport9` or JRuby into a named module, would that resolve things?

(I know it's not you who designed that `isOpen()` behavior. I replicated your experiments from the gist, and read the docs. I agreed with your expectations.)

**Comment by wjcarpenter** [comment]
Ah! I just figured something out that explains both the weird "by design" behavior. Maybe everybody else already understood this, and I'm the only one just waking up.

The default option of `--illegal-access=permit` causes `isOpen()` to return true for all classes in the unnamed module. I thought there was just some code somewhere that said "with this setting, give the warning, but otherwise skip the check". What it actually does (and is documented as doing, but I was blind to it) is explicitly open those internal modules to everything in the unnamed package. So, of course, it makes sense that `isOpen()` returns true. Because it literally is true.

Counter-intuitively, if you sent `illegal-access=deny`, then the internal modules are not explicitly opened up, and `isOpen()` returns false. (I just tried it with the example from the gist.) Well, that is pretty good news for what backport9 is trying to do, I think.

There is one snag for the code in the gist, though. If you use a line like:
```
Class cls = sun.nio.ch.NativeThread.class;
```
you will get an exception like this on that line of code:
```
java.lang.IllegalAccessError: class ModuleThing (in unnamed module @0x5aaa6d82) cannot access class sun.nio.ch.NativeThread (in module java.base) because module java.base does not export sun.nio.ch to unnamed module @0x5aaa6d82
```
So, you would have to switch to `Class.forName()` , which does not throw the exception. But I think that probably isn't a problem for the backport9 code itself.

**Comment by headius** [comment]
@wjcarpenter Yeah you seem to have gone through the same analysis process I did on Twitter.

The logic works like this...

Until Java 16, they needed a way to allow reflective access from non-modularized code to continue to work. That means all unnamed modules need to be able to reflect against core JDK code without raising an error if they would not have raised an error before. However in order to start encouraging people to stop depending on that reflective access, they made it still warn if the packages are open only because you're calling from the unnamed module.

If however, the packages in question are explicitly opened, then the check for the unnamed module doesn't happen and the warning is not printed. By specifying a `--add-opens` we now have a "real" opening of the package, and we never proceed to the point of treating them as implicitly open.

The trick I discovered is making those implicitly open packages to be explicitly opened by calling Module.addOpens. I have employed this in the work in #6195 and modified backport9 to do this in its trySetAccessible implementation (which has always been there to setAccessible if possible but avoid warnings).

With all the tweaks in #6195, a bare JRuby jar on the classpath no longer triggers warnings. JRuby's jar as a module can't open up those packages, but we will warn to indicate what functionality has been degraded and how to open it up (and of course running JRuby at a command line will apply those flags automatically).

The remaining challenge will be embedded uses of JRuby that still put it on the classpath after Java 16, or that put it on module path without the necessary flags. We will do our best to fall back to degraded functionality. That degraded functionality will often still work fine... for example asciidoctor shouldn't need true native IO or process management. But there will likely always be a few packages we need access to for full Ruby compatibility. We just need to make it clear to uses how to achieve that.

**Comment by headius** [comment]
As usual, there will be cases I haven't covered in #6195, but that should bring us much closer avoiding the illegal access warnings. To summarize:

* JRuby run from classpath (not as a module) will avoid warnings by making partially-open JDK modules be actually open.
* JRuby run from a module will avoid warnings by never accessing anything that's not open, with warnings as appropriate indicating how to avoid the degraded functionality.

The changes in #6195 have been applied to reflective access we do to support Ruby compatibility (e.g. file descriptor access) as well as to our Java integration subsystem (e.g. binding only methods that can be made accessible). We will fix any missed cases as they come up (and please keep reporting them!)
