### ISSUE TITLE
Duplicate jnr-ffi classes when combining jruby-core with jython-slim

### ISSUE THREAD

**Issue by ctrueden** [jruby/jruby#6205]
The Jython project now has a jython-slim artifact with proper modular dependencies.
I want to build a project that depends on both JRuby and Jython, so I tried adding dependencies on `org.jruby:jruby-core:9.2.11.1` and `org.python:jython-slim:2.7.2`. My project uses an enforcer rule to validate that there are no duplicate classes on the classpath, which uncovered the fact that `jruby-core` ships the `jnr-ffi` classes unshaded.

Here is a sample `pom.xml` which illustrates the issue (just create it, then run `mvn`):

<details><summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>combine-jruby-and-jython</artifactId>
	<version>0-SNAPSHOT</version>

	<name>JRuby + Jython</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.jruby</groupId>
			<artifactId>jruby-core</artifactId>
			<version>9.2.11.1</version>
		</dependency>
		<dependency>
			<groupId>org.python</groupId>
			<artifactId>jython-slim</artifactId>
			<version>2.7.2</version>
		</dependency>
	</dependencies>

	<build>
		<defaultGoal>install</defaultGoal>
		<plugins>
			<plugin>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>1.4.1</version>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.mojo</groupId>
						<artifactId>extra-enforcer-rules</artifactId>
						<version>1.2</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>enforce-rules</id>
						<goals>
							<goal>enforce</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<rules>
						<!--
						Ensure no two dependencies ship the same class.
						Otherwise, much havoc may be wreaked at runtime.
						-->
						<banDuplicateClasses>
							<findAllDuplicates>true</findAllDuplicates>
						</banDuplicateClasses>
					</rules>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

</details>

The first few lines of the error are:
```
Duplicate classes found:

  Found in:
    com.github.jnr:jnr-ffi:jar:2.1.10:runtime
    org.jruby:jruby-core:jar:9.2.11.1:compile
  Duplicate classes:
    jnr/ffi/provider/InterfaceScanner$2.class
    jnr/ffi/provider/jffi/BufferParameterStrategy$1.class
    jnr/ffi/provider/jffi/HeapBufferParameterStrategy.class
    ...
```

Is there a jruby artifact that avoids shipping dependencies unshaded? Or is there some other solution I should use here? I'd rather not be at the mercy of the classpath order.

**Comment by headius** [comment]
What a peculiar use case!

Shading jnr-* is definitely an option. I am wondering, however, whether shading should still exist in this new world of Java modules. The other day I mused that we might want to start shipping jruby-core and the jruby.jar in our standard distribution *without* shaded dependencies, so each of those libraries can be properly treated as a module.

I have a to-do on my list for getting jnr-* modularized. Perhaps we can collaborate there?

I guess the answer here is that we're open to ideas.

**Comment by headius** [comment]
Marking for 9.3... modularize or rename or do something with all remaining shaded dependencies.

**Comment by jeff5** [comment]
Jython doesn't add modules in the project Jigsaw sense. We're not talking about that kind of module, right?

The problem here seems to be that JRuby bundles unshaded things also published separately (and used by Jython). It's jnr-ffi for a start, but others are close behind, I predict (jnr-posix).

Shading them in JRuby would be a disappointing outcome because my objective was to remove the need for shading, not force others into it.

The answer I think is to have a "JRuby slim" that cites all its separately available dependencies as such. For Jython, I'd like the normal "jython.jar" to be the slim one eventually, and the jython executable be built with that as a dependency, and everything else transitively. We'd have version clashes where Jython slim and JRuby meet, but I believe that's a commonly solved problem.

**Comment by headius** [comment]
Oh I see, you weren't literally talking about modules in the JPMS/Jigsaw sense, you were talking about published maven artifacts. That's much simpler 👍 

Looping @enebo and @mkristian in here...

Adding a new artifact would be simple enough... jruby-slim or similar would unbundle/unshade everything. I don't recall now why we didn't do this to begin with, but I'm guessing we wanted jruby-core to at least be a fully-operational jar that could be paired with jruby-stdlib.

I think in practice, almost everyone that wants this goes straight to jruby-complete anyway.

**Comment by headius** [comment]
We discussed a bit on our [Matrix room](https://matrix.to/#/#jruby:matrix.org) and I think we are on board with adding a `jruby-base` artifact that contains just the sources from JRuby and no shaded dependencies.

Our maven rig is a little complicated, so this might take a bit of time... but we wouldn't be publishing this new artifact until the next release 9.3 anyway. Hopefully you or @mkristian can help us figure out a clean way to add this artifact into the project.

**Comment by ctrueden** [comment]
> you weren't literally talking about modules in the JPMS/Jigsaw sense, you were talking about published maven artifacts

Right, sorry. While I'm interested in JPMS modularization of all these libraries in the long term, I understand that's a ways off—it is for the components I maintain as well. I'll try to stop using the word "modules", to avoid confusion.

> I think we are on board with adding a jruby-base artifact that contains just the sources from JRuby and no shaded dependencies.

That would be super helpful! Thanks!

> I'm guessing we wanted jruby-core to at least be a fully-operational jar that could be paired with jruby-stdlib.

Just to make sure I understand correctly: assuming one uses Maven, would jruby-base not still be "fully functional" in the sense that the jruby-base JAR plus its dependencies work in downstream projects without additional work?

**Comment by mkristian** [comment]
@headius we can do this jruby-base maybe we need to find some other naming or not.

the shaded all is the lib/jruby.jar and we used this as maven artifact as well and use it for jruby-jars gems.

shading and not replacing (the packages) is also a problem with OSGi (so this seems to fade now in light of 'modules') as far I remember.

**Comment by ctrueden** [comment]
@mkristian Glad to hear this is doable.

> shading and not replacing (the packages)

Just to clarify terminology: my understanding is that "shading" means to _bundle additional __renamed__ packages into a fat/uber jar_, leading to the terms "shaded uber-jar" or "shaded fat jar". Whereas an "unshaded uber-jar" or "unshaded fat jar" is an artifact containing additional _not renamed_ packages. As things stand, `org.jruby:jruby-core` is a _mixed_ uber-jar, with some shaded and some unshaded packages. In particular, jnr-ffi is _unshaded_.

From my perspective, unshaded uber-jars are evil and should be avoided whenever possible—especially for reusable library components. Non-uber-jars are best, but if you need to bundle dependencies for some reason, at least shade them to avoid dependency conflicts.

**Comment by headius** [comment]
@mkristian When I was chatting with @enebo it seemed logical that we'd have this sort of relationship:

* jruby-base just contains JRuby's code
* jruby-core and the jruby-dist jar we use in lib would shade together jruby-base and the various dependencies. We may want to start relocating any of those dependencies that are internal and not expose through public APIs (we can't shade joda because it's part of RubyTime's public API for now).
* jruby-complete then combines jruby-core and jruby-stdlib.

So jruby-base is really just the "lost artifact" we have never gotten around to publishing.

As for naming... @enebo and I were both ok with "jruby-base". The related work on jython has produced a "jython-slim" but we felt like that might imply there's something faster or lighter-weight about it.

As for structure... I think it would be logical to make lib/jruby.jar be an artifact of the lib directory, which might mean we want to rename core/ but I'm not sure. My thinking is that core builds the jruby-base.jar (at first I typed "base jruby.jar which just shows that base is a pretty natural name) and then building lib constructs the shaded jar. I'm not sure how much renaming core/ would hurt us. I'm also not sure how important it is that we have the sources align EXACTLY with the artifacts.

@ctrueden Yeah shade has been overloaded to have two meanings, at least to me. The first is to "shade" your dependencies into an uberjar, as you describe. The other, which is really just a secondary feature of the shade plugin, is to **relocate** the packages those libraries bring in so that they don't conflict with any other versions of those libraries in the same JVM.

jruby-core does a bit of both. As you know, all the Java dependencies are shaded into the jar. At least one of them, the asm bytecode library, additionally gets relocated (to something like org.jruby.org.ow2.asm) since it's an extremely common library.

Part of the debate here will be whether we want to continue shading **and** relocating some packages to pretend they're just part of JRuby. My gut feeling is that **none** of our dependencies should be shaded into jruby-base this way, so we get the smallest possible jar file. A true "base" jar.

There will still need to be uberjars for the forseeable future (jruby-complete is by far the most popular JRuby Maven artifact), but we should take another look at whether the dependencies in jruby-core and jruby-complete should be relocated. That would avoid future users of those libraries having conflicts, but needs to be done with public APIs in mind.

**Comment by mkristian** [comment]
@headius of course I want to go the easy way and the above naming proposal is a bit against the easy way. the easy way would be to use
https://maven.apache.org/plugins/maven-shade-plugin/examples/attached-artifact.html
i.e. two parameters in the jruby/core/pom.rb and you have both the shaded one and the unshaded one. so jruby-core + jruby-core-shaded would be the easiest. lib/jruby.jar remains as is. jruby-complete.jar as well. jruby-jars gem I need to check.

any ways I have a look what is possible easy and not easy ;)

FYI my matrix username is `sintel` and I joined jruby there

**Comment by headius** [comment]
See #6233 which begins the process of making a `jruby-base` module that contains only JRuby code.

**Comment by headius** [comment]
This is taking a long way around, but JRuby 9.3 will publish a bare-bones "jruby-base" artifact that shades nothing. "jruby-core" will remain as it is today, shading ASM and libraries that depend on it, but we will consider it deprecated since it's a weird half-way shading that doesn't really gain us much. The future is "jruby-base" and "jruby-complete".
