### ISSUE TITLE
com.sun.javafx.collections not exported in javafx.base

### ISSUE THREAD

**Issue by GoldenWeiss** [jruby/jruby#6287]
.: Environment :.
jruby 9.2.11.1

.: Overview :.
It prevents access to the inherited methods of _ObservableMapWrapper_ in the jrubyfx DSL. Hence, the method add_change_listener throws an _Exception_ : 

TypeError: illegal access on 'addListener': class org.jruby.javasupport.JavaMethod cannot access class com.sun.javafx.collections.ObservableMapWrapper (in module javafx.base) because module javafx.base does not export com.sun.javafx.collections to unnamed module @abc0923
  add_change_listener at uri:classloader:/jrubyfx/core_ext/observable_value.rb:121

.: Reproduction :.
x =Java::javafx.collections.FXCollections.observable_map({})
x.addListener Java::javafx.collections.MapChangeListener.impl{|a,b| puts "z"}

.: Small patch by Headius :.
In run configurations, add the line : 
--add-exports javafx.base/com.sun.javafx.collections=ALL-UNNAMED

.: Note :.
observable_array_list.add_change_listener runs just fine, as it doesn't inherit from collections.

**Comment by headius** [comment]
The problem here is that `ObservableMapWrapper` is a public class, but in a non-exported package. Because it's public we proceed to set up its methods, assuming they and the class itself will be accessible. However when a class is not exported, accessing it directly this way triggers the error reported above.

We will also need to check whether a given class has been exported to the module JRuby is running as before binding its methods. If it has not been exported, we may try to export it, but failing that we should treat it the same way we treat private classes.

**Comment by headius** [comment]
Merged to master and 9.2.
