### ISSUE TITLE
IRReturnJump when returning from a proc returned by a lambda

### ISSUE THREAD

**Issue by eregon** [jruby/jruby#6350]
**Environment Information**
  
Provide at least:
* JRuby version: `jruby 9.2.13.0 (2.5.7)`

**Expected Behavior**

```
$ ruby -e 'b=-> { Proc.new { return 42 }; }.call; p b; p b.call'
#<Proc:0x00005584560614b0 -e:1>
```

**Actual Behavior**

```
$ jruby -e 'b=-> { Proc.new { return 42 }; }.call; p b; p b.call'
#<Proc:0xeafc191@-e:1>
Unhandled Java exception: IRReturnJump:<Static Type[1957502751]: block []
  Static Type[1780132728]: local [b=#<Proc:0xeafc191@-e:1>]:42>
org.jruby.ir.runtime.IRReturnJump: null
```

Might relate to #1134.

**Comment by eregon** [comment]
Also happens for:
```ruby
def m
  b = -> { Proc.new { return 42 } }.call
  b.call # returns from the method
  p :after # never reached!
end

p m
```

```
MRI:
42

JRuby 9.2.13.0:
Unhandled Java exception: IRReturnJump:<Static Type[1226622409]: block []
  Static Type[1957502751]: local [b=#<Proc:0x462d5aee@-:2>]:42>
org.jruby.ir.runtime.IRReturnJump: null
```

FYI The example is from https://github.com/oracle/truffleruby/issues/1488 where we try to figure out what are the semantics of `return` inside a proc inside a lambda inside a method.

**Comment by headius** [comment]
Backtrace for flow-control jumps is available with `-Xjump.backrace`:

```
$ jruby -J$JAVADEBUG -Xjump.backtrace -e 'b=-> { Proc.new { return 42 }; }.call; p b; p b.call'
#<Proc:0x6bb7cce7@-e:1>
Unhandled Java exception: IRReturnJump:<Static Type[1800605369]: block []
  Static Type[847606512]: local [b=#<Proc:0x6bb7cce7@-e:1>]:42>
org.jruby.ir.runtime.IRReturnJump: null
                  create at org/jruby/ir/runtime/IRReturnJump.java:20
  initiateNonLocalReturn at org/jruby/ir/runtime/IRRuntimeHelpers.java:171
                  <main> at -e:1
              callDirect at org/jruby/runtime/CompiledIRBlockBody.java:141
                    call at org/jruby/runtime/IRBlockBody.java:64
                    call at org/jruby/runtime/Block.java:143
                    call at org/jruby/RubyProc.java:283
                    call at org/jruby/RubyProc$INVOKER$i$call.gen:-1
                    call at org/jruby/internal/runtime/methods/JavaMethod.java:327
            cacheAndCall at org/jruby/runtime/callsite/CachingCallSite.java:354
                    call at org/jruby/runtime/callsite/CachingCallSite.java:143
       invokeOther3:call at -e:1
                  <main> at -e:1
                     run at -e:-1
     invokeWithArguments at java/lang/invoke/MethodHandle.java:710
                    load at org/jruby/ir/Compiler.java:114
               runScript at org/jruby/Ruby.java:1257
             runNormally at org/jruby/Ruby.java:1176
             runNormally at org/jruby/Ruby.java:1158
             runNormally at org/jruby/Ruby.java:1194
             runFromMain at org/jruby/Ruby.java:977
           doRunFromMain at org/jruby/Main.java:393
             internalRun at org/jruby/Main.java:287
                     run at org/jruby/Main.java:234
                    main at org/jruby/Main.java:206
```

I believe both of these cases should be LocalJumpError. The bug is that we are not detecting the lambda scope when determining where to return to.

The logic to generate the return jump exception detects the intervening lambda frame and sets that as the target for the jump. This is correct behavior; because the proc was created within a lambda, its return should be from the lambda level.

The subsequent logic that unrolls the stack should raise either an IRReturnJump (if the target frame is active) or a Ruby LocalJumpError (if the target frame is no longer active). Unfortunately this logic skips over the lambda and instead finds the top-level (in the top-level example) or the method (in the method example). In both cases they are still on active.

As a result, we raise an IRReturnJump, expecting it to be handled as a normal non-local return, when we should be raising a LocalJumpError.

I see from oracle/truffleruby#1488 there is some abiguity in the CRuby behavior. I would consider that behavior to be incorrect; once the proc has escaped from the lambda, its return target is no longer valid. It should not return to a different place. This is likely only effective in CRuby because of their messy handling of these jumps... there happens to be someone ready to handle any old return jump, so it just happens to work.

With a simple patch in JRuby, we get the behavior I think is correct for both cases:

```
$ jruby -Xjump.backtrace -e 'b=-> { Proc.new { return 42 }; }.call; p b; p b.call'
#<Proc:0x47747fb9@-e:1>
LocalJumpError: unexpected return
  <main> at -e:1
  <main> at -e:1

$ jruby -Xjump.backtrace -e 'def foo; b=-> { Proc.new { return 42 }; }.call; p b; p b.call; 42; end; p foo'
#<Proc:0x47747fb9@-e:1>
LocalJumpError: unexpected return
     foo at -e:1
     foo at -e:1
  <main> at -e:1
```

I will push a PR to see how it lands.

**Comment by eregon** [comment]
> I see from [oracle/truffleruby#1488](https://github.com/oracle/truffleruby/issues/1488) there is some abiguity in the CRuby behavior. I would consider that behavior to be incorrect; once the proc has escaped from the lambda, its return target is no longer valid. It should not return to a different place. This is likely only effective in CRuby because of their messy handling of these jumps... there happens to be someone ready to handle any old return jump, so it just happens to work.

I agree the semantics seem confusing and potentially unintentional here.
I filed https://bugs.ruby-lang.org/issues/17105

**Comment by headius** [comment]
Given that we have Shyouhei on our side I think it's likely that the behavior we want will be considered the right behavior. I've merged the JRuby fix that makes both cases LJE.

**Comment by headius** [comment]
Matz has approved the error condition described above, which @ko1 has a patch for in https://github.com/ruby/ruby/pull/4347.

Nothing for us to do since we have already made this change for 9.3.
