### ISSUE TITLE
Java::JavaLang::NullPointerException () --> JRuby 9.2.13.0 on Windows 10

### ISSUE THREAD

**Issue by mistergibson** [jruby/jruby#6440]
JRuby 9.2.13.0
JRUBY_OPTS="-X+O" (yes, I know)
Windows 10

require 'sys-cpu'
Sys::CPU.processors()

**Expected Behavior**
A list of local system processors

**Actual Behavior**
Sys::CPU.processors
Traceback (most recent call last):
16: from org.jruby.ext.win32ole.RubyWIN32OLE$INVOKER$i$0$0$each.call(RubyWIN32OLE$INVOKER$i$0$0$each.gen)
15: from org.jruby.ext.win32ole.RubyWIN32OLE.each(RubyWIN32OLE.java:66)
14: from org.jruby.runtime.Block.yield(Block.java:184)
13: from org.jruby.runtime.BlockBody.yield(BlockBody.java:108)
12: from org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:166)
11: from org.jruby.runtime.MixedModeIRBlockBody.commonYieldPath(MixedModeIRBlockBody.java:137)
10: from org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:116)
9: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
8: from org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
7: from org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:172)
6: from org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
5: from org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:143)
4: from org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:156)
3: from org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
2: from org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:83)
1: from org.jruby.ir.instructions.BSwitchInstr.interpretAndGetNewIPC(BSwitchInstr.java:99)
Java::JavaLang::NullPointerException ()

I suspect this is a JRuby bug, but just to be safe I also filed a bug report with the gem author here : https://github.com/djberg96/sys-cpu/issues/11

Let me know if you need additional information.

**Comment by headius** [comment]
In https://github.com/djberg96/sys-cpu/issues/11#issuecomment-713590907 @djberg96 narrowed this down to a simple script:

```ruby
# case_test.rb
def stuff(arg = nil)
  case
  when 0
    puts "zero"
  when 1
    puts "one"
  else
    puts "oops"
  end
end

stuff
```

We are not handling a bare `case` statement correctly (probably for a long time).

**Comment by headius** [comment]
Actual stack trace for the example from @djberg96:

```
Unhandled Java exception: java.lang.NullPointerException
java.lang.NullPointerException: null
  interpretAndGetNewIPC at org/jruby/ir/instructions/BSwitchInstr.java:99
              interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:83
              interpret at org/jruby/ir/interpreter/InterpreterEngine.java:80
       INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:121
```

**Comment by headius** [comment]
The issue here is that we are turning the case statement into an optimized Java `switch`, but not checking that there's actually a case value to compare with. As a result the optimized case logic blindly tries to evaluate the null case value and raises NPE.

This probably has been broken since we introduced the switch-based "BSwitchInsn" in 9.1.3.0: https://github.com/jruby/jruby/commit/8acfb77952430b4135702b83a795aed9f5494a15.

Note it only affects cases that have all Fixnum `when` values and omitted `case` value.

**Comment by headius** [comment]
FTR: optimized switch only works in JRuby when we have a `case` value and all the `when` values are integer-ranged numeric literals, since that's what the Java `switch` supports. When a `case` has no value, the `when` values are just evaluated until one of them is true.

For the example case, a peephole optimization would be to only compile in the first true `when` body since that's the only one that will ever fire. I leave that as an exercise for the reader, since this is a pretty weird and useless `case`.
