### ISSUE TITLE
StringIO#seek uses 32-Bit file offsets on 64-Bit arch

### ISSUE THREAD

**Issue by felixbuenemann** [jruby/jruby#6459]
While file offsets are 64-Bit, `StringIO` is still limited to 32-Bit on JRuby 9.2.9.0.

```ruby
s = StringIO.new
s.seek(2**31-1)
=> 0
s.seek(2**31)
RangeError (integer 2147483648 too big to convert to `int')
```

Related to #3817 which fixed this for `File`.

**Comment by felixbuenemann** [comment]
For comparison on MRI 2.7.2:

```ruby
2.7.2 :006 > s.seek(2**63-1)
 => 0
2.7.2 :007 > s.seek(2**63)
RangeError (bignum too big to convert into `long')
```

**Comment by headius** [comment]
This is a bit problematic to fix in StringIO because Java does not provide a way for us to address into a byte array (such as that contained in the String that backs up the StringIO) using anything larger than a 32-bit signed integer value. When seeking external IO we do not have the same limitation.

Did you run into this in a real-world library or application? In order for you to need this, you'd have to have an in-memory StringIO buffer larger than 2GB.

**Comment by felixbuenemann** [comment]
It caused a problem in the zip_tricks gem specs when simulating zip64 which does a seek beyond the max int32 offset. For now I fixed it by recovering from RangeError, which should be done for MRI as well, but at int64 boundary, so I fixed a bug as a side effect…

**Comment by felixbuenemann** [comment]
I think it is fine to close this issue, since I don't see a reasonable fix given the underlying string cannot exceed int32 size.

**Comment by headius** [comment]
Not worth the effort to implement this, given the JVM limitation of int32-sized arrays and array offsets.

If someone wanted to spike a proof-of-concept for this using multiple arrays or some other trickery, we can talk.
