### ISSUE TITLE
 WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem

### ISSUE THREAD

**Issue by gshields** [jruby/jruby#6475]
>irb
2020-11-21T12:02:38.345-08:00 [main] WARN FilenoUtil : Native subprocess control requires open access to the JDK IO subsystem
Pass '--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist' to enable.
irb(main):001:0>

C:\Users\ghs>jruby --version
jruby 9.2.13.0 (2.5.7) 2020-08-03 9a89c94bcc OpenJDK 64-Bit Server VM 15.0.1+9-18 on 15.0.1+9-18 +jit [mswin32-x86_64]
 on windows 10 ver 20H2

-->

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc)
* Operating system and platform (e.g. `uname -a`)

Other relevant info you may wish to add:
* Installed or activated gems
* Application/framework version (e.g. Rails, Sinatra)
* Environment variables

**Expected Behavior**

* Describe your expectation of how JRuby should behave, perhaps by showing how CRuby/MRI behaves.
* Provide an executable Ruby script or a link to an example repository.

**Actual Behavior**

* Describe or show the actual behavior.
* Provide text or screen capture showing the behavior.

**Comment by headius** [comment]
This is likely due to the launcher not being updated on Windows recently. That has other issues filed for it but I don't remember the issue numbers offhand.

You can avoid this warning by adding those flags to the JAVA_OPTS environment variable, either in the system settings or at a command line like this:

```
set JAVA_OPTS="--add-opens java.base/sun.nio.ch=org.jruby.dist --add-opens java.base/java.io=org.jruby.dist"
```

We will get a new JRuby release out soon with an updated jruby.exe launcher. cc @enebo

**Comment by enebo** [comment]
This is fixed with new jruby launcher build.

**Comment by rdp** [comment]
For followers, unless you set these values you will get really wonky/wrong PID values for child processes...

and get wonky stuff trying to send them signals etc:

`No such process - No message available Stop`  `Errno::ESRCH: No such process - No message available` 'Exception in thread "Ruby-0-Thread-1: record_with_buttons.rb:218" java.lang.NullPointerException: Cannot invoke "org.jruby.runtime.ThreadContext.getThread()" because "this.mainContext" is null'

But works fine with those values set, thanks! :)

https://github.com/jruby/jruby/issues/5642
