### ISSUE TITLE
Unexpected ArgumentError when calling method and splatting empty hash

### ISSUE THREAD

**Issue by ivoanjo** [jruby/jruby#6564]
Hello there!

While investigating a CI failure related to the newest version of the sucker_punch gem in as part of DataDog/dd-trace-rb#1369 I spotted two behavior differences between MRI and JRuby (as well as TruffleRuby, I've filed oracle/truffleruby#2260 with them -- the tickets are quite similar)

### Testcase 1:

```ruby
puts RUBY_DESCRIPTION
kwargs = {}
def foo
end
foo(**kwargs)
puts "Works!"
```

Behavior with JRuby:

```
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 25.275-b01 on 1.8.0_275-b01 [darwin-x86_64]
ArgumentError: wrong number of arguments (given 1, expected 0)
     foo at splat-bug-1.rb:5
  <main> at splat-bug-1.rb:5
```

Behavior with MRI:

```
$ ruby splat-bug-1.rb
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
splat-bug-1.rb:3:in `foo': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from splat-bug-1.rb:5:in `<main>'
$ ruby splat-bug-1.rb
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Works!
$ ruby splat-bug-1.rb
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
Works!
```

For the life of me, I cannot find any references to a change in behavior in 2.5 for this, so perhaps it was a side-effect of some fix, rather than something deliberate.

### Testcase 2:

As a bonus, while trying to create a reduced test case for the issue, I found a second behavior that also differs in JRuby, but that seems to have been changed back in MRI 2.2:

```ruby
puts RUBY_DESCRIPTION
def foo; end
foo(**{})
puts "Works!"
```

Behavior with JRuby:

```
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 25.275-b01 on 1.8.0_275-b01 [darwin-x86_64]
ArgumentError: wrong number of arguments (given 1, expected 0)
     foo at splat-bug-2.rb:3
  <main> at splat-bug-2.rb:3
```

Behavior with MRI:

```
$ ruby splat-bug-2.rb
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-darwin19.0]
splat-bug-2.rb:2:in `foo': wrong number of arguments (1 for 0) (ArgumentError)
	from splat-bug-2.rb:3:in `<main>'
$ ruby splat-bug-2.rb
ruby 2.2.10p489 (2018-03-28 revision 63023) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.3.8p459 (2018-10-18 revision 65136) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-darwin19]
Works!
$ ruby splat-bug-2.rb
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin19]
Works!
```

**Comment by headius** [comment]
Both errors occur on master as well.

It is unclear from the TR issue whether they will be fixing something or not. We would consider this a bug but if suckerpunch is updated to do this delegation right it doesn't require an immediate fix.

As with TR, we will be doing 3.0 support soon which will rework how keyword arguments are handled.

**Comment by enebo** [comment]
Ok this bug is going to be yucky...

Our design passes in an explicit argument for the hash and is built to pass that explicit argument to a callInstr.  At that point all knowledge that single argument came from a kwarg hash is gone.

A few paths to consider:
  1. Making kwargs an out of band argument type.  I have always wanted to pass this separate from the other arguments as it would simplify everything in our internals.  There is some complexity with old school notion that last arg as hash may actually be a kwarg hash but for cases we know it feels like we should move that arg to its own param(s) vs what is my last argument again?
  2. Emit conditional logic to use appropriate call (e.g. one path is no args and one path is one arg) if we detect empty kwargs hash.  This may be easiest to do short term but it is pretty unappealing.  It is reasonable as a stop-gap for any other more invasive solution.
  3. Make calls aware that they are receiving kwargs from the site.  In some respects this is congruent with 1 it would just not be passing that argument as a special one but we would not that the last arg is special.

The reported issue uses **{} but this could literally be anything coming from anywhere **some_thing_from_somewhere.  The key is that we know at the site we are passing a kwargrest.  We need to leverage that knowledge.  Above #2 creates extra code for kwrest but it allows the site to fix up the call.  #1 and #3 will be much more invasive but in the long run knowing we have kwargs gives benefits beyond fixing this bug.  Processing arguments knowing for sure the last one is a valid hash means not checking it.  Or in more interesting future we know we will be passing kwargs we can destructure and pass them as positional arguments in some "scheme" to avoid all the hash processing.

**Comment by enebo** [comment]
Update on this issue getting ickier...

Consider these two definitions:
```ruby
def foo
  puts "OH YEAH"
end

a = {}
foo(**a)
foo(**{}, **{})

def bar(a)
  p a
end

a = {}
bar(**a)
bar(**{}, **{})
```

Both calls to foo work and the arguments at the callsite will end up as the keyword argument value and as foo does not consume them everything works (in C Ruby 2.6 anyways).  Now if we look at bar we have the same calls to it but the first call works as we are passing a hash and it expects a single argument.  We just pass that hash.  The second call fails as it sees two expansions and this somehow makes it appear to be a kwargs call?  So weird but so weird that although it behaves this way in 2.6 in Ruby 3.0 neither pass.

At this point I think although JRuby 9.3 will be 2.6.x compatiable I am thinking we should just follow Ruby 3.0 here.  The 2.6 behavior where it accepts the first bar will not work but since it work in 3.0 then I think we are safe just adopting the newer behavior.  The other justification here is that if the first call to bar works there is no actual reason I can think of why the second call shouldn't work?

Until I discovered this behavior I was dashed because it meant that option 2 could not even be a stop-gap solution.  Ruby 3 semantics has re-opened the notion that we can emit callsite params independently of what method it happens to hit.  This is a great thing since a callsite can potentially be calling completely different methods each time it is activated.
