### ISSUE TITLE
NotImplementedError in solaris10

### ISSUE THREAD

**Issue by tod-yangyd** [jruby/jruby#6710]
I found that jruby had incompatible problems running on solaris 10. I've seen people find solutions to the same problems as ubuntu, but they don't apply to the solaris version. The error is shown below.

**Environment Information** 
```
bash-3.00$ uname -a
SunOS mesttux2 5.10 Generic_142909-17 sun4u sparc SUNW,Sun-Fire-V440
bash-3.00$ jruby -v
jruby 9.2.7.0 (2.5.3) 2019-04-09 8a269e3 Java HotSpot(TM) 64-Bit Server VM 25.291-b10 on 1.8.0_291-b10 +jit [solaris-sparcv9]
```

**Expected Behavior**
```
bash-3.00$ jruby -e "puts File.stat('/').dev_minor"
NotImplementedError: stat.st_dev unsupported or native support failed to load; see http://wiki.jruby.org/Native-Libraries
  dev_minor at org/jruby/RubyFileStat.java:254
     <main> at -e:1
```

**Comment by ahorek** [comment]
unfortunately, ```sparcv9``` platform isn't supported

could you help us to add missing bits, since you have access to the platform?

we need a new variant for sparcv9
https://github.com/jnr/jnr-posix/blob/master/src/main/java/jnr/posix/SolarisPOSIX.java#L21
take a look at Linux variant for inspiration
https://github.com/jnr/jnr-posix/blob/master/src/main/java/jnr/posix/LinuxPOSIX.java#L47

and constants should be also generated
https://github.com/jnr/jnr-constants

**Comment by tod-yangyd** [comment]
Although I have access to this version of Solaris, but I'm sorry,  I can't help you with add missing bits because I'm not good at development.....T_T
If there is anything else I can help, please let me know...
Thank you for your answer!

**Comment by ahorek** [comment]
feel free to ask on https://app.element.io/#/room/#jruby:matrix.org for guidance

it shouldn't be hard to support it. Does CRuby work?
could you clone https://github.com/jnr/jnr-constants  run ```rake generate:platform``` and send us the generated file?

**Comment by headius** [comment]
@tod-yangyd Is this actually fixed in current JRuby, or did you just close it because it's stale?
