### ISSUE TITLE
JRuby issue with Installer EXE file

### ISSUE THREAD

**Issue by ozdeadmeat** [jruby/jruby#6750]
**Environment Information**
  
Windows 10 x64
Running from Powershell 5.x (happens from CMD.exe also)

To repeat

Download JRuby 9.2.19.0 Windows Executable (x64) 
open admin powershell or commandline.
Execute application with /?

CMD - **jruby_windows_x64_9_2_19_0.exe /?**
PowerShell - .\jruby_windows_x64_9_2_19_0.exe /?

**Expected Behavior**

Actual detail on installer switches

**Actual Behavior**

html format code

**Comment by enebo** [comment]
This is using a commercial product install4j.  I will look to see if perhaps there is the ability to toggle '/?' as a valid help option but if not then we are stuck without evaluating another installer product.

**Comment by mohits** [comment]
As a workaround, you can do:

```
$ jruby_windows_x64_9_2_19_0.exe -c -h
$ The following command line options are available:

-varfile [file]  Use a response file
-c               Run in console mode
-q               Run in unattended mode
-dir [directory] In unattended mode, set the installation directory
-overwrite       In unattended mode, overwrite all files
-splash [title]  In unattended mode, show a progress window
-console         In unattended mode, open a console that shows the output
-manual          Manually select a Java runtime environment in GUI mode
-Dname=value     Set system properties
-h               Show this help
```

Using '-c' forces it into console mode. The default for -h is to output in the GUI irrespective of the installer mode. The fact that it shows an HTML table is probably an error in the installer. The options are here: https://www.ej-technologies.com/resources/install4j/help/doc/installers/options.html

Hope this helps.

**Comment by enebo** [comment]
@mohits thanks for this.  I see it says /? should work so I will make sure I have latest version of the installer installer installed :)

**Comment by mohits** [comment]
@enebo - happy to help on things I can find easily by searching or following a lead. I didn't try /? but I expect it will also work. The main point to answer the original concern is just the -c which outputs to the console since -h will *always* default to the pop-up according to that page.

**Comment by headius** [comment]
Oh Windows, you so silly. 🤪

**Comment by enebo** [comment]
Speculatively fixed with 1f47c535b8b.  I updated us from install4j7 to install4j9.  This will still need to be tested but it should do the trick.  I moved this back to jruby-9.2 as well.

**Comment by rubyFeedback** [comment]
headius wrote:

> Oh Windows, you so silly.

Quite true! I have been using Linux since almost 20 years; it's "second nature" to me in many ways. When I use windows I always wonder how people can work on it (speaking of cmd.exe for instance). I also use WSL1 on windows so things have gotten better over the years.

I have been using ruby since close to 15 years so naturally I use it on windows as well. I also started using java since ~2 years; still more a noob than anything in java, but the promise to be able to access ruby, and vice versa (access java libraries) is a good reason to use it. And while on linux I don't really need java per se as much, on windows being quite annoying, java is actually quite useful. I find it easier to deal with java than C or C++. (I need to work with windows for various reasons actually; one are elderly people who aren't computer savvy so they need all the help they can get.)

So as annoying as windows is, the better java/jruby support can be, the better for tons of "downstream" users, IMO!

**Comment by mohits** [comment]
I use Windows the most in my day-to-day life and am continuously thankful to people who have worked hard to make things work well there. JRuby and CRuby (using RubyInstaller2) work perfectly well on Windows, including native extensions as applicable. Where things fail, it's often because people don't work on Windows and therefore didn't build/ test on it, or people who assumed that there was no way it would work on Windows - so, they didn't bother.

I do try to highlight where I find that and hope to help people who face problems running things on Windows, especially in Ruby/ JRuby and will be happy to help if I can. Specially, for RubyOnWindows, this is my current effort: https://notepad.onghu.com/tags/#RubyOnWindows and hope to continue to add more.

But, we digress :-)

**Comment by enebo** [comment]
Confirm this new installer seems to no longer have the issue reported
