### ISSUE TITLE
stacktrace first line erroneously reports line number. Reports duplicate line # as second line of stacktrace.

### ISSUE THREAD

**Issue by SeanFelipe** [jruby/jruby#6768]
JRuby 9.2.17.0
OSX 11.3.1

It appears that when I get an error with stacktrace, the first and second lines report the same line number. The second line number is correct, but the first is incorrect and just a duplication of the second line.

For example, my stacktrace looks like this:

```
Exception in thread "LWJGL Application" org.jruby.exceptions.ArgumentError: (ArgumentError) wrong number of arguments (given 0, expected 1)
	at RUBY.set_speed(/Users/felipe/scratchpad/stacktrace-jruby-26N1/src/fsprites.rb:118)
	at RUBY.throw_and_run(/Users/felipe/scratchpad/stacktrace-jruby-26N1/src/animator.rb:118)
	at RUBY.process_keydown(/Users/felipe/scratchpad/stacktrace-jruby-26N1/src/mux.rb:49)
	at RUBY.keyDown(/Users/felipe/scratchpad/stacktrace-jruby-26N1/src/mux.rb:35)
```

You can see that line 118 appears in the first and second files. However the first file is actually failing on line 165 in this example.

Full code with reproducible error is here:
https://github.com/SeanFelipe/Jruby-potential-bug-stacktrace-reporting-summer-2021

There is a readme in that repo with steps to reproduce.

**Comment by headius** [comment]
Thank you for the report!

There are some known issues with ArgumentError while calling code that has been compiled. Because we do the argument size check *before* we enter the actual compiled method body, it can be missing a stack trace element. But this appears to be combining a filename from one element with a line number from another.

**Comment by headius** [comment]
Related, similar issues: #5103, #6335.

**Comment by headius** [comment]
Based on your example, I think I have come up with a fairly minimal reproduction:

```
def foo(a)
  p a
end

def bar
  foo
end

th = java.lang.Thread.new do
  bar
end

th.start

th.join
```

The resulting stack trace is similar to yours, with the second-to-highest line number used in the highest trace element.

```
$ jruby -X-C blah.rb
Exception in thread "Thread-0" org.jruby.exceptions.ArgumentError: (ArgumentError) wrong number of arguments (given 0, expected 1)
	at RUBY.foo(blah.rb:6)
	at RUBY.bar(blah.rb:6)
	at RUBY.<main>(blah.rb:10)
```

We disable JIT here to duplicate the example in your case, because when JIT has compiled this code (either by running the script directly or by forcing methods to JIT immediately) that half-right trace element disappears as described in #5103.

```
$ jruby blah.rb
Exception in thread "Thread-0" org.jruby.exceptions.ArgumentError: (ArgumentError) wrong number of arguments (given 0, expected 1)
	at blah.bar(blah.rb:6)
	at blah.<main>(blah.rb:10)

$ jruby -Xjit.threshold=0 -e 'load "./blah.rb"'
Exception in thread "Thread-0" org.jruby.exceptions.ArgumentError: (ArgumentError) wrong number of arguments (given 0, expected 1)
	at Users.headius.projects.jruby.blah.bar(/Users/headius/projects/jruby/blah.rb:6)
	at RUBY.<main>(/Users/headius/projects/jruby/blah.rb:10)
```

The trace you see here is the one delivered to Java by post-processing the Ruby backtrace, which itself is generated by post-processing the native Java stack trace (we do this to remove JRuby internal lines and replace interpreter lines with the proper stack frame info). In the JIT case, because we do the arity check before calling the method body, the method itself does not show up in either the Ruby or Java stack traces. However the interpreter *does* enter the method before doing the arity check, which results in us pushing an artificial stack trace to use for the replacement described earlier.

The JIT issue has been around for a long time and we have other issues to track it, so I won't try to fix that here. However the interpreter issue is probably a simple bug in how it handles pushing the backtrace information. I suspect it pushes only the filename and doesn't update the line number until after it has checked the arity (and as a result, the error has the new file with the old line).

**Comment by headius** [comment]
Indeed, the Java thread is not even necessary to reproduce... just run this script with the interpreter only:

```ruby
def foo(a)
  p a
end

def bar
  foo
end

bar
```

And the result:

```
$ jruby -X-C blah.rb
ArgumentError: wrong number of arguments (given 0, expected 1)
     foo at blah.rb:6
     bar at blah.rb:6
  <main> at blah.rb:9
```

**Comment by headius** [comment]
I believe the problem lies here:

https://github.com/jruby/jruby/blob/e51ce3042fa489a667f9c341edb0ee2f255cabb9/core/src/main/java/org/jruby/internal/runtime/methods/InterpretedIRMethod.java#L124

This line pushes a backtrace element before calling the interpreter, using the called method name, the filename of the scope to be interpreted, but the **current** line number on the stack, which would from be the caller's stack frame.

**Comment by headius** [comment]
I have a fix for the JIT issues as well, FWIW.

```
$ jruby `pwd`/blah.rb
ArgumentError: wrong number of arguments (given 0, expected 1)
     foo at /Users/headius/projects/jruby-9.2/blah.rb:1
     bar at /Users/headius/projects/jruby-9.2/blah.rb:6
  <main> at /Users/headius/projects/jruby-9.2/blah.rb:9

$ jruby -Xjit.threshold=0 -e 'load "./blah.rb"'
ArgumentError: wrong number of arguments (given 0, expected 1)
     foo at /Users/headius/projects/jruby-9.2/blah.rb:1
     bar at /Users/headius/projects/jruby-9.2/blah.rb:6
  <main> at /Users/headius/projects/jruby-9.2/blah.rb:9
    load at org/jruby/RubyKernel.java:1009
  <main> at -e:1
```

**Comment by SeanFelipe** [comment]
Awesome :) Thanks :)

**Comment by headius** [comment]
@SeanFelipe Thank you for reporting it! Led me to fix other cases as well, so future releases will have more accurate traces.
