### ISSUE TITLE
ThreadsWait ignoring `report_on_exception = false`

### ISSUE THREAD

**Issue by NC-piercej** [jruby/jruby#6897]
**Environment Information**
  
* JRuby version: 9.3.1.0
* Operating system and platform: Linux 9a933b6ff814 5.10.47-linuxkit #1 SMP Sat Jul 3 21:51:47 UTC 2021 x86_64 GNU/Linux

**Example**

```
require 'thwait'

thread = Thread.new do
   Thread.current.report_on_exception = false
   raise "whoops"
end

ThreadsWait.all_waits(thread)
```

**Expected Behavior**

No `report_on_exception` warning is raised.

**Actual Behavior**

We get an unexpected log like:

```
warning: thread "Ruby-0-Thread-2: /opt/jruby/lib/ruby/stdlib/thwait.rb:91" terminated with exception (report_on_exception is true):
RuntimeError: whoops
  evaluate_ruby at (pry):1
```

**NOTE:**

Seems like there are plans to not include `thwait` by default to match Ruby 2.7 behavior: https://github.com/jruby/jruby/issues/6464

We probably want this fixed for the JRuby version of them, however.

**Comment by ahorek** [comment]
aha, it was a bug in the library https://bugs.ruby-lang.org/issues/15644

jruby 9.3 still targets 2.6.x compatibility and it was shipped with the previous version 0.1.0 (before the fix) https://github.com/ruby/ruby/blob/ruby_2_6/lib/thwait/version.rb

since 2.7.x ```thwait``` is no longer part of the stdlib. So I think this issue can be closed.
