### ISSUE TITLE
Prepending-including module precedence changed between jruby versions

### ISSUE THREAD

**Issue by mrhardikjoshi** [jruby/jruby#6971]
**Environment Information**
   Found different behaviour between `jruby 9.3.2.0` and `jruby 9.2.20.1`.
   
   When following script is run with `jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905` it calls `BaseModule`'s method. But when same script is run with `jruby 9.2.20.1 (2.5.8) 2021-11-30 2a2962fbd1` it calls `PrependingModule`'s method.

```   
module BaseModule
  def my_method
    puts "in BaseModule module"
  end
end

class Test
  include BaseModule

  def check
    my_method
  end
end

module PrependingModule
  def my_method
    puts "in PrependingModule module"
  end
end
BaseModule.prepend PrependingModule


Test.new.check
```

**Expected Behavior**

* Behaviour should be same between these two jruby versions.
* Not sure which one is correct but I think the prepending module should take priority over the other module 

**Actual Behavior**

* Both these jruby versions behaves differently. (I also checked with using jruby-9.2.16.0 and it still behaves differently than `jruby 9.2.20.1`)

**Comment by mohits** [comment]
To add to the information here, I used the code above to run it with different versions of Ruby/ JRuby (all on Windows) that I have. Results below (if it helps)

```$ ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [x64-mingw32]

$ ruby prepend.rb
in BaseModule module

$ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x64-mingw32]
$ ruby prepend.rb
in BaseModule module

$ ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
$ ruby prepend.rb
in PrependingModule module

$ jruby -v
jruby 9.2.18.0 (2.5.8) 2021-06-08 d67cb7d6e0 OpenJDK 64-Bit Server VM 25.265-b01 on 1.8.0_265-b01 +jit [mswin32-x86_64]
$ jruby prepend.rb
in PrependingModule module
```

**Comment by klobuczek** [comment]
@mohits you are right. I could not believe my eyes seeing the vast discrepancy.
Let's describe the issue better which is about:
**prepending to a module after that module has already been included** (in a class for example)
The above snippet works as expected on any ruby if the line containing `prepend` appears before the line containing `include`.

The prepending after inclusion is ineffective on MRI version before 3..0.0 and effective thereafter.
In the contrary, the prepending is effective on any jRuby version before 9.3.0.0 and ineffective after.

This is very frustrating even if jruby 9.3.x.x seem to be consistent with MRI 2.6.x, but on the other hand, 9.2.0.0 was not consistent with 2.5.x.
Not sure if this part of any spec. But if it were up to me I would very much prefer that such a prepending were always effective.

**Comment by mohits** [comment]
Hi @klobuczek - it really is a find by @mrhardikjoshi not me. I just did the extra leg-work to provide data to the already overloaded team in case they wanted to know how it works on CRuby which should carries the "burden of correctness" specs notwithstanding.

There does seem to be a switch in the CRuby implementation between 2.x and 3.0 based on the sample code and I think as 9.4 heads towards Ruby 3.x compatibility it is really important to close the gap.

**Comment by enebo** [comment]
In MRI 3.0+ all prepends/includes are tracked and when something is later included/prepended it will update all other uses so they all see the same thing.  Before that it was dependent on order of execution.  Earlier includes/prepends would not see later additions.  I am not sure how much libraries depends on that behavior but these methods have had this behavior since their inception.  As such it is difficult to just update to 3.0 behavior for 2.6 compatible Ruby (likely this difference will matter less and less as all libraries will work with 3.0 as well but there is a lot of unmaintained yet still used gems out there).

For JRuby 9.2 we had a prepend which obviously had issues.  When they were reported we fixed it on 9.3.x (which is just inherited its code from 9.2)  but did not backport to 9.2 since it is on version 21 and it felt risky (we are risk averse on any 9.2 fixes to try and focus on stability).  9.3 is new enough where we still fix anything.   9.3 hopefully is behaving like 2.6 now.  I would not be surprised if there is some combo of prepend + refinements which is broken in some way but these features are pretty tricky.

**Comment by enebo** [comment]
I should add that 9.2 appears to be doing what Ruby 3.0 does but it is deficient in other ways.  It is not tracking sites.  It is pointing at the wrong method location and just happens to look like it is working the same as Ruby 3.0.  You should assume ordered inclusion like all other Ruby's for 9.2 even if it doesn't act like it.

**Comment by enebo** [comment]
This is a WONTFIX for 9.2.x due to how complicated the changes are with respect to the risks that far out in the release cycle.
This is working the same as MRI 2.6.x on JRuby 9.3.x.  So I am resolving as WONTFIX.

I know this may suck a little bit but the 9.2 support is largely for non-risky and security fixes at this point (as well as the human resource aspect of maintaining multiple releases).

If people want to talk about this you can re-open the issue or come over to our matrix chat.
