### ISSUE TITLE
Possible memory leak from `instance_eval` with jruby 9.3

### ISSUE THREAD

**Issue by cbeer** [jruby/jruby#6993]
**Environment Information**
  
jruby 9.3.2.0 (2.6.8) 2021-12-01 0b8223f905 OpenJDK 64-Bit Server VM 17.0.1+1 on 17.0.1+1 +jit [darwin-x86_64]

**Expected Behavior**

This is a simplified demonstration of an issue I ran into updating from jruby 9.2 to 9.3. Running our application's test suite under 9.3, we saw memory usage go from ~500MB to blowing the stack around 8GB. I was able to track it down to a couple culprits, but one of the biggest changes seems to come from calls to `instance_eval`, e.g.:

```
require 'java'
java_import 'java.lang.System'
import java.lang.management.ManagementFactory
mbean = ManagementFactory.getMemoryMXBean

Object.new.tap { |a| a.instance_eval('') }

System.gc
puts "A: #{mbean.getHeapMemoryUsage.used}"

50_000.times do |index|
Object.new.tap { |a| a.instance_eval('') }
end

System.gc
puts "B: #{mbean.getHeapMemoryUsage.used}"
```

Under jruby 9.2.20.1, the heap used before + after was kinda close (numeric formatting added):

```
A: 16,309,352
B: 20,393,896
```

The more text inside the instance_eval, the more memory seems to be retained somewhere.

**Actual Behavior**

Under jruby 9.3.2.0, a lot more information seems to be retained in the heap, even after GC:

```
A: 18,304,776
B: 69,164,056
```

**Comment by enebo** [comment]
lol just doing eval '' in a loop does this.

**Comment by enebo** [comment]
IREvalScript is being help by StaticScope but why would not StaticScope not get cleaned up when the eval ends...

**Comment by enebo** [comment]
Weird I did not click close.  So looks like Eval is adding the IREvalScript to the closure lexical children list but not removing it when it is finished.  So we end up with a very large list of dead IREvalScripts.  I am somewhat surprised this is not also an issue with JRuby 9.2.x.

**Comment by enebo** [comment]
Ok this is not an issue in 9.2 because this is hidden behind a guard where we only record lexicalChildren:

 1. If running in dry run mode (e.g. when not really running but just for debugging stuff)
 2. IR persistence (we are making a jrubyc .class file or using IR persistence feature)
 3. RECORD_LEXICAL_HIERARCHY (archaic and not used).

There are a few questions:

 1. Is an eval in another closure actually a lexical child?
 2. Why are we unconditionally adding lexical children in 9.3?

I think 1 is probably the immediate fix but I cannot say for sure without understanding 2.

**Comment by enebo** [comment]
@cbeer thanks for reporting this since we were planning on another release early next week.

**Comment by cbeer** [comment]
Thanks for the quick fix @enebo; I'll give it a try as soon as I can.
