### ISSUE TITLE
jruby-9.3.3.0 is missing again on setup-ruby github action

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7025]
It sounded like it was a jruby issue rather than setup-ruby issue in the past. That's why I'm raising it here.

**Comment by headius** [comment]
I believe @eregon now has an automated job to pick up the new releases from ruby-build, to which we do submit an update PR after release.

https://github.com/ruby/setup-ruby/pull/277

It did not appear to submit this PR until yesterday, so I'm not sure if we should be more proactive about submitting one or not.

In any case, 9.3.3.0 should be available now on setup-ruby.

**Comment by eregon** [comment]
Yeah, it took me some days to add this release and I finally managed to automate it so it's faster and much less annoying.

Now all is needed is a merged PR to ruby-build and within 24h there should be an automatic PR in setup-ruby.
That PR still needs to be merged manually + create a release (manual due to the Marketplace), but that's basically a couple clicks vs wait for various builds & CI jobs.

**Comment by headius** [comment]
@eregon If it would be faster for me to submit a PR directly to setup-ruby, I'm willing to do that as part of release finalization. Currently, we submit update PRs to all of the following:

* rvm
* ruby-build
* ruby-versions
* docker official images

I believe I have push rights for rvm and ruby-versions but the other two require a project person to merge things in.
