### ISSUE TITLE
ArgumentError re-splatting empty keyword arguments

### ISSUE THREAD

**Issue by yaauie** [jruby/jruby#7102]
This issue comes from an error in Sinatra 2.2.0 when run on JRuby, due to the use of [keyword-arg splatting](https://github.com/sinatra/sinatra/tree/v2.2.0/lib/sinatra/base.rb#L1530-L1539), but has been reduced to eliminate Sinatra from the equation and merely compares MRI against JRuby.

**Environment Information**
  
Provide at least:
* JRuby version (`jruby -v`) and command line (flags, JRUBY_OPTS, etc): `jruby-9.3.0.0`, `jruby-9.2.19.0` as built by `ruby-build`
* Operating system and platform (e.g. `uname -a`):
   `Darwin limbo.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Jun 22 19:37:08 PDT 2021; root:xnu-4903.278.70~1/RELEASE_X86_64 x86_64`

Other relevant info you may wish to add:
* Installed or activated gems: _none_
* Application/framework version (e.g. Rails, Sinatra) _none_
* Environment variables _N/A_

**Expected Behavior**

With the following minimal script to represent how  successfully on MRI, without any of the Sinatra code:

~~~ ruby
def mew!
  'MEOW'
end

def mew(*args, **kwargs, &bk)
  mew!(*args, **kwargs, &bk)
end

puts mew
~~~

MRI handles the zero-keyword call and routes through to the other method:

~~~
╭─{ yaauie@limbo:~/REDACTED }
╰─● (rbenv shell 2.7.2; ruby kwargs-splat.rb)        
MEOW
[success]
~~~

**Actual Behavior**

JRuby raises an ArgumentError about arity mismatch:

~~~
╭─{ yaauie@limbo:~/REDACTED }
╰─● (rbenv shell jruby-9.3.0.0; ruby kwargs-splat.rb)
ArgumentError: wrong number of arguments (given 1, expected 0)
    mew! at kwargs-splat.rb:2
     mew at kwargs-splat.rb:7
  <main> at kwargs-splat.rb:10
( rbenv shell jruby-9.3.0.0; ruby kwargs-splat.rb; )  7.84s user 0.44s system 380% cpu 2.176 total
[error: 1]
~~~

**Comment by enebo** [comment]
Notes...TL;DIR: Method called knows it was given a kwrest through a flag saved with the call. if that flag is present and there are not kwargs and no rest it will remove the arg.            

I changed the repro to this:
```ruby
def mew!
  'MEOW'
end

a = {}
mew!(*[], **a)
```

```**[]``` in Ruby 2.6 is magicked away during parsing (Ruby 3 adds it back again) so it is not handled consistently.

The AST generated for this is:

```text
RootNode line: 0
  BlockNode line: 0
    DefnNode*:mew! line: 0
      ArgsNode line: 1
        ListNode line: 1
        ListNode line: 1
        ListNode line: 1
        ListNode line: 1
      StrNode* line: 1
    LocalAsgnNode*:a line: 4
      HashNode line: 4
    FCallNode*:mew! line: 5
      ArgsPushNode line: 5
        SplatNode line: 5
          ZArrayNode line: 5
        HashNode line: 5, null
          LocalVarNode:a line: 5
```

The instrs:

```text
     0	[DEAD]%self = recv_self()
     1	%v_0 = load_frame_closure()
     2	%current_module = copy(module<0>)
     3	line_num(;n: 0)
     4	def_inst_meth(;name: mew!)
     5	line_num(;n: 4)
     6	%v_2 = copy({!abs-arg!})
     7	a(0:0) = copy(%v_2)
     8	line_num(;n: 5)
     9	%v_6 = copy(Array:[])
    10	%v_5 = build_splat(%v_6)
    11	%v_7 = copy({!abs-arg!})
    12	%v_7 = runtime_helper(%v_7, a(0:0) ;method: MERGE_KWARGS)
    13	%v_8 = build_compound_array(%v_5, %v_7 ;type: push)
    14	%v_4 = build_splat(%v_8)
    15	%v_3 = call(%self, *(unsplat)%v_4 ;n:mew!, t:FU, cl:false)
    16	return(%v_3)
```

So the result of how we (and MRI) handle this is that we merge rest and kwargs together into an array.  There are no rest args and the argspush more or less just ends up with this equivalent in Ruby ```*[{}]```.  So we have a sole empty hash which is what ```a``` is.

Where this goes off the rails is MRI will maintain a flag list in the call to highlight stuff.  The important flag value it sets is ```VM_CALL_KW_SPLAT```.  When MRI enters the part of code which processes incoming args it knows ```mew!``` has no kwargs.  It also has this code:

```C
    if (ci->flag & VM_CALL_KW_SPLAT) {
	kw_splat = !iseq->body->param.flags.has_rest;
    }
```

```kw_splat``` is false by default.  Since mew has no rest arg it toggles kw_splat to true which in turn hits this code next:


```C
     if (given_argc > min_argc &&
	(iseq->body->param.flags.has_kw || iseq->body->param.flags.has_kwrest ||
	 (kw_splat && given_argc > max_argc)) &&
	args->kw_argv == NULL) {
	if (args_pop_keyword_hash(args, &keyword_hash)) {
	    given_argc--;
	}
    }
```

```kw_splat``` is true and we gave one too many arguments.  There are no already provided keywords so just just subtracts that out of the arguments list.   Huzzah.

The bummer of the fix for <9.4 is that it will not be useful for Ruby 3 where kwargs are marked themselves (e.g. ```**a``` will have a kwargs flag itself).  Just adding a flag to CallBase is enough to know we need to do something when we call but that information still has to be passable to the method we are calling.  We have no direct way to pass this and we don't want to put another field on TC.  

Marking the splat via field similar to how Ruby 3 does this could also work but just only for detecting the splat.  In looking at this I realize our Ruby 3+ support still has this issue too so this also needs to be fixed there.  I am going to ponder this a bit tonight.
