### ISSUE TITLE
[Q] about require 'jruby'.

### ISSUE THREAD

**Issue by hiroyuki-sato** [jruby/jruby#7221]
Hello, developers.

As far as I know, JRuby 9.3.0.0 need to `require "jruby"` to avoid `undefined method 'runtime' for JRuby:Module`. (#6868)
I would like to know the detail of this change because I need to explain [this change](https://github.com/embulk/embulk/pull/1505#discussion_r877167051). 

Does anyone tell me the following?
* Could you tell me the commit id for this change? Why JRuby 9.3 need `require "java"`?
* Is it possible to replace `require 'jruby'` instead of `require 'java'` < JRuby 9.3? (9.2.20.1 and 9.1.15.0(Embulk still uses this version. I know It's the EOL version))
  (It seems OK in my test case. [jruby.rb](https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/jruby.rb) doesn't find `require` statement, so I can't understand how that code loads `java.rb`)

Best regards.

**Comment by enebo** [comment]
@hiroyuki-sato this is something we probably should have documented better but 'require "java"' has always been how one is supposed to load Java features to Ruby.  It happened to work in the past because we were using java features to implement some core part of JRuby but then we stopped using those features (we did it a different way later).

require 'jruby' is how you get access to jruby internal features like the 'runtime' method.

In both cases these are specific requires to access these features.  We do not want them loaded by default to help load as little as possible at startup time.  Startup time in JRuby is our most signficant problem.  Not loading as many features helps improve startup time.

I don't remember which version we ended up not implicitly loading 'java'.  If this was in the middle of 9.2.x.x we could consider adding it for 9.2.x as it would appear to be an incompatibility (even though we never meant it to be a default feature).

"(It seems OK in my test case. [jruby.rb](https://github.com/jruby/jruby/blob/master/core/src/main/ruby/jruby/jruby.rb) doesn't find require statement, so I can't understand how that code loads java.rb)"

Are you saying if you require 'jruby' it manages to also load 'java' but you are unsure how it does that?  Or that you need to do both?

**Comment by hiroyuki-sato** [comment]
Hello, @enebo. Thank you for your comment.


I understood the following. Is this correct? (In >= 9.3.0.0 case)

* `require 'jruby'` is ncecessary if I use JRuby internal feature. (ex: `runtime` method.)
* `require 'java`' is necessary if I use the Java feature. 
* `require 'jruby'` doesn't call `require 'java'`. If I use Java features, I need to call `require 'java'` explicitly.
* `JRuby.runtime` is the JRuby internal feature. It happened to work in < 9.3.0.0 without `require 'jruby'`.  


`JRuby.runtime` worked without `require 'jruby'` in 9.2.20.1. I think you don't need to backport.

```
java -jar jruby-complete-9.2.20.1.jar -S 'irb'
irb(main):001:0> puts JRUBY_VERSION
9.2.20.1
=> nil
irb(main):002:0> JRuby.runtime
=> #<Java::OrgJruby::Ruby:0x7946e1f4>
```

Best regards.

**Comment by hiroyuki-sato** [comment]
@enebo Thank you for your comment.

**Comment by enebo** [comment]
@hiroyuki-sato Thanks and I wish we had made this a bit more clear.
