### ISSUE TITLE
Proposal: define `foo=` regardless of return type of `setFoo(1)`

### ISSUE THREAD

**Issue by byteit101** [jruby/jruby#7340]
The increased popularity of fluent and fluent-ish API's in Java libraries has meant that there are more setters that don't return void. I propose the following:

If a java method has a name of `set([A-Z]\w*)` and a single parameter, define a ruby-style setter proxy. As a ruby-oriented proxy, it should return the argument passed, ignoring the true return value of the underlying java method.

The benefits of this approach are:

1. More seamless Ruby-Java integration for those Java libraries that define fluent or fluent-ish APIs
2. No need to check the Javadoc of the library to determine if the ruby form `#foo=` is defined or merely the default `#set_foo`. Reading blog posts, irb tab completion, and other code listings is sufficient to translate java-style calls to ruby-style calls
3. Simpler to explain when alternate method names are defined

The drawbacks of this approach are:
1. No ability to get the return value with ruby-style calls, Must use java method name, or snake-cased version
2. People expecting `#foo=` to fail on java objects won't have that failure anymore

Thoughts? Any benefits or drawbacks I've missed?

**Comment by kares** [comment]
> The increased popularity of fluent and fluent-ish API's in Java libraries 

Is there any libraries in particular that you had in mind?

Have no objections against skipping the return check, except that is how bean-style properties where defined. I remember there's also special care to only support `boolean isFoo` but not `Boolean isFoo`.

**Comment by byteit101** [comment]
> Is there any libraries in particular that you had in mind?

No, though in the past ~6 months I have ran into this with 3 separate libraries

**Comment by kares** [comment]
have run into such setters as well but mostly around the builder pattern where the return is usually `this`.
in those cases the ruby style setter is actually redundant e.g.

`obj.set_foo(:foo).set_bar('bar').build` vs `obj.foo=(:foo).bar=('bar').build` :red_circle: 

again I am not against it just would like to keep the discussion going for a bit, if you recall any concrete examples please share them.

**Comment by byteit101** [comment]
Yes, if you chain it it is, but that's only part of the type of setters I've seen, and I wouldn't use the ruby-style setters for that case anyway, as it wouldn't work like that anymore[1]. I've mostly used that style for single property setters, and not in chains.

I've scanned my m2 library for various types of setters, and here is what I found:

## Standard fluent `return this` chainables

Maven and Aether are two big contributors in this category, and I ran into it repeatedly when trying to make the `maven-requre` library earlier this year. Here is actually one of my experimentation's:
```rb
def build_model_from_artifact(artifact)
    mbr = DefaultModelBuildingRequest.new
    mbr.set_process_plugins true
    mbr.set_model_source FileModelSource.new(artifact.file)
    mbr.set_model_resolver @model_resolver
    @model_builder_factory.newInstance.build(mbr)
end
```
Now, I would have liked to make it more ruby like, such as:
```rb
def fantasy_build_model_from_artifact(artifact)
    mbr = DefaultModelBuildingRequest.new
    mbr.process_plugins = true
    mbr.model_source  = FileModelSource.new(artifact.file)
    mbr.model_resolver = @model_resolver
    @model_builder_factory.newInstance.build(mbr)
end
```
So there are lots of methods here, but I've picked for maven and aether, respective:
1. https://maven.apache.org/resolver-archives/resolver-LATEST/maven-resolver-api/apidocs/org/eclipse/aether/resolution/VersionRangeRequest.html#setArtifact-org.eclipse.aether.artifact.Artifact-
2. https://maven.apache.org/resolver/apidocs/org/eclipse/aether/DefaultRepositorySystemSession.html#setOffline-boolean-

As this was the most popular category for fluent/fluent-ish API's, here are 3 more I found in this category in my m2 repo:
1. http://www.jdom.org/docs/apidocs/org/jdom2/Element.html#setName-java.lang.String-
2. https://vaadin.com/api/platform/23.2.0/com/vaadin/flow/component/datepicker/DatePicker.DatePickerI18n.html#setToday(java.lang.String)
3. https://hc.apache.org/httpcomponents-core-4.4.x/current/httpcore/apidocs/org/apache/http/impl/bootstrap/ServerBootstrap.html#setServerInfo(java.lang.String)

## Returning the value set
I'll admit I wasn't expecting this category, but I actually have run into this when doing selenium stuff a few years ago. Apache commons is chock-full of this kind of fluent-ish API. The benefit of this category is there is no semantic difference between it and a typical ruby-style assignment.

1. https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/mobile/NetworkConnection.html#setNetworkConnection(org.openqa.selenium.mobile.NetworkConnection.ConnectionType)
2. https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/BitField.html#setShort-short-

## Returning the previous value set
While most maps do have JRuby magic on top, they natively do this in Java. I also though I'd highlight some of the DOM API's here, which, for example, return the previous attribute. 

1. https://docs.oracle.com/javase/7/docs/api/org/w3c/dom/Element.html#setAttributeNode(org.w3c.dom.Attr)
2. Implementation of the above: https://xerces.apache.org/xerces2-j/javadocs/xerces2/org/apache/xerces/impl/xs/opti/DefaultElement.html#setAttributeNode(org.w3c.dom.Attr)
3. https://developers.google.com/j2objc/javadoc/jre/reference/java/util/AbstractMap.SimpleEntry.html#setValue(V)

## Returning a success `boolean`
This was the kind that actually made me file this ticket, as I've been doing stuff in Ghida/[ruby-dragon](https://github.com/goatshriek/ruby-dragon/pull/26) recently. Interestingly, Ghidra has lots of setters that won't be affected by this change, like [this setName function with two arguments](https://ghidra.re/ghidra_docs/api/ghidra/program/model/symbol/Symbol.html#setName(java.lang.String,ghidra.program.model.symbol.SourceType)). 

1. https://ghidra.re/ghidra_docs/api/ghidra/app/decompiler/DecompInterface.html#setOptions(ghidra.app.decompiler.DecompileOptions)
2. https://docs.oracle.com/javase/8/docs/api/java/io/File.html?is-external=true#setLastModified-long-
3. Extensions of the above: https://www.javadoc.io/doc/com.github.jnr/jnr-posix/3.1.10/jnr/posix/JavaSecuredFile.html#setLastModified-long-

As a final example, currently my Ghidra script looks like:
```rb
#...
ifc = DecompInterface.new
ifc.set_options DecompileOptions.new
ifc.open_program $current_program
#...
```
Whereas I'd like it to be:
```rb
#...
ifc = DecompInterface.new
ifc.options = DecompileOptions.new
ifc.open_program $current_program
#...
```

[1] I'd just to clarify something. Your example of `obj.foo=(:foo).bar=('bar').build` would raise an error of `NoMethodError (undefined method 'bar=' for :foo:Symbol)` in my current proposal as `foo=` would return its argument, not `self`, in line with Ruby idioms. This means that `set_foo` and `foo=` are no longer synonyms and have different return values.

**Comment by headius** [comment]
I don't see any down side to adding this feature. It is typically not possible to chain `foo=` attribute assignments as @kares proposed since the syntactic sugar form `x.foo = bar` will always return the result of `bar`. The chained form with parentheses, using `foo=()` as a normal call, is both uncommon and unaffected by adding `foo=` in the first place; if we set up the attribute method to return the result of `x.setFoo(...)` it will still work both as `x.foo = ...` and as `x.foo=(...).something_else()`.

**Comment by kares** [comment]
The two arg setters (e.g. `setName​(java.lang.String newName, SourceType source)`) seem something we do not want to setup with a Ruby style `name= ...` alias.

Given that we would allow variances of return values in Java such as those mentioned (e.g. returning this or a boolean) -> would mean we either do the same with Ruby field writers or this will be more work - since currently the Ruby style `foo=` are simply aliases for `setFoo` (and as expected by Ruby writers return the argument).

**Comment by rubyFeedback** [comment]
Personally (I may be biased) I think this is fine.

In ruby-gtk they used .foo = as well as set_foo().

In Java I am kind of used (or, somewhat) to .setFoo(). So to me personally

I like the flexibility. I tend to use
    set_foo()

most of the time myself, but I understand people preferring .foo = since you
can save a few characters. (e.g the ".set_" parts 3 chars on an object versus the
". =" aka 2 chars. I don't include the "foo" part since this would be the same for
.set_foo 'abc' as well as .foo = 'abc'. I do include the ' ' before the '=' though,
so I come to only a small saving.)

Or to illustrate:

    .set_foo 'abc'
    .foo = 'abc' # is shorter right

.setFoo would be even shorter but I don't quite like the "F" simply due to having
to press an additional key. May be totally irrelevant for short code but in larger
code bases I try to be succinct when possible but without sacrificing readability.
To me, the slightly longer .set_foo() still helps me, oddly enough. For a similar
reason I prefer {} rather than do/end. The {} helps me visually versus do/end
(and is a tiny bit shorter too; I am aware that it is not 100% equivalent due 
to binding preferences being different but most of the time I go with my own
style and then stick with it for a given code base).

**Comment by kares** [comment]
thanks @rubyFeedback, JRuby already has underscore aliases so when a Java API has a `setFoo` setter:
- `setFoo` works from Ruby
- `set_foo` is setup as an alternative name
- `foo=` is added as an alias

the discussion was mostly regarding whether to setup the alias for any `setFoo` regardless of the return type (the Java specification assumes setters have a void return type)
