### ISSUE TITLE
Changing method visibility changes super_method for module-inherited methods

### ISSUE THREAD

**Issue by evaniainbrooks** [jruby/jruby#7344]
Follow-up to https://github.com/jruby/jruby/issues/7240

Environment Information

JRuby 9.3.4.0

```
module A
  private
  def derp message
    puts [message, ' from A'].join
  end
end

module B
  private
  def derp
    puts 'from B'
    super("superclass")
    puts "subclass"
  end
end

class C
  include A
  include B
end

pp C.instance_method(:derp).super_method
# <UnboundMethod: A#derp>
C.send(:public, :derp)
pp C.instance_method(:derp).super_method
# <UnboundMethod: B#derp>
```

Expected behavior: `C.instance_method(:derp).super_method` should not change from `A#derp` to `B#derp` after changing method visibility,

**Comment by evaniainbrooks** [comment]
Similarly, after calling `alias_method`, the `super_method` is not reported correctly for module-inherited methods. It is actually returning `nil`:

```
module A
  private
  def derp
  end
end

module B
  private
  def derp
    super
  end
end

class C
  include A
  include B
end

C.alias_method :meow, :derp
pp C.instance_method(:meow).super_method
# nil
```

CRuby returns the expected `C(A)#derp`

**Comment by headius** [comment]
Good examples, thanks!

Confirmed both examples are broken on 9.3 HEAD.

**Comment by headius** [comment]
At a glance, I would say the first example fails because we now have a method entry in C (used to wrap the private `derp` with a public invoker) and rather than searching for a super method starting at B#derp it tries to do it from C#derp.

The second example seems like it may simply be a bug with `super_method` in that it is not considering the original name of the method when searching for a superclass method.

In both cases, though, we are losing the context for the super call when installing one of these wrapper methods (visibility or alias).

**Comment by headius** [comment]
Thank you!
