### ISSUE TITLE
require_relative confused by chdir

### ISSUE THREAD

**Issue by ivladak** [jruby/jruby#7394]
Hi! 

I'm new to Ruby, but I believe, I've stumbled across a bug in JRuby implementation. I prepared a minimal example, which should be self-explanatory, so let me start with that.

**Reproducer**

`reproducer.sh`:
```
#!/bin/sh

cat << EOF > main.rb
Dir.chdir("foo")
require_relative "other"
puts "main finished"
EOF

cat << EOF > other.rb
puts "other finished"
EOF

mkdir -p foo

echo "MRI>"   &&  ruby main.rb
echo "JRuby>" && jruby main.rb
```

`cd /tmp && sh ./reproducer.sh`
```
MRI>
other finished
main finished
JRuby>
Errno::ENOENT: No such file or directory - /tmp/foo/main.rb
          realpath at org/jruby/RubyFile.java:898
  require_relative at org/jruby/RubyKernel.java:1040
            <main> at main.rb:2
```

**Compliance**

JRuby's behavior looks non-compliant to me, as language specification requires treating the `other.rb` path as _relative to the requiring file’s path_, regardless of the current working directory
https://docs.ruby-lang.org/en/3.1/Kernel.html#method-i-require_relative

**Environment Information**

I believe, this should be widely reproducible, but here's my setup
  
```
$ jruby -v
jruby 9.3.8.0 (2.6.8) 2022-09-13 98d69c9461 OpenJDK 64-Bit Server VM 18.0.2+0 on 18.0.2+0 +jit [x86_64-linux]
```
Arch Llinux (kernel 5.10.142-1), also reproduced on Ubuntu 18.04, with several versions of jruby (and an older JVM).

**Comment by headius** [comment]
Wow, that's pretty weird. I would not have expected chdir to affect this. I'll look into it.

**Comment by headius** [comment]
This is bumped to 9.3.10.0 due to the invasiveness of the fix. In order to fix this we need to start tracking the full path to the CLI script, which will probably mean keeping three different paths around in the IR and bytecode for various uses:

* The relative path of the script, based on the CLI filename or the `require` filename. This will be used to assist debuggers that depend on relative paths.
* The absolute path of the script after canonicalizing, with consideration for symlinks. This will be used for `require_relative` and for error reporting that uses the full system path to a file.
* The `__FILE__` filename, which may be the relative path in the case of CLI scripts and the full path in the case of normal `load` and `require` scripts.

In any case, this is too much to do in 9.3.9 so we will look at it for a future release.

**Comment by eregon** [comment]
This is still an issue and it prevents running some yjit-bench benchmarks.
For instance:
```
$ ruby -Iharness benchmarks/erubi_rails/benchmark.rb
jruby 9.4.2.0 (3.1.0) 2023-03-08 90d2913fda OpenJDK 64-Bit Server VM 17.0.7+4-jvmci-23.0-b10 on 17.0.7+4-jvmci-23.0-b10 +indy +jit [x86_64-linux]
Command: bundle check 2> /dev/null || bundle install
The Gemfile's dependencies are satisfied
Errno::ENOENT: No such file or directory - /home/eregon/code/yjit-bench/benchmarks/erubi_rails/benchmarks/erubi_rails/benchmark.rb
          realpath at org/jruby/RubyFile.java:956
  require_relative at org/jruby/RubyKernel.java:1080
            <main> at benchmarks/erubi_rails/benchmark.rb:8
```
https://github.com/jruby/jruby/issues/4700 is probably the same issue as well.

TruffleRuby had the same bug and it was fixed in https://github.com/oracle/truffleruby/issues/2709
That issue links to both the fix and the added specs.
It was not too difficult to fix, because there is only one main script, so it's enough to store the main script absolute path and some reference to the parsed main script to identify it and canonicalize paths based on that.
