### ISSUE TITLE
Time.at with fractional seconds and :in doubles timezone offset

### ISSUE THREAD

**Issue by jeremyevans** [jruby/jruby#7406]
**Environment Information**

Appears to be OS-independent, as it is reproducible on both:  

`jruby 9.3.8.0 (2.6.8) 2022-09-13 98d69c9461 OpenJDK 64-Bit Server VM 25.342-b07 on 1.8.0_342-b07 +jit [x86_64-OpenBSD]`
`jruby 9.3.0.0 (2.6.8) 2021-09-17 85c20e780f Java HotSpot(TM) 64-Bit Server VM 25.131-b11 on 1.8.0_131-b11 +jit [mswin32-x86_64]`

**Expected Behavior**

With the following code:

```ruby
require 'tzinfo'
v = Time.now
tz = TZInfo::Timezone.get('America/New_York')
p Time.at(v.to_i, :in => tz)
p Time.at(v.to_i, v.nsec, :nsec, :in => tz)
```

I get the following output with CRuby 2.6, which is the output I would expect from JRuby:

```
2022-10-13 09:12:47 -0700
2022-10-13 09:12:47 -0700
```

**Actual Behavior**

I get the following output with JRuby:

```
2022-10-13 09:10:12 -0700
2022-10-13 02:10:12 -1400
```

Note the doubled timezone offset when fractional seconds are provided.

I hit this when adding fractional second support to Sequel's named_timezones extension.

**Comment by headius** [comment]
It's not exactly doubling; rather, it is combining the current zone offset with the requested zone offset. I am in America/Chicago at -0400 and the end result of applying America/New_York at -0500 is a time zone of -0900:

```
$ jruby blah.rb
2022-10-13 17:11:50 -0400
2022-10-13 12:11:50 -0900
```

I think this is due to the logic calling back into `utc_to_local` to get the local time before applying the new zone, but then appying the new zone offset on top of the local time's offset.

The code for this is largely based on CRuby's so I'll try to trace through the CRuby logic and figure out what we duplicated incorrectly.

**Comment by headius** [comment]
It is a bit disturbing that we did not fail any of the Time.at Ruby specs nor any of the tests in the tznfo gem.

@jeremyevans could you submit this and maybe some other test cases to the Ruby spec suite?

**Comment by jeremyevans** [comment]
I'll add that to my todo list.
