### ISSUE TITLE
Probably method_missing is not handling keyword arguments properly [jruby-9.4.1.0]

### ISSUE THREAD

**Issue by klobuczek** [jruby/jruby#7670]
The following script generates a minimal rails application with rspec and simplecov. Note the latter is required to expose the issue. 
The script runs `rspec` on the pristine rails app and returns successfully on all rubies (jruby and MRI) except jruby-9.4.1.0
```
#!/bin/bash

rails new boom-app -OTJ --api
cd boom-app
echo 'gem "rspec-rails"' >> Gemfile
echo 'gem "simplecov"' >> Gemfile
bundle update
rails generate rspec:install
echo "require 'simplecov'" >> spec/boom_spec.rb
echo "SimpleCov.start 'rails'" >> spec/boom_spec.rb
echo "require 'rails_helper'" >> spec/boom_spec.rb
echo "RSpec.describe('example') { it {} }" >> spec/boom_spec.rb
rspec
```

The top of the error stack:
```
Unhandled Java exception: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 75
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 75
                     get at org/jruby/util/collections/IntList.java:25
               coverLine at org/jruby/ext/coverage/CoverageData.java:98
          updateCoverage at org/jruby/ir/runtime/IRRuntimeHelpers.java:644
    processBookKeepingOp at org/jruby/ir/interpreter/InterpreterEngine.java:422
               interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:94
               interpret at org/jruby/ir/interpreter/InterpreterEngine.java:82
        INTERPRET_METHOD at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:201
                    call at org/jruby/internal/runtime/methods/MixedModeIRMethod.java:188
  finvokeWithRefinements at org/jruby/RubyClass.java:538
                    send at org/jruby/RubyBasicObject.java:1651
                    call at org/jruby/RubyBasicObject$INVOKER$i$send.gen:-1
                    call at org/jruby/internal/runtime/methods/JavaMethod.java:444
                    call at org/jruby/runtime/callsite/CachingCallSite.java:291
             processCall at org/jruby/ir/interpreter/InterpreterEngine.java:328
               interpret at org/jruby/ir/interpreter/StartupInterpreterEngine.java:66
         INTERPRET_BLOCK at org/jruby/ir/interpreter/Interpreter.java:116
         commonYieldPath at org/jruby/runtime/MixedModeIRBlockBody.java:136
                 doYield at org/jruby/runtime/IRBlockBody.java:170
                   yield at org/jruby/runtime/BlockBody.java:108
                   yield at org/jruby/runtime/Block.java:188
                    each at org/jruby/RubyArray.java:1988
```

However, this error is not the root cause of the issue. In railties in the file rails/intializable.rb:60 while iterating through the Initializers at some point `tsort_each` starts yielding `ArgumentError: wrong number of arguments (given 0, expected 1..2)` and repeats doing so until the above `ArrayIndexOutOfBoundsException`. I dug a little bit deeper and saw that there are method_missing calls in the stack. But since it moves back and forth between java and ruby my debugger does not support such stepping into.

When upgrading our application to jruby-9.4.1.0 I got tons of those ArgumentErrors mostly because methods or method calls were not using the ruby 3.1 syntax. But maybe jruby should tolerate the old syntax as MRI ruby does. It was relatively obvious how to fix it in our code but here in other gems it is difficult to even find the place.

![Screenshot 2023-02-17 at 12 50 04 PM](https://user-images.githubusercontent.com/81925/219800848-6c8f0a53-41ac-43f7-be67-e34b0207c9db.png)

**Environment Information**
  
Provide at least:
* JRuby version 9.4.1.0
* Operating system and platform Mac M1 and Ubuntu

**Comment by enebo** [comment]
"When upgrading our application to jruby-9.4.1.0 I got tons of those ArgumentErrors mostly because methods or method calls were not using the ruby 3.1 syntax. But maybe jruby should tolerate the old syntax as MRI ruby does. It was relatively obvious how to fix it in our code but here in other gems it is difficult to even find the place."

Could you please file issues for these?  I am unaware of any compatibility issues between us and MRI 3.1.  In the last 3 issues you put in a sentence implying we are doing these things purposely.  We are a compatibility project.  Barring unsupportable things like running Kernel#fork we generally try and be as compatible as possible (with rare exceptions like flip-flop operator :smile:).

I will continue to figure out what is wrong in this case (I was using Rails 7 until I noticed you ar running with Rails 6 so I am going to try and line up these backtraces).

**Comment by enebo** [comment]
@klobuczek I will figure this one out.  It is passing kwargs to a signature which is not expecting to receive them.  This is the opposite problem I usually encountered debugging kwargs issues (passing a kwargs as an ordinary hash).

**Comment by enebo** [comment]
@klobuczek I believe there are at least two issues at play.   The first is what I fixed which represents the stack trace in the report.  This was us erroneously setting the line of source to -1 due to a change in how the parser works.  I can now run rspec with the app you provided and it shows:

```text
system ~/work/jruby/boom-app main # 3530% JRUBY_OPTS="--dev --debug" jruby -S rspec
/home/enebo/work/jruby/lib/ruby/gems/shared/gems/ruby-debug-0.11.0/cli/ruby-debug/commands/list.rb:36: warning: `-' after local variable or literal is interpreted as binary operator
/home/enebo/work/jruby/lib/ruby/gems/shared/gems/ruby-debug-0.11.0/cli/ruby-debug/commands/list.rb:36: warning: even though it seems like unary operator
.

Finished in 0.0932 seconds (files took 4.36 seconds to load)
1 example, 0 failures

Coverage report generated for RSpec to /home/enebo/work/jruby/boom-app/coverage. 0 / 16 LOC (0.0%) covered.
```

Should this really be 0% though?  It is started before loading rails-helper?  If not then there is something wrong with coverage.  I am going to look at that now.

The third thing is the method mismatches you experienced trying to figure this problem out.  That I think is something within ruby-debug which is passing keyword args to a method which does not expect them.  If you could perhaps try and tell me how far I need to step or where beyond the tsort initializers eaching.  That I could not reproduce but I was not stepping into anything.  I predict ruby-debug or dependent gem needs to be changed to be Ruby 3.1 compatible (probably with some method changes using ruby2_keywords method specifier).

**Comment by enebo** [comment]
I can get coverage data when using test-unit so I am guessing perhaps the rails profile is not really hitting any rails code in the example so we see no coverage.

**Comment by klobuczek** [comment]
@enebo yes, the script was not designed to show any meaningful coverage, but rather to expose the error. 0% is correctly reported as no line is hit by this test.
However, if you fixed the ArrayIndexOutOfBoundsException only then I suspect the initialization is still not done properly, and the `ArgumentError: wrong number of arguments (given 0, expected 1..2)` might still be happening but swallowed.
Is there any jruby beta version I could use to test this?

**Comment by enebo** [comment]
@klobuczek You can get latest builds at this url: https://github.com/ruby/jruby-dev-builder/releases/latest.
