### ISSUE TITLE
The `File#absolute_path?` implementation in JRuby 9.4.x.x causes issues with *asciidoctor-pdf*

### ISSUE THREAD

**Issue by sschuberth** [jruby/jruby#7744]
Looks like the `File#absolute_path?` implementation added in https://github.com/jruby/jruby/commit/42a2ab9fb407b8ce485105c5fa801cb5ef9de530 causes issues:

https://github.com/jruby/jruby/blob/98c9d139629a6134340caa71eeb73d33edbc6679/core/src/main/java/org/jruby/RubyFile.java#L928-L934

I'm cross-posting this from https://github.com/asciidoctor/asciidoctor-pdf/issues/2383 to raise awareness that some (valid?) assumptions of *asciidoctor-pdf* about how `File#absolute_path?` relates to `Pathname#absolute?` do not seem to hold anymore as of JRuby 9.4.x.x, and seem to not be in line with CRuby, see https://github.com/asciidoctor/asciidoctor-pdf/issues/2383#issuecomment-1497006056 and following.

**Comment by enebo** [comment]
This actually pointed out two bugs in 9.4.  Second one opened here: https://github.com/jruby/jruby/issues/7745

**Comment by mojavelinux** [comment]
I'd like to add that `Pathname#absolute?` is now returning `true` when an absolute URL is passed to it, which is incorrect behavior (based on how it works in CRuby).

```rb
puts Pathname.new('https://example.org').absolute?
```

**Comment by mojavelinux** [comment]
To be clear, this issue is in no way related to Asciidoctor PDF. We just happened to have discovered it there.

**Comment by enebo** [comment]
As a reprospective the problem with our testing is that when it was written it only tested for things we added (special uris as paths) that worked.  There were no negative test cases like (http:).  As it turned out the way pathname was implemented it just happened to be false until last year when the impl changed.

I moves the unit tests into a newer jruby:specs task where I plan on migrating more and more of our pretty sloppy regression tests and our older unit tests into a more unified place.  This may take a long time but it should make it easier to look up expected behavior more easily.
