### ISSUE TITLE
Ruby 2.7 conformance: ObjectSpace::WeakMap is broken for FixNum keys

### ISSUE THREAD

**Issue by JasonLunn** [jruby/jruby#7862]
* JRuby version: Reproducible on 9.4.3.0 release

**Expected Behavior**

Per https://github.com/rubyreferences/rubychanges/blob/master/2.7.md#objectspaceweakmap-now-accepts-non-gc-able-objects as of Ruby 2.7, ObjectSpace::WeakMap should be able to accept numeric keys.

**Actual Behavior**

Accessor functions like `#key?` and `#[]` behave as though a numeric key is not present when queried, except if the instance of the key that appears in `#keys` is used.

```ruby
foo = Object.new
m=ObjectSpace::WeakMap.new
original_key = 105553124374448
m[original_key] = foo
puts "m.key?(105553124374448) #{m.key? 105553124374448}"
puts m.inspect
puts m.keys.inspect
puts m.values.inspect
puts "m.key?(m.keys.first) #{m.key? m.keys.first}"
puts "m.key?(original_key) #{m.key? original_key}"
```

Outputs:
```
m.key?(105553124374448) false
#<ObjectSpace::WeakMap:0x799f354a: 105553124374448 => #<Object:0x45e140ae>>
Keys [105553124374448]
Values [#<Object:0x45e140ae>]
m.key?(m.keys.first) true
m.key?(original_key) false
```

After investigation, the root cause seems to be that the underlying backing map is `java.util.IdentityHashMap`, which uses `System.identityHashCode(Object))` to compare keys. `System.identityHashCode(Object))` does not return identical values for two `org.jruby.RubyFixnum` instances that have identical values for `IRubyObject.id()` or `Object.hashCode()`.

**Comment by headius** [comment]
So there's a few reasons this may not be possible for us to support:

* WeakMap in CRuby is also a true identity map; it uses the address of any incoming object to calculate both the hash and perform a comparison; only two objects with the same address will match (i.e. the same object).
* Fixnum and Float values in JRuby are always objects and the same value may show up with many different wrapper objects. This breaks the semantics of WeakMap's identity hash as seen here. In CRuby, fixnum and flonum values are tagged pointers that will be the same for all equivalent values and those pointers will never collide with real ones.
* Simply changing our WeakMap to use a non-identity hash would introduce new behavior; specifically, it would start calling `Object#hash` to get the hash value and `Object#===` for comparison, which will cause collisions for objects that have the same value but different identity.

You can try out the non-identity hash idea and see if it works, but I don't think we can change the semantics of WeakMap, as as they stand right now they won't be reliable for fixnum and float-ranged numerics.

I would suggest building a new data structure on top of WeakRef that uses a normal Hash to store keys. An example is below, though this has poor cleanup behavior (it should use reference queues and weakrefs from my "weakling" library, or iterate keys looking for dead values periodically).

```ruby
class FixnumWeakMap
  def initialize
    @hash = {}
  end
  def put(a, b)
    @hash[a] = WeakRef.new(b)
  end
  def get(a)
    w = @hash[a]
    if w
      v = w.__getobj__
      if v.nil?
        @hash.delete(a)
      end
    end
    v
  end
end

# usage
fwm = FixnumWeakMap.new
x = 9001 - 1
y = 8999 + 1
str = "foo"
fwm.put(x, str)
p fwm.get(y) # should return "foo"
```

**Comment by headius** [comment]
A possible fix occurred to me today: separate tables for objects like Fixnum-ranged Integers we want to compare by value instead of identity. Externally it should look like they're in the same table.

Oddly I can find no tests in CRuby 3.1 or recent RubySpecs that fail because of our current behavior. Perhaps you could create some specs?

**Comment by headius** [comment]
Ah, I see why the test added for this feature does not fail on JRuby. It mostly uses singleton values like "true" or "nil", which should work fine on JRuby. It also tests a fixnum `42`, which will work fine on JRuby as we maintain a cache of -256..255 values.

I will see about improving the test and see if my impl works well enough.

**Comment by headius** [comment]
Heh, the CRuby test also uses all literal integer values, which in JRuby would usually be cached as the same object within the same file.

I actually ran your script looking for something good to add as a test, it now outputs what you wanted:

```
m.key?(105553124374448) true
#<ObjectSpace::WeakMap:0x7d4f9aae: 105553124374448 => #<Object:0x27462a88>>
[105553124374448]
[#<Object:0x27462a88>]
m.key?(m.keys.first) true
m.key?(original_key) true
```

I also modified it to `eval` every literal integer value, to try to ensure they are different objects, and it still works the same.

Now for purposes of this example, I have only checked for RubyFixnum and RubyFloat, two objects that are represented as tagged pointers in CRuby and which should therefore be idempotent. The other types tested by CRuby already worked because they only existed in singleton form and most would never GC anyway.

If there's any other types this should apply to, we could add it.

I still wish Ruby had gone with my idea to add reference queues instead of WeakMap, so we could write WeakMap in pure-Ruby, but it is what is is.

PR is here: https://github.com/jruby/jruby/pull/8009
