### ISSUE TITLE
Marshal.dump with frozen string literals differs on --debug flag

### ISSUE THREAD

**Issue by segiddins** [jruby/jruby#7898]
**Environment Information**
  
`jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 19.0.1+10-21 on 19.0.1+10-21 +jit [arm64-darwin]`

**Expected Behavior**

```
❯ chruby-exec jruby-9.4 -- ruby -vwe "$(printf "# frozen_string_literal: true\np Marshal.dump('')")"
jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 19.0.1+10-21 on 19.0.1+10-21 +jit [arm64-darwin]
"\x04\bI\"\x00\x06:\x06ET"
```

**Actual Behavior**

```
❯ chruby-exec jruby-9.4 -- ruby --debug -vwe "$(printf "# frozen_string_literal: true\np Marshal.dump('')")"
jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 19.0.1+10-21 on 19.0.1+10-21 +jit [arm64-darwin]
"\x04\bI\"\x00\a:\x06ET:\x18@debug_created_info[\aI\"\a-e\x06;\x00Ti\a"
```

I would expect `--debug` not to cause the `@debug_created_info` ivar to be dumped.

**Comment by ahorek** [comment]
@debug_created_info is an internal variable for tracking frozen string literals, see https://bugs.ruby-lang.org/issues/11725 and https://github.com/jruby/jruby/commit/bfd0b763796582691a30bcada2d826bd9ae0fb58

MRI just hides it from Marshal.dump since https://github.com/ruby/ruby/commit/6964c0635f76ea79a49c8dcb85f279e0b85fc0cd which isn't really a good approach in the first place, but it shouldn't be hard to replicate it...

**Comment by enebo** [comment]
heh. I don't remember imlpementing this at all.  So I guess the FIXME I added was relevant after all.
