### ISSUE TITLE
Java::JavaLang::ClassCastException: class org.jruby.java.proxies.ConcreteJavaProxy cannot be cast to class org.jruby.RubyArray

### ISSUE THREAD

**Issue by UweKubosch** [jruby/jruby#8178]
**Environment Information**
  
* jruby 9.4.6.0 (3.1.4) 2024-02-20 576fab2c51 OpenJDK 64-Bit Server VM 17.0.10+7 on 17.0.10+7 +jit [x86_64-darwin]
* Darwin MacBook-Pro.home 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:49 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6020 arm64

This occurs inside a Spring Boot application using SLIM as a view template engine.  The general setup is handled by  https://github.com/DatekWireless/slim-spring-webmvc

We run a web crawler against our app, and most requests work fine, but intermittent requests produce an exception:

Java::JavaLang::ClassCastException: class org.jruby.java.proxies.ConcreteJavaProxy cannot be cast to class org.jruby.RubyArray (org.jruby.java.proxies.ConcreteJavaProxy and org.jruby.RubyArray are in unnamed module of loader 'app')

Stack trace:

```
org.jruby.embed.variable.Argv.getJavaObject(org/jruby/embed/variable/Argv.java:199)
org.jruby.embed.internal.BiVariableMap.get(org/jruby/embed/internal/BiVariableMap.java:230)
org.jruby.embed.internal.BiVariableMap.get(org/jruby/embed/internal/BiVariableMap.java:209)
org.jruby.embed.jsr223.Utils.postEval(org/jruby/embed/jsr223/Utils.java:198)
org.jruby.embed.jsr223.JRubyEngine.invokeMethod(org/jruby/embed/jsr223/JRubyEngine.java:229)
org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(org/springframework/web/servlet/view/script/ScriptTemplateView.java:426)
org.springframework.web.servlet.view.AbstractView.render(org/springframework/web/servlet/view/AbstractView.java:316)
jdk.internal.reflect.GeneratedMethodAccessor254.invoke(jdk/internal/reflect/GeneratedMethodAccessor254)
jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(jdk/internal/reflect/DelegatingMethodAccessorImpl.java:43)
java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:568)
org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:345)
org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:200)
uri_3a_classloader_3a_.ruby.slim_helper.invokeOther35:render(uri_3a_classloader_3a_/ruby/uri:classloader:/ruby/slim_helper.rb:27)
uri_3a_classloader_3a_.ruby.slim_helper.render(uri:classloader:/ruby/slim_helper.rb:27)
views.layouts.layout_dot_slim.invokeOther20:render(views/layouts//views/layouts/layout.slim:13)
views.layouts.layout_dot_slim.__tilt_4004(/views/layouts/layout.slim:13)
org.jruby.RubyUnboundMethod.bind_call(org/jruby/RubyUnboundMethod.java:169)
org.jruby.RubyUnboundMethod$INVOKER$i$0$0$bind_call.call(org/jruby/RubyUnboundMethod$INVOKER$i$0$0$bind_call.gen)
uri_3a_classloader_3a_.gems.tilt.template.invokeOther12:bind_call(uri_3a_classloader_3a_/gems/tilt/uri:classloader:/gems/tilt/template.rb:191)
uri_3a_classloader_3a_.gems.tilt.template.evaluate(uri:classloader:/gems/tilt/template.rb:191)
uri_3a_classloader_3a_.gems.tilt.template.invokeOther5:evaluate(uri_3a_classloader_3a_/gems/tilt/uri:classloader:/gems/tilt/template.rb:109)
uri_3a_classloader_3a_.gems.tilt.template.render(uri:classloader:/gems/tilt/template.rb:109)
uri_3a_classloader_3a_.ruby.slim_renderer.invokeOther60:render(uri_3a_classloader_3a_/ruby/uri:classloader:/ruby/slim_renderer.rb:89)
uri_3a_classloader_3a_.ruby.slim_renderer.render_slim(uri:classloader:/ruby/slim_renderer.rb:89)
org.jruby.RubyClass.finvokeWithRefinements(org/jruby/RubyClass.java:540)
org.jruby.RubyClass.finvoke(org/jruby/RubyClass.java:528)
org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.doInvokeMethod(org/jruby/embed/internal/EmbedRubyObjectAdapterImpl.java:240)
org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(org/jruby/embed/internal/EmbedRubyObjectAdapterImpl.java:160)
org.jruby.embed.ScriptingContainer.callMethod(org/jruby/embed/ScriptingContainer.java:1464)
org.jruby.embed.jsr223.JRubyEngine.invokeMethod(org/jruby/embed/jsr223/JRubyEngine.java:221)
org.springframework.web.servlet.view.script.ScriptTemplateView.renderMergedOutputModel(org/springframework/web/servlet/view/script/ScriptTemplateView.java:426)
org.springframework.web.servlet.view.AbstractView.render(org/springframework/web/servlet/view/AbstractView.java:316)
org.springframework.web.servlet.DispatcherServlet.render(org/springframework/web/servlet/DispatcherServlet.java:1406)
org.springframework.web.servlet.DispatcherServlet.processDispatchResult(org/springframework/web/servlet/DispatcherServlet.java:1150)
```

The guilty line (org/jruby/embed/variable/Argv.java:199) contains a cast to org.jruby.RubyArray, and an inspection in IntelliJ IDEA shows `rubyObject` is a RubyArray object, but still the ClassCastException is thrown.  

```java
        final RubyArray ary = (RubyArray) rubyObject;
```

Maybe a ConcreteJavaProxy mimics a RubyArray?

The error does affect our production environment.  Any help is greatly appreciated.

**Comment by kares** [comment]
Did this happen for older JRuby versions, or has this been only observed with 9.4.6 (maybe it's new functionality, would be good to know if not) ?

**Comment by UweKubosch** [comment]
I checked back to 9.4.1.0 at least.

**Comment by UweKubosch** [comment]
I have not checked 9.3 versions.  Would that be useful?  We use a lot of newer syntax, so it would take some time.

**Comment by kares** [comment]
I honestly do not know, have no solid ideas really...

What I did find weird around `ARGV` is that internally JRuby engine [converts](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/embed/jsr223/Utils.java#L242-L246) from `"javax.script.argv"` to `"ARGV"` as well as the other way around when seeing `"ARGV"` the key is adjusted to `"javax.script.argv"`. But since the exception only happens sometimes I can not explain the behavior. Maybe be some kind of "variable sharing" concurrency problem, looking at the Spring [source the javadoc](https://github.com/spring-projects/spring-framework/blob/main/spring-webmvc/src/main/java/org/springframework/web/servlet/view/script/ScriptTemplateConfigurer.java#L168) seems to suggest you will be starting a scripting engine [from the SlimConfigurer](https://github.com/DatekWireless/slim-spring-webmvc/blob/master/src/main/java/no/datek/slim/SlimConfigurer.java#L21-L28) per thread. I am not familiar with the internals but would maybe try configuring the script engine to be assumed thread-safe (assuming the Ruby parts such as [`ruby/slim_helper.rb`](https://github.com/DatekWireless/slim-spring-webmvc/blob/master/src/main/resources/ruby/slim_helper.rb) are thread-safe, which they seem to be), in the hopes that there would not be any multi-thread `ARGV` restoration.

**Comment by UweKubosch** [comment]
I tried setting the scripting container as **not shared**, and that resulted in lots of array index out of bounds exceptions on initialization, so not an improvement.

I lack the basic understanding of ConcreteJavaProxy/ARGV to find good experiments to perform. Any suggestions?

**Comment by UweKubosch** [comment]
I tried setting `configurer.setSharedEngine(false)`.  This activates the thread local with multiple instances of the engine, but the error remains the same.

**Comment by UweKubosch** [comment]
I have created a sample application at https://github.com/DatekWireless/slim-spring-mvc-sample for debugging.

**Comment by UweKubosch** [comment]
The error can be reproduced by running the included crawler:

    chruby system # Clean environment variables (GEM*, RUBY*)
    ./gradlew bootrun
    ./crawl.rb

On my system the error occurs within a couple of hundred requests.

**Comment by kares** [comment]
```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not resolve no.datek:slim-spring-webmvc:0.+.
     Required by:
         project :
      > No matching variant of no.datek:slim-spring-webmvc:0.19.2 was found.
```

**Comment by UweKubosch** [comment]
@kares Thanks for looking into this!  I'll see what the compilation problem is.

**Comment by UweKubosch** [comment]
Hmm, we've tried on several systems here, and they all compile and start the application.

Does updating dependencies help?

    ./gradlew --refresh-dependencies bootRun

**Comment by kares** [comment]
yeah it works, but this is just a repro which is hard to work with - JRuby is hidden behind a dependency's dependency.
and the error is just coming out of a servlet container.

we should try reducing the reproducer further, so it can be worked with using a custom JRuby version...

**Comment by UweKubosch** [comment]
Yes, that would be great.  Not sure how to proceed, though.

**Comment by headius** [comment]
@UweKubosch If you could stop by Matrix to chat about this we can try to help get a diagnosis and fix.

My first thought is that a Java array or collection type is getting put into ARGV without being converted, and then we expect it to be a RubyArray coming out. I don't know how that would be happening intermittently, though, and typically Java arrays go into an ArrayJavaProxy, not a ConcreteJavaProxy (so leaning toward it being a List getting into ARGV somehow).

I was able to reproduce locally and now trying to figure out how to attach a debugger.

**Comment by headius** [comment]
> an inspection in IntelliJ IDEA shows rubyObject is a RubyArray object, but still the ClassCastException is thrown

I don't see how this is possible. Perhaps you saw it at a different point in execution?

It does seem to me that `rubyObject` is getting set to a concrete Java type, probably some sort of `List`, and this blind cast may even be a bug itself. Later checks in the same method check for `javaObject` to be a `String[]` or a `List`.

Much of this code was modified by a @kares cleanup commit in 2015: https://github.com/jruby/jruby/commit/cab825cfccce7817569db744fc31e9c046520bf8

...but before that it was all code from @yokolet, specifically to handle conversions of ARGV into RubyArray: https://github.com/jruby/jruby/commit/f7d52bd2311be3920a9ea24abf7fa491985091ea

I suspect there's a bug in that "forcing" to RubyArray such that it's missing some path that allows a non-RubyArray to get into `rubyObject`.

**Comment by UweKubosch** [comment]
> @UweKubosch If you could stop by Matrix to chat about this we can try to help get a diagnosis and fix.

@headius I would love that.  When are you likely to be on?

**Comment by headius** [comment]
@UweKubosch I am on now, and will be on tomorrow morning US central time (UTC-5). We can set up a specific time if you are busy!

**Comment by UweKubosch** [comment]
I have been swamped, sorry.  When is your next convenient time?

**Comment by headius** [comment]
Ok I think I've figured out what's happening here.

The `Argv` class, extending `AbstractVariable`, represents a specific bound variable in the scripting engine. Like other `AbstractVariable` it can hold either a Java value or a Ruby value, and the logic in these classes manages converting back and forth as necessary.

The `JRubyEngine` class implements the top-level logic for e.g. evaluating a script given a scripting context. In this process, it has `preEval` it pulls pre-bound values out of the context and sets them into the engine, evaluates the script, and then calls `postEval` to pull those values back out of the engine and into the context for the next execution.

It is in this process that we get the `ConcreteJavaProxy` wrapped `ArrayList`, because the logic for getting the values back out of the engine calls `getJavaObject` which sees that there's no `javaObject` field populated and creates a new `ArrayList`. That goes into the context, and in the future when we set the value into the engine we are setting it as a `ConcreteJavaProxy`.

This all works ok, but there's another field in `Argv` called `fromRuby`. When we populate with a Ruby object, as in `Argv.inject`, we set this to true, because the `rubyObject` is actually a `RubyArray`. When we populate with a Java object, as in `AbstractVariable.updateWithJavaObjects`, the `rubyObject` is a `ConcreteJavaProxy` wrapping that `ArrayList` we previously got back and we set `fromRuby` to false so that `Argv.getJavaObject` will immediately just return the `javaObject`.

These state changes are messy but work ok single-threaded (though it's questionable why we're managing both a Java version and a Ruby version of the value in the same `AbstractVariable` when only one is usable). I could not see any way that we would normally get a `ConcreteJavaProxy` in `rubyObject` without also having the original `ArrayList` in `javaObject` and `fromRuby` set to false.

The answer seems to be that the state changes are being done across threads, and as a result we end up racing on the `rubyObject` and `fromRuby` fields, potentially having one thread set `rubyObject` to a wrapped Java object while a different thread is trying to update `rubyObject` to a normal `RubyArray`. When they cross, we might end up with the wrapped object and `fromRuby` set to true, which causes us to fall into the hard cast to `RubyArray`.

So a synchronization patch fixes it: https://gist.github.com/headius/db73cb12296299a819b8fea17fb165e5

This guards all the fields of `AbstractScript` and `Argv`. It will have some impact on concurrent uses of a scripting container.

A different fix would be to ensure that the `rubyObject` field in `Argv` never gets set to anything but a `RubyArray`, which basically takes the race out of it but might do more copying (though there's a TON of copying throughout this subsystem that needs to be improved).

I don't see any deadlock potential from the synchronization, but it would impact `ScriptingContainer` and `ScriptEngine` concurrent performance. I also strongly dislike the idea of having `rubyObject` potentially be a wrapped Java collection, so the other fix is attractive in that way.

@kares You poked around this code in 2015... maybe you can remember a bit about that process and offer some suggestions?

My gut feeling about this is that the entire embedding subsystem needs some analysis and parts like this that were patched in years later need some analysis. We could probably improve performance across the board with cleaner implementations of the entirety of variable binding and engine/container state management.

**Comment by headius** [comment]
Some additional spelunking...

The original issue that led to much of this logic being written, in order to round-trip values to and from the engine and context: https://web.archive.org/web/20150515192653/http://jira.codehaus.org/browse/JRUBY-4944

The patch for that issue by @yokolet: 780f1dda3938773ad5cfe2ab4c8cf878a5d2f051

Additional commits came in from @kares. One in particular added the update of `fromRuby` back to `true` which could have led to this concurrency problem (previously it could only get set to `false` and then stayed that way): https://github.com/jruby/jruby/commit/f393116bc2fe54e2547128d40cbc474d60a34f44#diff-5e6c26a3be372282369ddab46a07c17e5f5ede66209234f6ace7385d074591ccR130

In @kares defense, this whole thing is pretty messy from a concurrency standpoint, and there's probably other issues we'd be patching over by just sprinkling `synchronized` around.

**Comment by kares** [comment]
> You poked around this code in 2015... maybe you can remember a bit about that process and offer some suggestions?

not really - think I just wanted to fix not leaking `ARGV` as something unexpected (not `org.jruby.embed.variable.Argv`)

> So a synchronization patch fixes it: https://gist.github.com/headius/db73cb12296299a819b8fea17fb165e5

^^^ LGTM

**Comment by donv** [comment]
Is there a timeline for the JRUby 9.4.8.0 release?

**Comment by headius** [comment]
Within the next week or so!

**Comment by UweKubosch** [comment]
Wonderful!
