### ISSUE TITLE
JRuby Jar comuptation fails in OSGi environment

### ISSUE THREAD

**Issue by glatuske** [jruby/jruby#8217]
**Environment Information**
  
Provide at least:
* JRuby version: 9.4.7.0
* Operating system and platform: Windows 10 64 Bit, OSGi with Equinox

**Expected Behavior**

* JRuby should run in OSGi environment
* Any kind of access to the classpath need to take OSGi into consideration

**Actual Behavior**

* [ClasspathLauncher](https://github.com/jruby/jruby/blob/master/core/src/main/java/org/jruby/util/ClasspathLauncher.java#L37) expects a JAR classpath entry. In OSGi case this is a bundleresource (e.g. bundleresource://344.fwk257265217/org/jruby/Main.class).
* Path.of fails with java.nio.file.FileSystemNotFoundException: Provider "bundleresource" not installed
* Catching this exception and return null would be sufficient in our scenario.

**Comment by enebo** [comment]
Ah whoops.  Different fish different recipe I guess (this change was so some things would continue to run within jruby-complete.jar) For some reason I thought we had some OSGi test.

@glatuske Since you localized this would there be any chance you can make a PR since you also can test it?  It sounds like you have an idea on a fix.

**Comment by glatuske** [comment]
@enebo I can try ;-) Just to get it right the idea of  getJRubyJar() is to retrieve the location of the JAR file it self (e.g. /path/to/jruby.jar)?

**Comment by enebo** [comment]
@glatuske yeah.  In the comment I thought that this was only used with jruby-complete.jar.  Looking a little more this is only used by jrubyCommand but that is used for classpath_launcher ... which I think is where you are calling this from?

I feel like I am missing the path where OSGi requests this.  Do you think the uri stripping is the main issue?

The original fix was because on newer Java's our code for determining where jruby-complete.jar (and I guess for the OSGi case) stopped working.

**Comment by glatuske** [comment]
@enebo I have checked debugged new and old behaviour. The old code was also not working with OSGi, but did not throw an exception.

The best way to get the JAR location in an OSGi environment would be:
`org.osgi.framework.FrameworkUtil.getBundle(Main.class).getLocation()`

**Comment by enebo** [comment]
@glatuske I think it is ok.   I can see we compile against org.osgi already in org.jruby.embed.osgi which ends up in jruby.jar.

So your change would be just recognize you are in an OSGi env and then use getBundle() as the replacement to determine the location.  All the rest would just be the same more or less?  If so I think that is fine.  If not then you may be finding a rich vein of new problems.  

My wonderment at this point is this is for exec'ing a new JRuby process for executing a sub-Ruby command.  OSGi I would wonder if this ever worked or is even something OSGi would want.  It seems like the OSGi way would be to get another instance of the service which does Ruby and run that in there (It has been ~20 years since I used OSGi so I am rusty :) ).  If this was not raising but giving a bad value for the location of the jar then it is possible no one has ever used the value being produced because they are not performing subspawns of Ruby....or this entire paragraph is wrong :)  It is possible this is how it works for us (not that the service idea wouldn't also be some option for OSGi).

**Comment by glatuske** [comment]
@enebo I would recommend to just fetch the FileSystemNotFoundException and do nothing more on that. As you said, the OSGi way would be to use OSGi services; but I guess that's to realistic to change this easily.

**Comment by laumacirule** [comment]
It seems I am running into this same issue when I run a compiled JRuby app as an Atlassian Jira OSGi plugin (Jruby 9.4.7.0, MacOS). Here is the stacktrace:
```
Caused by: java.nio.file.FileSystemNotFoundException: Provider "bundle" not installed
	at java.base/java.nio.file.Path.of(Path.java:212)
	at java.base/java.nio.file.Paths.get(Paths.java:97)
	at org.jruby.util.ClasspathLauncher.getJRubyJar(ClasspathLauncher.java:40)
	at org.jruby.util.ClasspathLauncher.jrubyCommand(ClasspathLauncher.java:48)
	at org.jruby.RubyInstanceConfig.getEnvironment(RubyInstanceConfig.java:679)
	at org.jruby.util.OSEnvironment.environmentVariableMap(OSEnvironment.java:51)
	at org.jruby.RubyGlobal.defineGlobalEnvConstants(RubyGlobal.java:395)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:234)
	at org.jruby.Ruby.<init>(Ruby.java:520)
	at org.jruby.Ruby.newInstance(Ruby.java:723)
```
And as @glatuske mentioned, just fetching the `FileSystemNotFoundException` would be enough to proceed.

**Comment by jimtng** [comment]
I encountered this problem in openHAB too. In my case,

`org.osgi.framework.FrameworkUtil.get_bundle(org.jruby.Main.java_class).location` (called from inside jruby) gave me:
`mvn:org.openhab.addons.bundles/org.openhab.automation.jrubyscripting/4.2.0-SNAPSHOT`

And `Paths.get()` is not able to resolve the `mvn` file system provider either.

So it seems that it's not a straight forward solution to get this resolved in osgi. I've submitted a PR to simply handle `FileSystemNotFoundException` and that seems to solve the problem within my environment.

**Comment by enebo** [comment]
This was resolved as part of the PR but if @glatuske or @laumacirule still see an issue then reopen this.

**Comment by WolfpackMike** [comment]
We have run into this issue as well.  Just curious, is there an estimate for when the 9.4.8.0 release may be available?

**Comment by headius** [comment]
We discussed getting some releases out, and I think 9.4.8.0 could be within the next week.

I just pushed snapshot builds to Maven if that helps!
