### ISSUE TITLE
Upgrade fileutils.

### ISSUE THREAD

**Issue by mashhurs** [jruby/jruby#8296]
### Description
We came across [cannot remove folder, "Directory not empty" issue with `fileutils`](https://github.com/ruby/fileutils/issues/111) in Logstash. It seems `fielutils` [addressed the issue](https://github.com/ruby/fileutils/commit/ec5d3b84ea1e1d1b13c7dcb5bbe6cd5208c20a49) and released 1.7.0 version.
However, Logstash's fileutils usage is through `jruby` (we may pin internally for the short term) and [`jruby` is pinning 1.6.0](https://github.com/jruby/jruby/blob/master/lib/pom.rb#L48) where it would be nice to have it upgraded.

**Comment by ahorek** [comment]
JRuby 9.4.x targets Ruby 3.1.x support which has fileutils 1.6.0 as the default version

$ ruby -v
ruby 3.1.6p260 (2024-05-29 revision a777087be6) [x86_64-linux]
$ gem list fileutils
*** LOCAL GEMS ***
fileutils (default: 1.6.0)

since it's an independent gem, you can still use a newer version by pinning it in your Gemfile

**Comment by headius** [comment]
@mashhurs Yes as @ahorek mentioned, we ship the same version of standard libraries as CRuby but since it is a "default gem", you can upgrade it yourself with gem install or bundler.
