### ISSUE TITLE
Add `REUSE_AS_BINARY_ON_JRUBY` config for rubygems

### ISSUE THREAD

**Issue by ntkme** [jruby/jruby#8381]
TruffleRuby has an internal config called `REUSE_AS_BINARY_ON_TRUFFLERUBY` as well as a command line flag `--reuse-precompiled-gems=foo,bar`. It allows specific platform native gems to be installed without building from source.

For JRuby, this is relevant for `ffi` based extensions (e.g. `google-protobuf` is moving from java to ffi), or extensions that bundles a native executable file (e.g. sass-embedded), because those native extensions should work out of box on JRuby.

https://github.com/rubygems/rubygems/blob/c8542c9e9abffae63ddc3a55c6cbf9e60d39891f/lib/rubygems/platform.rb#L51-L52
https://github.com/oracle/truffleruby/blob/44ded821ff72de16675f320f599e1e97ef0b1786/lib/truffle/rubygems/defaults/truffleruby.rb#L31-L34

**Comment by headius** [comment]
I'm not sure I understand why this is needed. What is the bug this fixes?

If we need to move forward with some fix this seems like it should be something more generic that lives in RubyGems, like just `REUSE_AS_BINARY_GEMS` that we can configure in RubyGems defaults.rb rather than adding implementation-specific constants.

@deivid-rodriguez @eregon Can you help me understand this new constant and why it isn't just a configurable RubyGems default?

**Comment by ntkme** [comment]
> What is the bug this fixes?
Not a bug but rather a feature request. 

This allows the platform native version of ffi based gem to be installed, instead of needing to have compiler toolchain and always compile those extensions.

**Comment by headius** [comment]
> This allows the platform native version of ffi based gem to be installed

So this is for cases where a gem is FFI-based and includes a pre-built binary, to avoid fetching the source version of the gem and building it from scratch.

This definitely seems like it should be in a RubyGems configurable default.

**Comment by headius** [comment]
A side note: this also seems like a hacky way to work around RubyGems having no way to distinguish a "prebuilt native library" from a "prebuilt CRuby extension".

A "prebuilt native library" gem should work on all FFI-capable Rubies.

A "prebuilt CRuby extension" gem includes a prebuilt extension specifically for CRuby. This is the real problem... the platform in the gem is being used for two different things.

**Comment by deivid-rodriguez** [comment]
I agree this is not ideal. Happy to hear proposals to improve things, but this seems quite hard to solve properly to me.

Just for some context. This was started with truffleruby monkeypatching RubyGems by hardcoding specific gems to behave specially. For example, https://github.com/oracle/truffleruby/commit/ae83667c220f52cbea4e83c44d2b9f7027688a3a or https://github.com/oracle/truffleruby/commit/1172b04ef43c2800aef7f39cca9d89df017f637b. Eventually we introduced this constant in RubyGems, so that at least it could be defined in the `defaults` file and we could avoid monkeypatches that make things difficult for everyone.

**Comment by eregon** [comment]
Related discussion: https://github.com/orgs/rubygems/discussions/5988. Option 3 there seems the way to go, but there are plenty of things to figure out and unclear if anyone has time to work on that.
For context, the original issue: https://github.com/rubygems/rubygems/issues/2945 and I upstreamed most of the mentioned logic in RubyGems in https://github.com/rubygems/rubygems/pull/3817.

**Comment by deivid-rodriguez** [comment]
Thanks for mentioning that ticket @eregon, and apologies I never left feedback there.

> Option 3 there seems the way to go, but there are plenty of things to figure out and unclear to me if anyone has time/wants to work on that.

I have the same feeling. The idea seems nice, it just feels like a lot of work, and I'm not sure anyone will be able or want to tackle it.

**Comment by ntkme** [comment]
Closing as it seems to be more appropriate to track this at https://github.com/orgs/rubygems/discussions/5988
