### ISSUE TITLE
Timeout exception may trigger outside of timeout method

### ISSUE THREAD

**Issue by jsvd** [jruby/jruby#8403]
We've noticed this affecting users of Logstash, where the use of a `Timeout::timeout { str.match(/regex/) }` block causes other blocks of `str.match(/regex/)` without being inside a Timeout block to still be timed out by it.
This means that if regex matching in the Timeout block is slow, it starts causing Logstash to raise Timeout::Error in any other location where a regex match is happening, randomly.

The reproducer script is:

```
require 'timeout'
Thread.abort_on_exception = true

threads = 10.times.map do |i|
  Thread.new do
    loop do 
      # first perform a regex with timeout, but throw away any exception
      Timeout::timeout(0.001) { ''.match(/a|b|c|d|e|f|g|h|i|j/) } rescue nil
      # now perform a regex without the timeout
      'logs-generic-default' =~ /%{.*}/
    end
  end
end

threads.each(&:join)
```

**Environment Information**
  
As far I checked, it doesn't seem to occur in JRuby 9.3, only 9.4 but I haven't tried out every single version of 9.4 yet.
```
❯ rvm jruby-9.4.8.0 do ruby -v       
jruby 9.4.8.0 (3.1.4) 2024-07-02 4d41e55a67 OpenJDK 64-Bit Server VM 21.0.2+13-LTS on 21.0.2+13-LTS +jit [arm64-darwin]
```

**Expected Behavior**

JRuby should only trigger timeout exceptions for the block inside `Timeout::timeout`

**Actual Behavior**

```
❯ rvm jruby-9.4.8.0 do ruby script.rb 
warning: thread "Ruby-0-Thread-4: script.rb:5" terminated with exception (report_on_exception is true):
Timeout::Error: execution expired
      =~ at org/jruby/RubyRegexp.java:1113
      =~ at org/jruby/RubyString.java:1737
  <main> at script.rb:10
    loop at org/jruby/RubyKernel.java:1722
  <main> at script.rb:6
Timeout::Error: execution expired
      =~ at org/jruby/RubyRegexp.java:1113
      =~ at org/jruby/RubyString.java:1737
  <main> at script.rb:10
    loop at org/jruby/RubyKernel.java:1722
  <main> at script.rb:6
```

**Comment by headius** [comment]
That is very peculiar! One thing that has changed in 9.4 is that we now ship the standard library version of the timeout gem. This could be a bug there. Also could be that the timeout exception is somehow getting stuck and not cleared after being rescued.

**Comment by headius** [comment]
It does seem like the exception is getting stuck, or firing later than it should. I believe there's a threshold where the timeout will try to fire after the block has exited, so the next Ruby construct that checks for interrupts will receive it. It's not cancelling properly after a successul block.

It is not limited to Regexp matching, either. Here's an example with an empty timeout block and a `print` and it behaves the same (eventually raises where it should not):

```ruby
require 'timeout'
Thread.abort_on_exception = true

thread = Thread.new do
  loop do
    Timeout::timeout(0.001) { } rescue nil
    print '.'
  end
end

thread.join
```

**Comment by jsvd** [comment]
Really cool bug indeed, also nice 1 line is enough:

```
❯ ruby -rtimeout -e "loop { Timeout::timeout(0.001) { } rescue nil; print '.' }"
..............................................................Timeout::Error: execution expired
   write at org/jruby/RubyIO.java:1589
   write at org/jruby/RubyIO.java:1479
   write at org/jruby/RubyIO.java:2853
   print at org/jruby/RubyIO.java:1855
   print at org/jruby/RubyKernel.java:762
  <main> at -e:1
    loop at org/jruby/RubyKernel.java:1722
  <main> at -e:1```

**Comment by headius** [comment]
I think I see where a race occurs in Timeout, and how a small JRuby bug causes it to trigger late.

A little background here: in order to allow interrupting operations across threads, JRuby periodically polls some bits in the Thread object that indicate whether an interrupt has been set. Based on these bits, the thread could start to `kill` itself, or `raise` an exception from another thread. Checking for this interrupt is not free, so we try to do it only at times where it is likely to be important, like when doing IO operations or waking from a `sleep`.

I believe the problem here is that one of these interrupts is not being handled within the boundary of the `timeout` method, and lingers until the next interrupt check.

So then there's Timeout...

Timeout uses a `synchronize` block to guard a flag that marks whether the timeout block has finished in time. If the flag is set, the timeout error will not fire.

Here's the block that triggers the timeout error:

```ruby
def interrupt
  @mutex.synchronize do
    unless @done
      @thread.raise @exception_class, @message
      @done = true
    end
  end
end
```

The `finished` method is called after the block passed to `timeout` returns from its yield:

```ruby
def finished
  @mutex.synchronize do
    @done = true
  end
end
```

And here's where the block is yielded:

```ruby
request = Request.new(Thread.current, sec, exc, message)
QUEUE_MUTEX.synchronize do
  QUEUE << request
  CONDVAR.signal
end
begin
  return yield(sec)
ensure
  request.finished
end
```

I believe what's happening goes like this:

* Timeout fires after the block yield has returned (and after any interrupt-checking code has run), likely within `finished` before the `synchronize` call. A thread interrupt is set to trigger an exception.
* The `finished` method has no code that would check for an interrupt, so it sets `@done` and returns. There's now an unhandled exception interrupt on the thread.
* The `timeout` method itself returns which also does not trigger the interrupt.
* Finally, in user code outside of the `timeout` call, some call or operation checks for a thread interrupt and the exception triggers.

If I add a `print` to the `synchronize` block in `finish`, the bug never happens because `print` triggers the interrupt check.

So the issue is that we can get all the way out of the `timeout` method without detecting the interrupt if it happens along that thin edge after the block has returned but before `timeout` returns.

There's a couple of possible fixes:

* Mutex#synchronize should check for thread interrupts upon acquiring the lock. This would cause the interrupt to fire after `finished` completes but before exiting `timeout`, and it would raise normally. If there are no interrupts after we have acquired the lock, there's no way the timeout could fire, so we are safe to proceed. Locally, this fixes the issue for me, and probably makes some sense (once the thread wakes from waiting, it should check for any interrupts it missed).

  The interrupt poll would go somewhere around here: https://github.com/jruby/jruby/blob/972548098217118bdb5b0b0979c08d60866aea6e/core/src/main/java/org/jruby/ext/thread/Mutex.java#L133

* The `finished` method in Timeout could also try to trigger any interrupt by using `Thread.handle_interrupt`. If I patch `finished` to do that, it also fixes the bug:
  ```ruby
  def finished
    @mutex.synchronize do
      @done = true
    end
    # force any pending interrupt to fire
    Thread.handle_interrupt(Object => :immediate) {}
  end
  ```

I suspect other implementations do not run into this because they are either:

* not parallel enough (CRuby checks these interrupts on every GVL transfer, so if the timeout thread runs and triggers the exception, the target thread will see it when it runs again), OR
* they already check interrupts along these boundaries (I could not trigger the same issue in TruffleRuby).

At the very least I think we should move forward with the Mutex patch.

**Comment by headius** [comment]
As for why this changed when we went to the pure-Ruby timeout.rb:

The old Java-based implementation was much more explicit about handling interrupts. If the timeout did not expire, it was immediately and atomically cancelled, so there was no chance of triggering on a weird edge. And if the cancellation failed, we knew the timeout had fired and should let it raise.

The Ruby version relies more heavily on asynchronous thread interrupts, and because we don't check those after every line of code we ended up triggering the raise too late.

Fixing Mutex to check for interrupts after any sleep or lock wait makes sense since any number of thread events might have fired in the meantime.

**Comment by headius** [comment]
Pushed https://github.com/jruby/jruby/pull/8404 to add interrupt checking to `Mutex#lock`.

**Comment by jsvd** [comment]
Thank you for the quick fix, I confirmed https://oss.sonatype.org/content/repositories/snapshots/org/jruby/jruby-core/9.4.9.0-SNAPSHOT/jruby-core-9.4.9.0-20241104.063911-133.jar doesn't trigger the single threaded issue any more.

I do still see an issue with multi threading though. Using the latest snapshot:

```
/tmp/jruby-9.4.9.0-SNAPSHOT
❯ bin/jruby -v
jruby 9.4.9.0-SNAPSHOT (3.1.4) 2024-11-04 746b84aa02 OpenJDK 64-Bit Server VM 21.0.2+13-LTS on 21.0.2+13-LTS +jit [arm64-darwin]
```

1 thread seems to work fine:

```
❯ time JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e "timeout = 0.001; 1.times.map { Thread.new { 10_000_000.times { Timeout::timeout(timeout) { } rescue nil; } } }.each(&:join)"
JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e   67.62s user 11.53s system 143% cpu 55.135 total
```

but with 2 threads the process OOMs eventually:

```
/tmp/jruby-9.4.9.0-SNAPSHOT
❯ time JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e "timeout = 0.001; 2.times.map { Thread.new { 10_000_000.times { Timeout::timeout(timeout) { } rescue nil; } } }.each(&:join)"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-1: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-2: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e   332.54s user 26.38s system 137% cpu 4:20.93 total
```

same but much faster with 10 threads:

```
/tmp/jruby-9.4.9.0-SNAPSHOT
❯ time JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e "timeout = 0.001; 10.times.map { Thread.new { 10_000_000.times { Timeout::timeout(timeout) { } rescue nil; } } }.each(&:join)"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-3: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-2: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-6: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-7: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-8: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-10: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-4: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-5: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-9: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Ruby-0-Thread-1: -e:1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "main"

JRUBY_OPTS="-J-Xmx128m -Xreify.classes=true" bin/jruby -rtimeout -e   142.85s user 1.79s system 289% cpu 50.048 total
```

**Comment by headius** [comment]
Confirmed! That's pretty peculiar... I will have a look. Nobody else has reported this, which is surprising for such an easy-to-trigger OOM.

**Comment by headius** [comment]
Could you file a new issue with this info please?

**Comment by jsvd** [comment]
Done #8406
